version: "2"
linters:
  enable:
    - gosec
    - misspell
  settings:
    gosec:
      excludes:
        - G402
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: kanidm/client\.go
        text: G402
      - linters:
          - errcheck
        path: tests/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
