/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type AccountAPI interface {

	/*
	AccountIdRadiusTokenGet Method for AccountIdRadiusTokenGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return AccountAPIAccountIdRadiusTokenGetRequest
	*/
	AccountIdRadiusTokenGet(ctx context.Context, id string) AccountAPIAccountIdRadiusTokenGetRequest

	// AccountIdRadiusTokenGetExecute executes the request
	//  @return RadiusAuthToken
	AccountIdRadiusTokenGetExecute(r AccountAPIAccountIdRadiusTokenGetRequest) (*RadiusAuthToken, *http.Response, error)

	/*
	AccountIdRadiusTokenPost Method for AccountIdRadiusTokenPost

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return AccountAPIAccountIdRadiusTokenPostRequest
	*/
	AccountIdRadiusTokenPost(ctx context.Context, id string) AccountAPIAccountIdRadiusTokenPostRequest

	// AccountIdRadiusTokenPostExecute executes the request
	//  @return RadiusAuthToken
	AccountIdRadiusTokenPostExecute(r AccountAPIAccountIdRadiusTokenPostRequest) (*RadiusAuthToken, *http.Response, error)

	/*
	AccountIdSshPubkeysGet Method for AccountIdSshPubkeysGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return AccountAPIAccountIdSshPubkeysGetRequest

	Deprecated
	*/
	AccountIdSshPubkeysGet(ctx context.Context, id string) AccountAPIAccountIdSshPubkeysGetRequest

	// AccountIdSshPubkeysGetExecute executes the request
	//  @return []string
	// Deprecated
	AccountIdSshPubkeysGetExecute(r AccountAPIAccountIdSshPubkeysGetRequest) ([]string, *http.Response, error)

	/*
	AccountIdSshPubkeysTagGet Method for AccountIdSshPubkeysTagGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param tag
	@return AccountAPIAccountIdSshPubkeysTagGetRequest
	*/
	AccountIdSshPubkeysTagGet(ctx context.Context, id string, tag string) AccountAPIAccountIdSshPubkeysTagGetRequest

	// AccountIdSshPubkeysTagGetExecute executes the request
	//  @return string
	AccountIdSshPubkeysTagGetExecute(r AccountAPIAccountIdSshPubkeysTagGetRequest) (string, *http.Response, error)

	/*
	AccountIdUnixAuthPost Method for AccountIdUnixAuthPost

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return AccountAPIAccountIdUnixAuthPostRequest
	*/
	AccountIdUnixAuthPost(ctx context.Context, id string) AccountAPIAccountIdUnixAuthPostRequest

	// AccountIdUnixAuthPostExecute executes the request
	//  @return UnixUserToken
	AccountIdUnixAuthPostExecute(r AccountAPIAccountIdUnixAuthPostRequest) (*UnixUserToken, *http.Response, error)

	/*
	AccountIdUnixToken Method for AccountIdUnixToken

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return AccountAPIAccountIdUnixTokenRequest
	*/
	AccountIdUnixToken(ctx context.Context, id string) AccountAPIAccountIdUnixTokenRequest

	// AccountIdUnixTokenExecute executes the request
	//  @return UnixUserToken
	AccountIdUnixTokenExecute(r AccountAPIAccountIdUnixTokenRequest) (*UnixUserToken, *http.Response, error)

	/*
	AccountIdUserAuthTokenGet Method for AccountIdUserAuthTokenGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return AccountAPIAccountIdUserAuthTokenGetRequest
	*/
	AccountIdUserAuthTokenGet(ctx context.Context, id string) AccountAPIAccountIdUserAuthTokenGetRequest

	// AccountIdUserAuthTokenGetExecute executes the request
	AccountIdUserAuthTokenGetExecute(r AccountAPIAccountIdUserAuthTokenGetRequest) (*http.Response, error)

	/*
	AccountUserAuthTokenDelete Method for AccountUserAuthTokenDelete

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param tokenId
	@return AccountAPIAccountUserAuthTokenDeleteRequest
	*/
	AccountUserAuthTokenDelete(ctx context.Context, id string, tokenId string) AccountAPIAccountUserAuthTokenDeleteRequest

	// AccountUserAuthTokenDeleteExecute executes the request
	AccountUserAuthTokenDeleteExecute(r AccountAPIAccountUserAuthTokenDeleteRequest) (*http.Response, error)
}

// AccountAPIService AccountAPI service
type AccountAPIService service

type AccountAPIAccountIdRadiusTokenGetRequest struct {
	ctx context.Context
	ApiService AccountAPI
	id string
}

func (r AccountAPIAccountIdRadiusTokenGetRequest) Execute() (*RadiusAuthToken, *http.Response, error) {
	return r.ApiService.AccountIdRadiusTokenGetExecute(r)
}

/*
AccountIdRadiusTokenGet Method for AccountIdRadiusTokenGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return AccountAPIAccountIdRadiusTokenGetRequest
*/
func (a *AccountAPIService) AccountIdRadiusTokenGet(ctx context.Context, id string) AccountAPIAccountIdRadiusTokenGetRequest {
	return AccountAPIAccountIdRadiusTokenGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return RadiusAuthToken
func (a *AccountAPIService) AccountIdRadiusTokenGetExecute(r AccountAPIAccountIdRadiusTokenGetRequest) (*RadiusAuthToken, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *RadiusAuthToken
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccountAPIService.AccountIdRadiusTokenGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/account/{id}/_radius/_token"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AccountAPIAccountIdRadiusTokenPostRequest struct {
	ctx context.Context
	ApiService AccountAPI
	id string
}

func (r AccountAPIAccountIdRadiusTokenPostRequest) Execute() (*RadiusAuthToken, *http.Response, error) {
	return r.ApiService.AccountIdRadiusTokenPostExecute(r)
}

/*
AccountIdRadiusTokenPost Method for AccountIdRadiusTokenPost

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return AccountAPIAccountIdRadiusTokenPostRequest
*/
func (a *AccountAPIService) AccountIdRadiusTokenPost(ctx context.Context, id string) AccountAPIAccountIdRadiusTokenPostRequest {
	return AccountAPIAccountIdRadiusTokenPostRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return RadiusAuthToken
func (a *AccountAPIService) AccountIdRadiusTokenPostExecute(r AccountAPIAccountIdRadiusTokenPostRequest) (*RadiusAuthToken, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *RadiusAuthToken
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccountAPIService.AccountIdRadiusTokenPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/account/{id}/_radius/_token"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AccountAPIAccountIdSshPubkeysGetRequest struct {
	ctx context.Context
	ApiService AccountAPI
	id string
}

func (r AccountAPIAccountIdSshPubkeysGetRequest) Execute() ([]string, *http.Response, error) {
	return r.ApiService.AccountIdSshPubkeysGetExecute(r)
}

/*
AccountIdSshPubkeysGet Method for AccountIdSshPubkeysGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return AccountAPIAccountIdSshPubkeysGetRequest

Deprecated
*/
func (a *AccountAPIService) AccountIdSshPubkeysGet(ctx context.Context, id string) AccountAPIAccountIdSshPubkeysGetRequest {
	return AccountAPIAccountIdSshPubkeysGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return []string
// Deprecated
func (a *AccountAPIService) AccountIdSshPubkeysGetExecute(r AccountAPIAccountIdSshPubkeysGetRequest) ([]string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccountAPIService.AccountIdSshPubkeysGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/account/{id}/_ssh_pubkeys"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AccountAPIAccountIdSshPubkeysTagGetRequest struct {
	ctx context.Context
	ApiService AccountAPI
	id string
	tag string
}

func (r AccountAPIAccountIdSshPubkeysTagGetRequest) Execute() (string, *http.Response, error) {
	return r.ApiService.AccountIdSshPubkeysTagGetExecute(r)
}

/*
AccountIdSshPubkeysTagGet Method for AccountIdSshPubkeysTagGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param tag
 @return AccountAPIAccountIdSshPubkeysTagGetRequest
*/
func (a *AccountAPIService) AccountIdSshPubkeysTagGet(ctx context.Context, id string, tag string) AccountAPIAccountIdSshPubkeysTagGetRequest {
	return AccountAPIAccountIdSshPubkeysTagGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		tag: tag,
	}
}

// Execute executes the request
//  @return string
func (a *AccountAPIService) AccountIdSshPubkeysTagGetExecute(r AccountAPIAccountIdSshPubkeysTagGetRequest) (string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccountAPIService.AccountIdSshPubkeysTagGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/account/{id}/_ssh_pubkeys/{tag}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"tag"+"}", url.PathEscape(parameterValueToString(r.tag, "tag")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AccountAPIAccountIdUnixAuthPostRequest struct {
	ctx context.Context
	ApiService AccountAPI
	id string
	singleStringRequest *SingleStringRequest
}

func (r AccountAPIAccountIdUnixAuthPostRequest) SingleStringRequest(singleStringRequest SingleStringRequest) AccountAPIAccountIdUnixAuthPostRequest {
	r.singleStringRequest = &singleStringRequest
	return r
}

func (r AccountAPIAccountIdUnixAuthPostRequest) Execute() (*UnixUserToken, *http.Response, error) {
	return r.ApiService.AccountIdUnixAuthPostExecute(r)
}

/*
AccountIdUnixAuthPost Method for AccountIdUnixAuthPost

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return AccountAPIAccountIdUnixAuthPostRequest
*/
func (a *AccountAPIService) AccountIdUnixAuthPost(ctx context.Context, id string) AccountAPIAccountIdUnixAuthPostRequest {
	return AccountAPIAccountIdUnixAuthPostRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return UnixUserToken
func (a *AccountAPIService) AccountIdUnixAuthPostExecute(r AccountAPIAccountIdUnixAuthPostRequest) (*UnixUserToken, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *UnixUserToken
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccountAPIService.AccountIdUnixAuthPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/account/{id}/_unix/_auth"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.singleStringRequest == nil {
		return localVarReturnValue, nil, reportError("singleStringRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.singleStringRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AccountAPIAccountIdUnixTokenRequest struct {
	ctx context.Context
	ApiService AccountAPI
	id string
}

func (r AccountAPIAccountIdUnixTokenRequest) Execute() (*UnixUserToken, *http.Response, error) {
	return r.ApiService.AccountIdUnixTokenExecute(r)
}

/*
AccountIdUnixToken Method for AccountIdUnixToken

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return AccountAPIAccountIdUnixTokenRequest
*/
func (a *AccountAPIService) AccountIdUnixToken(ctx context.Context, id string) AccountAPIAccountIdUnixTokenRequest {
	return AccountAPIAccountIdUnixTokenRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return UnixUserToken
func (a *AccountAPIService) AccountIdUnixTokenExecute(r AccountAPIAccountIdUnixTokenRequest) (*UnixUserToken, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *UnixUserToken
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccountAPIService.AccountIdUnixToken")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/account/{id}/_unix/_token"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type AccountAPIAccountIdUserAuthTokenGetRequest struct {
	ctx context.Context
	ApiService AccountAPI
	id string
}

func (r AccountAPIAccountIdUserAuthTokenGetRequest) Execute() (*http.Response, error) {
	return r.ApiService.AccountIdUserAuthTokenGetExecute(r)
}

/*
AccountIdUserAuthTokenGet Method for AccountIdUserAuthTokenGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return AccountAPIAccountIdUserAuthTokenGetRequest
*/
func (a *AccountAPIService) AccountIdUserAuthTokenGet(ctx context.Context, id string) AccountAPIAccountIdUserAuthTokenGetRequest {
	return AccountAPIAccountIdUserAuthTokenGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *AccountAPIService) AccountIdUserAuthTokenGetExecute(r AccountAPIAccountIdUserAuthTokenGetRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccountAPIService.AccountIdUserAuthTokenGet")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/account/{id}/_user_auth_token"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type AccountAPIAccountUserAuthTokenDeleteRequest struct {
	ctx context.Context
	ApiService AccountAPI
	id string
	tokenId string
}

func (r AccountAPIAccountUserAuthTokenDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.AccountUserAuthTokenDeleteExecute(r)
}

/*
AccountUserAuthTokenDelete Method for AccountUserAuthTokenDelete

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param tokenId
 @return AccountAPIAccountUserAuthTokenDeleteRequest
*/
func (a *AccountAPIService) AccountUserAuthTokenDelete(ctx context.Context, id string, tokenId string) AccountAPIAccountUserAuthTokenDeleteRequest {
	return AccountAPIAccountUserAuthTokenDeleteRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		tokenId: tokenId,
	}
}

// Execute executes the request
func (a *AccountAPIService) AccountUserAuthTokenDeleteExecute(r AccountAPIAccountUserAuthTokenDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AccountAPIService.AccountUserAuthTokenDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/account/{id}/_user_auth_token/{token_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"token_id"+"}", url.PathEscape(parameterValueToString(r.tokenId, "tokenId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
