/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type PersonUnixAPI interface {

	/*
	PersonIdUnixCredentialDelete Method for PersonIdUnixCredentialDelete

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return PersonUnixAPIPersonIdUnixCredentialDeleteRequest
	*/
	PersonIdUnixCredentialDelete(ctx context.Context, id string) PersonUnixAPIPersonIdUnixCredentialDeleteRequest

	// PersonIdUnixCredentialDeleteExecute executes the request
	PersonIdUnixCredentialDeleteExecute(r PersonUnixAPIPersonIdUnixCredentialDeleteRequest) (*http.Response, error)

	/*
	PersonIdUnixCredentialPut Method for PersonIdUnixCredentialPut

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return PersonUnixAPIPersonIdUnixCredentialPutRequest
	*/
	PersonIdUnixCredentialPut(ctx context.Context, id string) PersonUnixAPIPersonIdUnixCredentialPutRequest

	// PersonIdUnixCredentialPutExecute executes the request
	PersonIdUnixCredentialPutExecute(r PersonUnixAPIPersonIdUnixCredentialPutRequest) (*http.Response, error)

	/*
	PersonIdUnixPost Method for PersonIdUnixPost

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return PersonUnixAPIPersonIdUnixPostRequest
	*/
	PersonIdUnixPost(ctx context.Context, id string) PersonUnixAPIPersonIdUnixPostRequest

	// PersonIdUnixPostExecute executes the request
	PersonIdUnixPostExecute(r PersonUnixAPIPersonIdUnixPostRequest) (*http.Response, error)
}

// PersonUnixAPIService PersonUnixAPI service
type PersonUnixAPIService service

type PersonUnixAPIPersonIdUnixCredentialDeleteRequest struct {
	ctx context.Context
	ApiService PersonUnixAPI
	id string
}

func (r PersonUnixAPIPersonIdUnixCredentialDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.PersonIdUnixCredentialDeleteExecute(r)
}

/*
PersonIdUnixCredentialDelete Method for PersonIdUnixCredentialDelete

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return PersonUnixAPIPersonIdUnixCredentialDeleteRequest
*/
func (a *PersonUnixAPIService) PersonIdUnixCredentialDelete(ctx context.Context, id string) PersonUnixAPIPersonIdUnixCredentialDeleteRequest {
	return PersonUnixAPIPersonIdUnixCredentialDeleteRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *PersonUnixAPIService) PersonIdUnixCredentialDeleteExecute(r PersonUnixAPIPersonIdUnixCredentialDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonUnixAPIService.PersonIdUnixCredentialDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_unix/_credential"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type PersonUnixAPIPersonIdUnixCredentialPutRequest struct {
	ctx context.Context
	ApiService PersonUnixAPI
	id string
	singleStringRequest *SingleStringRequest
}

func (r PersonUnixAPIPersonIdUnixCredentialPutRequest) SingleStringRequest(singleStringRequest SingleStringRequest) PersonUnixAPIPersonIdUnixCredentialPutRequest {
	r.singleStringRequest = &singleStringRequest
	return r
}

func (r PersonUnixAPIPersonIdUnixCredentialPutRequest) Execute() (*http.Response, error) {
	return r.ApiService.PersonIdUnixCredentialPutExecute(r)
}

/*
PersonIdUnixCredentialPut Method for PersonIdUnixCredentialPut

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return PersonUnixAPIPersonIdUnixCredentialPutRequest
*/
func (a *PersonUnixAPIService) PersonIdUnixCredentialPut(ctx context.Context, id string) PersonUnixAPIPersonIdUnixCredentialPutRequest {
	return PersonUnixAPIPersonIdUnixCredentialPutRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *PersonUnixAPIService) PersonIdUnixCredentialPutExecute(r PersonUnixAPIPersonIdUnixCredentialPutRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonUnixAPIService.PersonIdUnixCredentialPut")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_unix/_credential"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.singleStringRequest == nil {
		return nil, reportError("singleStringRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.singleStringRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type PersonUnixAPIPersonIdUnixPostRequest struct {
	ctx context.Context
	ApiService PersonUnixAPI
	id string
	accountUnixExtend *AccountUnixExtend
}

func (r PersonUnixAPIPersonIdUnixPostRequest) AccountUnixExtend(accountUnixExtend AccountUnixExtend) PersonUnixAPIPersonIdUnixPostRequest {
	r.accountUnixExtend = &accountUnixExtend
	return r
}

func (r PersonUnixAPIPersonIdUnixPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.PersonIdUnixPostExecute(r)
}

/*
PersonIdUnixPost Method for PersonIdUnixPost

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return PersonUnixAPIPersonIdUnixPostRequest
*/
func (a *PersonUnixAPIService) PersonIdUnixPost(ctx context.Context, id string) PersonUnixAPIPersonIdUnixPostRequest {
	return PersonUnixAPIPersonIdUnixPostRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *PersonUnixAPIService) PersonIdUnixPostExecute(r PersonUnixAPIPersonIdUnixPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonUnixAPIService.PersonIdUnixPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_unix"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.accountUnixExtend == nil {
		return nil, reportError("accountUnixExtend is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.accountUnixExtend
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
