/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type PersonSshPubkeysAPI interface {

	/*
	PersonIdSshPubkeysGet Method for PersonIdSshPubkeysGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return PersonSshPubkeysAPIPersonIdSshPubkeysGetRequest
	*/
	PersonIdSshPubkeysGet(ctx context.Context, id string) PersonSshPubkeysAPIPersonIdSshPubkeysGetRequest

	// PersonIdSshPubkeysGetExecute executes the request
	//  @return []string
	PersonIdSshPubkeysGetExecute(r PersonSshPubkeysAPIPersonIdSshPubkeysGetRequest) ([]string, *http.Response, error)

	/*
	PersonIdSshPubkeysPost Method for PersonIdSshPubkeysPost

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return PersonSshPubkeysAPIPersonIdSshPubkeysPostRequest
	*/
	PersonIdSshPubkeysPost(ctx context.Context, id string) PersonSshPubkeysAPIPersonIdSshPubkeysPostRequest

	// PersonIdSshPubkeysPostExecute executes the request
	PersonIdSshPubkeysPostExecute(r PersonSshPubkeysAPIPersonIdSshPubkeysPostRequest) (*http.Response, error)

	/*
	PersonIdSshPubkeysTagDelete Method for PersonIdSshPubkeysTagDelete

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param tag The tag of the SSH key
	@param id
	@return PersonSshPubkeysAPIPersonIdSshPubkeysTagDeleteRequest
	*/
	PersonIdSshPubkeysTagDelete(ctx context.Context, tag string, id string) PersonSshPubkeysAPIPersonIdSshPubkeysTagDeleteRequest

	// PersonIdSshPubkeysTagDeleteExecute executes the request
	PersonIdSshPubkeysTagDeleteExecute(r PersonSshPubkeysAPIPersonIdSshPubkeysTagDeleteRequest) (*http.Response, error)

	/*
	PersonIdSshPubkeysTagGet Method for PersonIdSshPubkeysTagGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param tag
	@return PersonSshPubkeysAPIPersonIdSshPubkeysTagGetRequest
	*/
	PersonIdSshPubkeysTagGet(ctx context.Context, id string, tag string) PersonSshPubkeysAPIPersonIdSshPubkeysTagGetRequest

	// PersonIdSshPubkeysTagGetExecute executes the request
	//  @return string
	PersonIdSshPubkeysTagGetExecute(r PersonSshPubkeysAPIPersonIdSshPubkeysTagGetRequest) (string, *http.Response, error)
}

// PersonSshPubkeysAPIService PersonSshPubkeysAPI service
type PersonSshPubkeysAPIService service

type PersonSshPubkeysAPIPersonIdSshPubkeysGetRequest struct {
	ctx context.Context
	ApiService PersonSshPubkeysAPI
	id string
}

func (r PersonSshPubkeysAPIPersonIdSshPubkeysGetRequest) Execute() ([]string, *http.Response, error) {
	return r.ApiService.PersonIdSshPubkeysGetExecute(r)
}

/*
PersonIdSshPubkeysGet Method for PersonIdSshPubkeysGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return PersonSshPubkeysAPIPersonIdSshPubkeysGetRequest
*/
func (a *PersonSshPubkeysAPIService) PersonIdSshPubkeysGet(ctx context.Context, id string) PersonSshPubkeysAPIPersonIdSshPubkeysGetRequest {
	return PersonSshPubkeysAPIPersonIdSshPubkeysGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return []string
func (a *PersonSshPubkeysAPIService) PersonIdSshPubkeysGetExecute(r PersonSshPubkeysAPIPersonIdSshPubkeysGetRequest) ([]string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonSshPubkeysAPIService.PersonIdSshPubkeysGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_ssh_pubkeys"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PersonSshPubkeysAPIPersonIdSshPubkeysPostRequest struct {
	ctx context.Context
	ApiService PersonSshPubkeysAPI
	id string
	requestBody *[]interface{}
}

func (r PersonSshPubkeysAPIPersonIdSshPubkeysPostRequest) RequestBody(requestBody []interface{}) PersonSshPubkeysAPIPersonIdSshPubkeysPostRequest {
	r.requestBody = &requestBody
	return r
}

func (r PersonSshPubkeysAPIPersonIdSshPubkeysPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.PersonIdSshPubkeysPostExecute(r)
}

/*
PersonIdSshPubkeysPost Method for PersonIdSshPubkeysPost

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return PersonSshPubkeysAPIPersonIdSshPubkeysPostRequest
*/
func (a *PersonSshPubkeysAPIService) PersonIdSshPubkeysPost(ctx context.Context, id string) PersonSshPubkeysAPIPersonIdSshPubkeysPostRequest {
	return PersonSshPubkeysAPIPersonIdSshPubkeysPostRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *PersonSshPubkeysAPIService) PersonIdSshPubkeysPostExecute(r PersonSshPubkeysAPIPersonIdSshPubkeysPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonSshPubkeysAPIService.PersonIdSshPubkeysPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_ssh_pubkeys"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestBody == nil {
		return nil, reportError("requestBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json", "text/plain"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type PersonSshPubkeysAPIPersonIdSshPubkeysTagDeleteRequest struct {
	ctx context.Context
	ApiService PersonSshPubkeysAPI
	tag string
	id string
}

func (r PersonSshPubkeysAPIPersonIdSshPubkeysTagDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.PersonIdSshPubkeysTagDeleteExecute(r)
}

/*
PersonIdSshPubkeysTagDelete Method for PersonIdSshPubkeysTagDelete

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param tag The tag of the SSH key
 @param id
 @return PersonSshPubkeysAPIPersonIdSshPubkeysTagDeleteRequest
*/
func (a *PersonSshPubkeysAPIService) PersonIdSshPubkeysTagDelete(ctx context.Context, tag string, id string) PersonSshPubkeysAPIPersonIdSshPubkeysTagDeleteRequest {
	return PersonSshPubkeysAPIPersonIdSshPubkeysTagDeleteRequest{
		ApiService: a,
		ctx: ctx,
		tag: tag,
		id: id,
	}
}

// Execute executes the request
func (a *PersonSshPubkeysAPIService) PersonIdSshPubkeysTagDeleteExecute(r PersonSshPubkeysAPIPersonIdSshPubkeysTagDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonSshPubkeysAPIService.PersonIdSshPubkeysTagDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_ssh_pubkeys/{tag}"
	localVarPath = strings.Replace(localVarPath, "{"+"tag"+"}", url.PathEscape(parameterValueToString(r.tag, "tag")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type PersonSshPubkeysAPIPersonIdSshPubkeysTagGetRequest struct {
	ctx context.Context
	ApiService PersonSshPubkeysAPI
	id string
	tag string
}

func (r PersonSshPubkeysAPIPersonIdSshPubkeysTagGetRequest) Execute() (string, *http.Response, error) {
	return r.ApiService.PersonIdSshPubkeysTagGetExecute(r)
}

/*
PersonIdSshPubkeysTagGet Method for PersonIdSshPubkeysTagGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param tag
 @return PersonSshPubkeysAPIPersonIdSshPubkeysTagGetRequest
*/
func (a *PersonSshPubkeysAPIService) PersonIdSshPubkeysTagGet(ctx context.Context, id string, tag string) PersonSshPubkeysAPIPersonIdSshPubkeysTagGetRequest {
	return PersonSshPubkeysAPIPersonIdSshPubkeysTagGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		tag: tag,
	}
}

// Execute executes the request
//  @return string
func (a *PersonSshPubkeysAPIService) PersonIdSshPubkeysTagGetExecute(r PersonSshPubkeysAPIPersonIdSshPubkeysTagGetRequest) (string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonSshPubkeysAPIService.PersonIdSshPubkeysTagGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_ssh_pubkeys/{tag}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"tag"+"}", url.PathEscape(parameterValueToString(r.tag, "tag")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
