/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type PersonCredentialAPI interface {

	/*
	PersonGetIdCredentialStatus Method for PersonGetIdCredentialStatus

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return PersonCredentialAPIPersonGetIdCredentialStatusRequest
	*/
	PersonGetIdCredentialStatus(ctx context.Context, id string) PersonCredentialAPIPersonGetIdCredentialStatusRequest

	// PersonGetIdCredentialStatusExecute executes the request
	PersonGetIdCredentialStatusExecute(r PersonCredentialAPIPersonGetIdCredentialStatusRequest) (*http.Response, error)

	/*
	PersonIdCredentialUpdateGet Method for PersonIdCredentialUpdateGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return PersonCredentialAPIPersonIdCredentialUpdateGetRequest
	*/
	PersonIdCredentialUpdateGet(ctx context.Context, id string) PersonCredentialAPIPersonIdCredentialUpdateGetRequest

	// PersonIdCredentialUpdateGetExecute executes the request
	PersonIdCredentialUpdateGetExecute(r PersonCredentialAPIPersonIdCredentialUpdateGetRequest) (*http.Response, error)

	/*
	PersonIdCredentialUpdateIntentGet Method for PersonIdCredentialUpdateIntentGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return PersonCredentialAPIPersonIdCredentialUpdateIntentGetRequest
	*/
	PersonIdCredentialUpdateIntentGet(ctx context.Context, id string) PersonCredentialAPIPersonIdCredentialUpdateIntentGetRequest

	// PersonIdCredentialUpdateIntentGetExecute executes the request
	PersonIdCredentialUpdateIntentGetExecute(r PersonCredentialAPIPersonIdCredentialUpdateIntentGetRequest) (*http.Response, error)

	/*
	PersonIdCredentialUpdateIntentSendPost Method for PersonIdCredentialUpdateIntentSendPost

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return PersonCredentialAPIPersonIdCredentialUpdateIntentSendPostRequest
	*/
	PersonIdCredentialUpdateIntentSendPost(ctx context.Context, id string) PersonCredentialAPIPersonIdCredentialUpdateIntentSendPostRequest

	// PersonIdCredentialUpdateIntentSendPostExecute executes the request
	PersonIdCredentialUpdateIntentSendPostExecute(r PersonCredentialAPIPersonIdCredentialUpdateIntentSendPostRequest) (*http.Response, error)

	/*
	PersonIdCredentialUpdateIntentTtlGet Method for PersonIdCredentialUpdateIntentTtlGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param ttl The new TTL for the credential?
	@param id
	@return PersonCredentialAPIPersonIdCredentialUpdateIntentTtlGetRequest
	*/
	PersonIdCredentialUpdateIntentTtlGet(ctx context.Context, ttl int64, id string) PersonCredentialAPIPersonIdCredentialUpdateIntentTtlGetRequest

	// PersonIdCredentialUpdateIntentTtlGetExecute executes the request
	//  @return CUIntentToken
	PersonIdCredentialUpdateIntentTtlGetExecute(r PersonCredentialAPIPersonIdCredentialUpdateIntentTtlGetRequest) (*CUIntentToken, *http.Response, error)
}

// PersonCredentialAPIService PersonCredentialAPI service
type PersonCredentialAPIService service

type PersonCredentialAPIPersonGetIdCredentialStatusRequest struct {
	ctx context.Context
	ApiService PersonCredentialAPI
	id string
}

func (r PersonCredentialAPIPersonGetIdCredentialStatusRequest) Execute() (*http.Response, error) {
	return r.ApiService.PersonGetIdCredentialStatusExecute(r)
}

/*
PersonGetIdCredentialStatus Method for PersonGetIdCredentialStatus

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return PersonCredentialAPIPersonGetIdCredentialStatusRequest
*/
func (a *PersonCredentialAPIService) PersonGetIdCredentialStatus(ctx context.Context, id string) PersonCredentialAPIPersonGetIdCredentialStatusRequest {
	return PersonCredentialAPIPersonGetIdCredentialStatusRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *PersonCredentialAPIService) PersonGetIdCredentialStatusExecute(r PersonCredentialAPIPersonGetIdCredentialStatusRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonCredentialAPIService.PersonGetIdCredentialStatus")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_credential/_status"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type PersonCredentialAPIPersonIdCredentialUpdateGetRequest struct {
	ctx context.Context
	ApiService PersonCredentialAPI
	id string
}

func (r PersonCredentialAPIPersonIdCredentialUpdateGetRequest) Execute() (*http.Response, error) {
	return r.ApiService.PersonIdCredentialUpdateGetExecute(r)
}

/*
PersonIdCredentialUpdateGet Method for PersonIdCredentialUpdateGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return PersonCredentialAPIPersonIdCredentialUpdateGetRequest
*/
func (a *PersonCredentialAPIService) PersonIdCredentialUpdateGet(ctx context.Context, id string) PersonCredentialAPIPersonIdCredentialUpdateGetRequest {
	return PersonCredentialAPIPersonIdCredentialUpdateGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *PersonCredentialAPIService) PersonIdCredentialUpdateGetExecute(r PersonCredentialAPIPersonIdCredentialUpdateGetRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonCredentialAPIService.PersonIdCredentialUpdateGet")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_credential/_update"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type PersonCredentialAPIPersonIdCredentialUpdateIntentGetRequest struct {
	ctx context.Context
	ApiService PersonCredentialAPI
	id string
}

func (r PersonCredentialAPIPersonIdCredentialUpdateIntentGetRequest) Execute() (*http.Response, error) {
	return r.ApiService.PersonIdCredentialUpdateIntentGetExecute(r)
}

/*
PersonIdCredentialUpdateIntentGet Method for PersonIdCredentialUpdateIntentGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return PersonCredentialAPIPersonIdCredentialUpdateIntentGetRequest
*/
func (a *PersonCredentialAPIService) PersonIdCredentialUpdateIntentGet(ctx context.Context, id string) PersonCredentialAPIPersonIdCredentialUpdateIntentGetRequest {
	return PersonCredentialAPIPersonIdCredentialUpdateIntentGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *PersonCredentialAPIService) PersonIdCredentialUpdateIntentGetExecute(r PersonCredentialAPIPersonIdCredentialUpdateIntentGetRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonCredentialAPIService.PersonIdCredentialUpdateIntentGet")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_credential/_update_intent"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type PersonCredentialAPIPersonIdCredentialUpdateIntentSendPostRequest struct {
	ctx context.Context
	ApiService PersonCredentialAPI
	id string
	cUIntentSend *CUIntentSend
}

func (r PersonCredentialAPIPersonIdCredentialUpdateIntentSendPostRequest) CUIntentSend(cUIntentSend CUIntentSend) PersonCredentialAPIPersonIdCredentialUpdateIntentSendPostRequest {
	r.cUIntentSend = &cUIntentSend
	return r
}

func (r PersonCredentialAPIPersonIdCredentialUpdateIntentSendPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.PersonIdCredentialUpdateIntentSendPostExecute(r)
}

/*
PersonIdCredentialUpdateIntentSendPost Method for PersonIdCredentialUpdateIntentSendPost

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return PersonCredentialAPIPersonIdCredentialUpdateIntentSendPostRequest
*/
func (a *PersonCredentialAPIService) PersonIdCredentialUpdateIntentSendPost(ctx context.Context, id string) PersonCredentialAPIPersonIdCredentialUpdateIntentSendPostRequest {
	return PersonCredentialAPIPersonIdCredentialUpdateIntentSendPostRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *PersonCredentialAPIService) PersonIdCredentialUpdateIntentSendPostExecute(r PersonCredentialAPIPersonIdCredentialUpdateIntentSendPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonCredentialAPIService.PersonIdCredentialUpdateIntentSendPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_credential/_update_intent_send"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.cUIntentSend == nil {
		return nil, reportError("cUIntentSend is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.cUIntentSend
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type PersonCredentialAPIPersonIdCredentialUpdateIntentTtlGetRequest struct {
	ctx context.Context
	ApiService PersonCredentialAPI
	ttl int64
	id string
}

func (r PersonCredentialAPIPersonIdCredentialUpdateIntentTtlGetRequest) Execute() (*CUIntentToken, *http.Response, error) {
	return r.ApiService.PersonIdCredentialUpdateIntentTtlGetExecute(r)
}

/*
PersonIdCredentialUpdateIntentTtlGet Method for PersonIdCredentialUpdateIntentTtlGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param ttl The new TTL for the credential?
 @param id
 @return PersonCredentialAPIPersonIdCredentialUpdateIntentTtlGetRequest
*/
func (a *PersonCredentialAPIService) PersonIdCredentialUpdateIntentTtlGet(ctx context.Context, ttl int64, id string) PersonCredentialAPIPersonIdCredentialUpdateIntentTtlGetRequest {
	return PersonCredentialAPIPersonIdCredentialUpdateIntentTtlGetRequest{
		ApiService: a,
		ctx: ctx,
		ttl: ttl,
		id: id,
	}
}

// Execute executes the request
//  @return CUIntentToken
func (a *PersonCredentialAPIService) PersonIdCredentialUpdateIntentTtlGetExecute(r PersonCredentialAPIPersonIdCredentialUpdateIntentTtlGetRequest) (*CUIntentToken, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CUIntentToken
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonCredentialAPIService.PersonIdCredentialUpdateIntentTtlGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_credential/_update_intent/{ttl}"
	localVarPath = strings.Replace(localVarPath, "{"+"ttl"+"}", url.PathEscape(parameterValueToString(r.ttl, "ttl")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.ttl < 0 {
		return localVarReturnValue, nil, reportError("ttl must be greater than 0")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
