/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type GroupAttrAPI interface {

	/*
	GroupIdAttrDelete Method for GroupIdAttrDelete

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param attr
	@return GroupAttrAPIGroupIdAttrDeleteRequest
	*/
	GroupIdAttrDelete(ctx context.Context, id string, attr string) GroupAttrAPIGroupIdAttrDeleteRequest

	// GroupIdAttrDeleteExecute executes the request
	GroupIdAttrDeleteExecute(r GroupAttrAPIGroupIdAttrDeleteRequest) (*http.Response, error)

	/*
	GroupIdAttrGet Method for GroupIdAttrGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param attr
	@return GroupAttrAPIGroupIdAttrGetRequest
	*/
	GroupIdAttrGet(ctx context.Context, id string, attr string) GroupAttrAPIGroupIdAttrGetRequest

	// GroupIdAttrGetExecute executes the request
	//  @return []string
	GroupIdAttrGetExecute(r GroupAttrAPIGroupIdAttrGetRequest) ([]string, *http.Response, error)

	/*
	GroupIdAttrPost Method for GroupIdAttrPost

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param attr
	@return GroupAttrAPIGroupIdAttrPostRequest
	*/
	GroupIdAttrPost(ctx context.Context, id string, attr string) GroupAttrAPIGroupIdAttrPostRequest

	// GroupIdAttrPostExecute executes the request
	GroupIdAttrPostExecute(r GroupAttrAPIGroupIdAttrPostRequest) (*http.Response, error)

	/*
	GroupIdAttrPut Method for GroupIdAttrPut

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param attr
	@return GroupAttrAPIGroupIdAttrPutRequest
	*/
	GroupIdAttrPut(ctx context.Context, id string, attr string) GroupAttrAPIGroupIdAttrPutRequest

	// GroupIdAttrPutExecute executes the request
	GroupIdAttrPutExecute(r GroupAttrAPIGroupIdAttrPutRequest) (*http.Response, error)
}

// GroupAttrAPIService GroupAttrAPI service
type GroupAttrAPIService service

type GroupAttrAPIGroupIdAttrDeleteRequest struct {
	ctx context.Context
	ApiService GroupAttrAPI
	id string
	attr string
	requestBody *[]string
}

func (r GroupAttrAPIGroupIdAttrDeleteRequest) RequestBody(requestBody []string) GroupAttrAPIGroupIdAttrDeleteRequest {
	r.requestBody = &requestBody
	return r
}

func (r GroupAttrAPIGroupIdAttrDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.GroupIdAttrDeleteExecute(r)
}

/*
GroupIdAttrDelete Method for GroupIdAttrDelete

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param attr
 @return GroupAttrAPIGroupIdAttrDeleteRequest
*/
func (a *GroupAttrAPIService) GroupIdAttrDelete(ctx context.Context, id string, attr string) GroupAttrAPIGroupIdAttrDeleteRequest {
	return GroupAttrAPIGroupIdAttrDeleteRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		attr: attr,
	}
}

// Execute executes the request
func (a *GroupAttrAPIService) GroupIdAttrDeleteExecute(r GroupAttrAPIGroupIdAttrDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "GroupAttrAPIService.GroupIdAttrDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/group/{id}/_attr/{attr}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"attr"+"}", url.PathEscape(parameterValueToString(r.attr, "attr")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type GroupAttrAPIGroupIdAttrGetRequest struct {
	ctx context.Context
	ApiService GroupAttrAPI
	id string
	attr string
}

func (r GroupAttrAPIGroupIdAttrGetRequest) Execute() ([]string, *http.Response, error) {
	return r.ApiService.GroupIdAttrGetExecute(r)
}

/*
GroupIdAttrGet Method for GroupIdAttrGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param attr
 @return GroupAttrAPIGroupIdAttrGetRequest
*/
func (a *GroupAttrAPIService) GroupIdAttrGet(ctx context.Context, id string, attr string) GroupAttrAPIGroupIdAttrGetRequest {
	return GroupAttrAPIGroupIdAttrGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		attr: attr,
	}
}

// Execute executes the request
//  @return []string
func (a *GroupAttrAPIService) GroupIdAttrGetExecute(r GroupAttrAPIGroupIdAttrGetRequest) ([]string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "GroupAttrAPIService.GroupIdAttrGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/group/{id}/_attr/{attr}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"attr"+"}", url.PathEscape(parameterValueToString(r.attr, "attr")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type GroupAttrAPIGroupIdAttrPostRequest struct {
	ctx context.Context
	ApiService GroupAttrAPI
	id string
	attr string
	requestBody *[]string
}

func (r GroupAttrAPIGroupIdAttrPostRequest) RequestBody(requestBody []string) GroupAttrAPIGroupIdAttrPostRequest {
	r.requestBody = &requestBody
	return r
}

func (r GroupAttrAPIGroupIdAttrPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.GroupIdAttrPostExecute(r)
}

/*
GroupIdAttrPost Method for GroupIdAttrPost

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param attr
 @return GroupAttrAPIGroupIdAttrPostRequest
*/
func (a *GroupAttrAPIService) GroupIdAttrPost(ctx context.Context, id string, attr string) GroupAttrAPIGroupIdAttrPostRequest {
	return GroupAttrAPIGroupIdAttrPostRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		attr: attr,
	}
}

// Execute executes the request
func (a *GroupAttrAPIService) GroupIdAttrPostExecute(r GroupAttrAPIGroupIdAttrPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "GroupAttrAPIService.GroupIdAttrPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/group/{id}/_attr/{attr}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"attr"+"}", url.PathEscape(parameterValueToString(r.attr, "attr")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestBody == nil {
		return nil, reportError("requestBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type GroupAttrAPIGroupIdAttrPutRequest struct {
	ctx context.Context
	ApiService GroupAttrAPI
	id string
	attr string
	requestBody *[]string
}

func (r GroupAttrAPIGroupIdAttrPutRequest) RequestBody(requestBody []string) GroupAttrAPIGroupIdAttrPutRequest {
	r.requestBody = &requestBody
	return r
}

func (r GroupAttrAPIGroupIdAttrPutRequest) Execute() (*http.Response, error) {
	return r.ApiService.GroupIdAttrPutExecute(r)
}

/*
GroupIdAttrPut Method for GroupIdAttrPut

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param attr
 @return GroupAttrAPIGroupIdAttrPutRequest
*/
func (a *GroupAttrAPIService) GroupIdAttrPut(ctx context.Context, id string, attr string) GroupAttrAPIGroupIdAttrPutRequest {
	return GroupAttrAPIGroupIdAttrPutRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		attr: attr,
	}
}

// Execute executes the request
func (a *GroupAttrAPIService) GroupIdAttrPutExecute(r GroupAttrAPIGroupIdAttrPutRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "GroupAttrAPIService.GroupIdAttrPut")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/group/{id}/_attr/{attr}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"attr"+"}", url.PathEscape(parameterValueToString(r.attr, "attr")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestBody == nil {
		return nil, reportError("requestBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
