/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type UiAPI interface {

	/*
	Oauth2ImageGet This returns the image for the OAuth2 Resource Server if the user has permissions

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param rsName
	@return UiAPIOauth2ImageGetRequest
	*/
	Oauth2ImageGet(ctx context.Context, rsName string) UiAPIOauth2ImageGetRequest

	// Oauth2ImageGetExecute executes the request
	//  @return []int32
	Oauth2ImageGetExecute(r UiAPIOauth2ImageGetRequest) ([]int32, *http.Response, error)

	/*
	RobotsTxt Method for RobotsTxt

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return UiAPIRobotsTxtRequest
	*/
	RobotsTxt(ctx context.Context) UiAPIRobotsTxtRequest

	// RobotsTxtExecute executes the request
	RobotsTxtExecute(r UiAPIRobotsTxtRequest) (*http.Response, error)
}

// UiAPIService UiAPI service
type UiAPIService service

type UiAPIOauth2ImageGetRequest struct {
	ctx context.Context
	ApiService UiAPI
	rsName string
}

func (r UiAPIOauth2ImageGetRequest) Execute() ([]int32, *http.Response, error) {
	return r.ApiService.Oauth2ImageGetExecute(r)
}

/*
Oauth2ImageGet This returns the image for the OAuth2 Resource Server if the user has permissions

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param rsName
 @return UiAPIOauth2ImageGetRequest
*/
func (a *UiAPIService) Oauth2ImageGet(ctx context.Context, rsName string) UiAPIOauth2ImageGetRequest {
	return UiAPIOauth2ImageGetRequest{
		ApiService: a,
		ctx: ctx,
		rsName: rsName,
	}
}

// Execute executes the request
//  @return []int32
func (a *UiAPIService) Oauth2ImageGetExecute(r UiAPIOauth2ImageGetRequest) ([]int32, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []int32
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "UiAPIService.Oauth2ImageGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/ui/images/oauth2/{rs_name}"
	localVarPath = strings.Replace(localVarPath, "{"+"rs_name"+"}", url.PathEscape(parameterValueToString(r.rsName, "rsName")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/octet-stream"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type UiAPIRobotsTxtRequest struct {
	ctx context.Context
	ApiService UiAPI
}

func (r UiAPIRobotsTxtRequest) Execute() (*http.Response, error) {
	return r.ApiService.RobotsTxtExecute(r)
}

/*
RobotsTxt Method for RobotsTxt

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return UiAPIRobotsTxtRequest
*/
func (a *UiAPIService) RobotsTxt(ctx context.Context) UiAPIRobotsTxtRequest {
	return UiAPIRobotsTxtRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *UiAPIService) RobotsTxtExecute(r UiAPIRobotsTxtRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "UiAPIService.RobotsTxt")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/robots.txt"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
