/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type PersonAttrAPI interface {

	/*
	PersonIdDeleteAttr Method for PersonIdDeleteAttr

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param attr
	@return PersonAttrAPIPersonIdDeleteAttrRequest
	*/
	PersonIdDeleteAttr(ctx context.Context, id string, attr string) PersonAttrAPIPersonIdDeleteAttrRequest

	// PersonIdDeleteAttrExecute executes the request
	PersonIdDeleteAttrExecute(r PersonAttrAPIPersonIdDeleteAttrRequest) (*http.Response, error)

	/*
	PersonIdGetAttr Method for PersonIdGetAttr

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param attr
	@return PersonAttrAPIPersonIdGetAttrRequest
	*/
	PersonIdGetAttr(ctx context.Context, id string, attr string) PersonAttrAPIPersonIdGetAttrRequest

	// PersonIdGetAttrExecute executes the request
	//  @return []string
	PersonIdGetAttrExecute(r PersonAttrAPIPersonIdGetAttrRequest) ([]string, *http.Response, error)

	/*
	PersonIdPostAttr Method for PersonIdPostAttr

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param attr
	@return PersonAttrAPIPersonIdPostAttrRequest
	*/
	PersonIdPostAttr(ctx context.Context, id string, attr string) PersonAttrAPIPersonIdPostAttrRequest

	// PersonIdPostAttrExecute executes the request
	PersonIdPostAttrExecute(r PersonAttrAPIPersonIdPostAttrRequest) (*http.Response, error)

	/*
	PersonIdPutAttr Method for PersonIdPutAttr

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param attr
	@return PersonAttrAPIPersonIdPutAttrRequest
	*/
	PersonIdPutAttr(ctx context.Context, id string, attr string) PersonAttrAPIPersonIdPutAttrRequest

	// PersonIdPutAttrExecute executes the request
	PersonIdPutAttrExecute(r PersonAttrAPIPersonIdPutAttrRequest) (*http.Response, error)
}

// PersonAttrAPIService PersonAttrAPI service
type PersonAttrAPIService service

type PersonAttrAPIPersonIdDeleteAttrRequest struct {
	ctx context.Context
	ApiService PersonAttrAPI
	id string
	attr string
}

func (r PersonAttrAPIPersonIdDeleteAttrRequest) Execute() (*http.Response, error) {
	return r.ApiService.PersonIdDeleteAttrExecute(r)
}

/*
PersonIdDeleteAttr Method for PersonIdDeleteAttr

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param attr
 @return PersonAttrAPIPersonIdDeleteAttrRequest
*/
func (a *PersonAttrAPIService) PersonIdDeleteAttr(ctx context.Context, id string, attr string) PersonAttrAPIPersonIdDeleteAttrRequest {
	return PersonAttrAPIPersonIdDeleteAttrRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		attr: attr,
	}
}

// Execute executes the request
func (a *PersonAttrAPIService) PersonIdDeleteAttrExecute(r PersonAttrAPIPersonIdDeleteAttrRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonAttrAPIService.PersonIdDeleteAttr")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_attr/{attr}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"attr"+"}", url.PathEscape(parameterValueToString(r.attr, "attr")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type PersonAttrAPIPersonIdGetAttrRequest struct {
	ctx context.Context
	ApiService PersonAttrAPI
	id string
	attr string
}

func (r PersonAttrAPIPersonIdGetAttrRequest) Execute() ([]string, *http.Response, error) {
	return r.ApiService.PersonIdGetAttrExecute(r)
}

/*
PersonIdGetAttr Method for PersonIdGetAttr

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param attr
 @return PersonAttrAPIPersonIdGetAttrRequest
*/
func (a *PersonAttrAPIService) PersonIdGetAttr(ctx context.Context, id string, attr string) PersonAttrAPIPersonIdGetAttrRequest {
	return PersonAttrAPIPersonIdGetAttrRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		attr: attr,
	}
}

// Execute executes the request
//  @return []string
func (a *PersonAttrAPIService) PersonIdGetAttrExecute(r PersonAttrAPIPersonIdGetAttrRequest) ([]string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonAttrAPIService.PersonIdGetAttr")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_attr/{attr}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"attr"+"}", url.PathEscape(parameterValueToString(r.attr, "attr")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PersonAttrAPIPersonIdPostAttrRequest struct {
	ctx context.Context
	ApiService PersonAttrAPI
	id string
	attr string
	requestBody *[]string
}

func (r PersonAttrAPIPersonIdPostAttrRequest) RequestBody(requestBody []string) PersonAttrAPIPersonIdPostAttrRequest {
	r.requestBody = &requestBody
	return r
}

func (r PersonAttrAPIPersonIdPostAttrRequest) Execute() (*http.Response, error) {
	return r.ApiService.PersonIdPostAttrExecute(r)
}

/*
PersonIdPostAttr Method for PersonIdPostAttr

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param attr
 @return PersonAttrAPIPersonIdPostAttrRequest
*/
func (a *PersonAttrAPIService) PersonIdPostAttr(ctx context.Context, id string, attr string) PersonAttrAPIPersonIdPostAttrRequest {
	return PersonAttrAPIPersonIdPostAttrRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		attr: attr,
	}
}

// Execute executes the request
func (a *PersonAttrAPIService) PersonIdPostAttrExecute(r PersonAttrAPIPersonIdPostAttrRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonAttrAPIService.PersonIdPostAttr")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_attr/{attr}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"attr"+"}", url.PathEscape(parameterValueToString(r.attr, "attr")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestBody == nil {
		return nil, reportError("requestBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type PersonAttrAPIPersonIdPutAttrRequest struct {
	ctx context.Context
	ApiService PersonAttrAPI
	id string
	attr string
	requestBody *[]string
}

func (r PersonAttrAPIPersonIdPutAttrRequest) RequestBody(requestBody []string) PersonAttrAPIPersonIdPutAttrRequest {
	r.requestBody = &requestBody
	return r
}

func (r PersonAttrAPIPersonIdPutAttrRequest) Execute() (*http.Response, error) {
	return r.ApiService.PersonIdPutAttrExecute(r)
}

/*
PersonIdPutAttr Method for PersonIdPutAttr

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param attr
 @return PersonAttrAPIPersonIdPutAttrRequest
*/
func (a *PersonAttrAPIService) PersonIdPutAttr(ctx context.Context, id string, attr string) PersonAttrAPIPersonIdPutAttrRequest {
	return PersonAttrAPIPersonIdPutAttrRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		attr: attr,
	}
}

// Execute executes the request
func (a *PersonAttrAPIService) PersonIdPutAttrExecute(r PersonAttrAPIPersonIdPutAttrRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PersonAttrAPIService.PersonIdPutAttr")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/person/{id}/_attr/{attr}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"attr"+"}", url.PathEscape(parameterValueToString(r.attr, "attr")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestBody == nil {
		return nil, reportError("requestBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
