/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type SyncAccountAPI interface {

	/*
	SyncAccountGet Get all? the sync accounts.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return SyncAccountAPISyncAccountGetRequest
	*/
	SyncAccountGet(ctx context.Context) SyncAccountAPISyncAccountGetRequest

	// SyncAccountGetExecute executes the request
	//  @return []Entry
	SyncAccountGetExecute(r SyncAccountAPISyncAccountGetRequest) ([]Entry, *http.Response, error)

	/*
	SyncAccountIdAttrGet Method for SyncAccountIdAttrGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param attr
	@return SyncAccountAPISyncAccountIdAttrGetRequest
	*/
	SyncAccountIdAttrGet(ctx context.Context, id string, attr string) SyncAccountAPISyncAccountIdAttrGetRequest

	// SyncAccountIdAttrGetExecute executes the request
	//  @return []string
	SyncAccountIdAttrGetExecute(r SyncAccountAPISyncAccountIdAttrGetRequest) ([]string, *http.Response, error)

	/*
	SyncAccountIdAttrPut Method for SyncAccountIdAttrPut

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@param attr
	@return SyncAccountAPISyncAccountIdAttrPutRequest
	*/
	SyncAccountIdAttrPut(ctx context.Context, id string, attr string) SyncAccountAPISyncAccountIdAttrPutRequest

	// SyncAccountIdAttrPutExecute executes the request
	SyncAccountIdAttrPutExecute(r SyncAccountAPISyncAccountIdAttrPutRequest) (*http.Response, error)

	/*
	SyncAccountIdFinaliseGet Method for SyncAccountIdFinaliseGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return SyncAccountAPISyncAccountIdFinaliseGetRequest
	*/
	SyncAccountIdFinaliseGet(ctx context.Context, id string) SyncAccountAPISyncAccountIdFinaliseGetRequest

	// SyncAccountIdFinaliseGetExecute executes the request
	SyncAccountIdFinaliseGetExecute(r SyncAccountAPISyncAccountIdFinaliseGetRequest) (*http.Response, error)

	/*
	SyncAccountIdGet Get the details of a sync account

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return SyncAccountAPISyncAccountIdGetRequest
	*/
	SyncAccountIdGet(ctx context.Context, id string) SyncAccountAPISyncAccountIdGetRequest

	// SyncAccountIdGetExecute executes the request
	//  @return Entry
	SyncAccountIdGetExecute(r SyncAccountAPISyncAccountIdGetRequest) (*Entry, *http.Response, error)

	/*
	SyncAccountIdPatch Modify a sync account in-place

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return SyncAccountAPISyncAccountIdPatchRequest
	*/
	SyncAccountIdPatch(ctx context.Context, id string) SyncAccountAPISyncAccountIdPatchRequest

	// SyncAccountIdPatchExecute executes the request
	SyncAccountIdPatchExecute(r SyncAccountAPISyncAccountIdPatchRequest) (*http.Response, error)

	/*
	SyncAccountIdTerminateGet Method for SyncAccountIdTerminateGet

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return SyncAccountAPISyncAccountIdTerminateGetRequest
	*/
	SyncAccountIdTerminateGet(ctx context.Context, id string) SyncAccountAPISyncAccountIdTerminateGetRequest

	// SyncAccountIdTerminateGetExecute executes the request
	SyncAccountIdTerminateGetExecute(r SyncAccountAPISyncAccountIdTerminateGetRequest) (*http.Response, error)

	/*
	SyncAccountPost Method for SyncAccountPost

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return SyncAccountAPISyncAccountPostRequest
	*/
	SyncAccountPost(ctx context.Context) SyncAccountAPISyncAccountPostRequest

	// SyncAccountPostExecute executes the request
	SyncAccountPostExecute(r SyncAccountAPISyncAccountPostRequest) (*http.Response, error)

	/*
	SyncAccountTokenDelete Method for SyncAccountTokenDelete

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return SyncAccountAPISyncAccountTokenDeleteRequest
	*/
	SyncAccountTokenDelete(ctx context.Context, id string) SyncAccountAPISyncAccountTokenDeleteRequest

	// SyncAccountTokenDeleteExecute executes the request
	SyncAccountTokenDeleteExecute(r SyncAccountAPISyncAccountTokenDeleteRequest) (*http.Response, error)

	/*
	SyncAccountTokenPost Method for SyncAccountTokenPost

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id
	@return SyncAccountAPISyncAccountTokenPostRequest
	*/
	SyncAccountTokenPost(ctx context.Context, id string) SyncAccountAPISyncAccountTokenPostRequest

	// SyncAccountTokenPostExecute executes the request
	//  @return string
	SyncAccountTokenPostExecute(r SyncAccountAPISyncAccountTokenPostRequest) (string, *http.Response, error)
}

// SyncAccountAPIService SyncAccountAPI service
type SyncAccountAPIService service

type SyncAccountAPISyncAccountGetRequest struct {
	ctx context.Context
	ApiService SyncAccountAPI
}

func (r SyncAccountAPISyncAccountGetRequest) Execute() ([]Entry, *http.Response, error) {
	return r.ApiService.SyncAccountGetExecute(r)
}

/*
SyncAccountGet Get all? the sync accounts.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return SyncAccountAPISyncAccountGetRequest
*/
func (a *SyncAccountAPIService) SyncAccountGet(ctx context.Context) SyncAccountAPISyncAccountGetRequest {
	return SyncAccountAPISyncAccountGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []Entry
func (a *SyncAccountAPIService) SyncAccountGetExecute(r SyncAccountAPISyncAccountGetRequest) ([]Entry, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []Entry
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SyncAccountAPIService.SyncAccountGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/sync_account"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SyncAccountAPISyncAccountIdAttrGetRequest struct {
	ctx context.Context
	ApiService SyncAccountAPI
	id string
	attr string
}

func (r SyncAccountAPISyncAccountIdAttrGetRequest) Execute() ([]string, *http.Response, error) {
	return r.ApiService.SyncAccountIdAttrGetExecute(r)
}

/*
SyncAccountIdAttrGet Method for SyncAccountIdAttrGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param attr
 @return SyncAccountAPISyncAccountIdAttrGetRequest
*/
func (a *SyncAccountAPIService) SyncAccountIdAttrGet(ctx context.Context, id string, attr string) SyncAccountAPISyncAccountIdAttrGetRequest {
	return SyncAccountAPISyncAccountIdAttrGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		attr: attr,
	}
}

// Execute executes the request
//  @return []string
func (a *SyncAccountAPIService) SyncAccountIdAttrGetExecute(r SyncAccountAPISyncAccountIdAttrGetRequest) ([]string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SyncAccountAPIService.SyncAccountIdAttrGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/sync_account/{id}/_attr/{attr}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"attr"+"}", url.PathEscape(parameterValueToString(r.attr, "attr")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SyncAccountAPISyncAccountIdAttrPutRequest struct {
	ctx context.Context
	ApiService SyncAccountAPI
	id string
	attr string
	requestBody *[]string
}

func (r SyncAccountAPISyncAccountIdAttrPutRequest) RequestBody(requestBody []string) SyncAccountAPISyncAccountIdAttrPutRequest {
	r.requestBody = &requestBody
	return r
}

func (r SyncAccountAPISyncAccountIdAttrPutRequest) Execute() (*http.Response, error) {
	return r.ApiService.SyncAccountIdAttrPutExecute(r)
}

/*
SyncAccountIdAttrPut Method for SyncAccountIdAttrPut

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @param attr
 @return SyncAccountAPISyncAccountIdAttrPutRequest
*/
func (a *SyncAccountAPIService) SyncAccountIdAttrPut(ctx context.Context, id string, attr string) SyncAccountAPISyncAccountIdAttrPutRequest {
	return SyncAccountAPISyncAccountIdAttrPutRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
		attr: attr,
	}
}

// Execute executes the request
func (a *SyncAccountAPIService) SyncAccountIdAttrPutExecute(r SyncAccountAPISyncAccountIdAttrPutRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SyncAccountAPIService.SyncAccountIdAttrPut")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/sync_account/{id}/_attr/{attr}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"attr"+"}", url.PathEscape(parameterValueToString(r.attr, "attr")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestBody == nil {
		return nil, reportError("requestBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SyncAccountAPISyncAccountIdFinaliseGetRequest struct {
	ctx context.Context
	ApiService SyncAccountAPI
	id string
}

func (r SyncAccountAPISyncAccountIdFinaliseGetRequest) Execute() (*http.Response, error) {
	return r.ApiService.SyncAccountIdFinaliseGetExecute(r)
}

/*
SyncAccountIdFinaliseGet Method for SyncAccountIdFinaliseGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return SyncAccountAPISyncAccountIdFinaliseGetRequest
*/
func (a *SyncAccountAPIService) SyncAccountIdFinaliseGet(ctx context.Context, id string) SyncAccountAPISyncAccountIdFinaliseGetRequest {
	return SyncAccountAPISyncAccountIdFinaliseGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *SyncAccountAPIService) SyncAccountIdFinaliseGetExecute(r SyncAccountAPISyncAccountIdFinaliseGetRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SyncAccountAPIService.SyncAccountIdFinaliseGet")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/sync_account/{id}/_finalise"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SyncAccountAPISyncAccountIdGetRequest struct {
	ctx context.Context
	ApiService SyncAccountAPI
	id string
}

func (r SyncAccountAPISyncAccountIdGetRequest) Execute() (*Entry, *http.Response, error) {
	return r.ApiService.SyncAccountIdGetExecute(r)
}

/*
SyncAccountIdGet Get the details of a sync account

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return SyncAccountAPISyncAccountIdGetRequest
*/
func (a *SyncAccountAPIService) SyncAccountIdGet(ctx context.Context, id string) SyncAccountAPISyncAccountIdGetRequest {
	return SyncAccountAPISyncAccountIdGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return Entry
func (a *SyncAccountAPIService) SyncAccountIdGetExecute(r SyncAccountAPISyncAccountIdGetRequest) (*Entry, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *Entry
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SyncAccountAPIService.SyncAccountIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/sync_account/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SyncAccountAPISyncAccountIdPatchRequest struct {
	ctx context.Context
	ApiService SyncAccountAPI
	id string
	entry *Entry
}

func (r SyncAccountAPISyncAccountIdPatchRequest) Entry(entry Entry) SyncAccountAPISyncAccountIdPatchRequest {
	r.entry = &entry
	return r
}

func (r SyncAccountAPISyncAccountIdPatchRequest) Execute() (*http.Response, error) {
	return r.ApiService.SyncAccountIdPatchExecute(r)
}

/*
SyncAccountIdPatch Modify a sync account in-place

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return SyncAccountAPISyncAccountIdPatchRequest
*/
func (a *SyncAccountAPIService) SyncAccountIdPatch(ctx context.Context, id string) SyncAccountAPISyncAccountIdPatchRequest {
	return SyncAccountAPISyncAccountIdPatchRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *SyncAccountAPIService) SyncAccountIdPatchExecute(r SyncAccountAPISyncAccountIdPatchRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SyncAccountAPIService.SyncAccountIdPatch")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/sync_account/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.entry == nil {
		return nil, reportError("entry is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.entry
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SyncAccountAPISyncAccountIdTerminateGetRequest struct {
	ctx context.Context
	ApiService SyncAccountAPI
	id string
}

func (r SyncAccountAPISyncAccountIdTerminateGetRequest) Execute() (*http.Response, error) {
	return r.ApiService.SyncAccountIdTerminateGetExecute(r)
}

/*
SyncAccountIdTerminateGet Method for SyncAccountIdTerminateGet

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return SyncAccountAPISyncAccountIdTerminateGetRequest
*/
func (a *SyncAccountAPIService) SyncAccountIdTerminateGet(ctx context.Context, id string) SyncAccountAPISyncAccountIdTerminateGetRequest {
	return SyncAccountAPISyncAccountIdTerminateGetRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *SyncAccountAPIService) SyncAccountIdTerminateGetExecute(r SyncAccountAPISyncAccountIdTerminateGetRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SyncAccountAPIService.SyncAccountIdTerminateGet")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/sync_account/{id}/_terminate"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SyncAccountAPISyncAccountPostRequest struct {
	ctx context.Context
	ApiService SyncAccountAPI
	entry *Entry
}

func (r SyncAccountAPISyncAccountPostRequest) Entry(entry Entry) SyncAccountAPISyncAccountPostRequest {
	r.entry = &entry
	return r
}

func (r SyncAccountAPISyncAccountPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.SyncAccountPostExecute(r)
}

/*
SyncAccountPost Method for SyncAccountPost

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return SyncAccountAPISyncAccountPostRequest
*/
func (a *SyncAccountAPIService) SyncAccountPost(ctx context.Context) SyncAccountAPISyncAccountPostRequest {
	return SyncAccountAPISyncAccountPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *SyncAccountAPIService) SyncAccountPostExecute(r SyncAccountAPISyncAccountPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SyncAccountAPIService.SyncAccountPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/sync_account"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.entry == nil {
		return nil, reportError("entry is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.entry
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SyncAccountAPISyncAccountTokenDeleteRequest struct {
	ctx context.Context
	ApiService SyncAccountAPI
	id string
}

func (r SyncAccountAPISyncAccountTokenDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.SyncAccountTokenDeleteExecute(r)
}

/*
SyncAccountTokenDelete Method for SyncAccountTokenDelete

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return SyncAccountAPISyncAccountTokenDeleteRequest
*/
func (a *SyncAccountAPIService) SyncAccountTokenDelete(ctx context.Context, id string) SyncAccountAPISyncAccountTokenDeleteRequest {
	return SyncAccountAPISyncAccountTokenDeleteRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *SyncAccountAPIService) SyncAccountTokenDeleteExecute(r SyncAccountAPISyncAccountTokenDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SyncAccountAPIService.SyncAccountTokenDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/sync_account/{id}/_sync_token"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SyncAccountAPISyncAccountTokenPostRequest struct {
	ctx context.Context
	ApiService SyncAccountAPI
	id string
	body *string
}

func (r SyncAccountAPISyncAccountTokenPostRequest) Body(body string) SyncAccountAPISyncAccountTokenPostRequest {
	r.body = &body
	return r
}

func (r SyncAccountAPISyncAccountTokenPostRequest) Execute() (string, *http.Response, error) {
	return r.ApiService.SyncAccountTokenPostExecute(r)
}

/*
SyncAccountTokenPost Method for SyncAccountTokenPost

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return SyncAccountAPISyncAccountTokenPostRequest
*/
func (a *SyncAccountAPIService) SyncAccountTokenPost(ctx context.Context, id string) SyncAccountAPISyncAccountTokenPostRequest {
	return SyncAccountAPISyncAccountTokenPostRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return string
func (a *SyncAccountAPIService) SyncAccountTokenPostExecute(r SyncAccountAPISyncAccountTokenPostRequest) (string, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  string
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SyncAccountAPIService.SyncAccountTokenPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/sync_account/{id}/_sync_token"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"text/plain"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
