/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// Oauth2ClaimMapJoin the model 'Oauth2ClaimMapJoin'
type Oauth2ClaimMapJoin string

// List of Oauth2ClaimMapJoin
const (
	CSV Oauth2ClaimMapJoin = "csv"
	SSV Oauth2ClaimMapJoin = "ssv"
	ARRAY Oauth2ClaimMapJoin = "array"
)

// All allowed values of Oauth2ClaimMapJoin enum
var AllowedOauth2ClaimMapJoinEnumValues = []Oauth2ClaimMapJoin{
	"csv",
	"ssv",
	"array",
}

func (v *Oauth2ClaimMapJoin) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Oauth2ClaimMapJoin(value)
	for _, existing := range AllowedOauth2ClaimMapJoinEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Oauth2ClaimMapJoin", value)
}

// NewOauth2ClaimMapJoinFromValue returns a pointer to a valid Oauth2ClaimMapJoin
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOauth2ClaimMapJoinFromValue(v string) (*Oauth2ClaimMapJoin, error) {
	ev := Oauth2ClaimMapJoin(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Oauth2ClaimMapJoin: valid values are %v", v, AllowedOauth2ClaimMapJoinEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Oauth2ClaimMapJoin) IsValid() bool {
	for _, existing := range AllowedOauth2ClaimMapJoinEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Oauth2ClaimMapJoin value
func (v Oauth2ClaimMapJoin) Ptr() *Oauth2ClaimMapJoin {
	return &v
}

type NullableOauth2ClaimMapJoin struct {
	value *Oauth2ClaimMapJoin
	isSet bool
}

func (v NullableOauth2ClaimMapJoin) Get() *Oauth2ClaimMapJoin {
	return v.value
}

func (v *NullableOauth2ClaimMapJoin) Set(val *Oauth2ClaimMapJoin) {
	v.value = val
	v.isSet = true
}

func (v NullableOauth2ClaimMapJoin) IsSet() bool {
	return v.isSet
}

func (v *NullableOauth2ClaimMapJoin) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOauth2ClaimMapJoin(val *Oauth2ClaimMapJoin) *NullableOauth2ClaimMapJoin {
	return &NullableOauth2ClaimMapJoin{value: val, isSet: true}
}

func (v NullableOauth2ClaimMapJoin) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOauth2ClaimMapJoin) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

