/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConsistencyErrorOneOf4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsistencyErrorOneOf4{}

// ConsistencyErrorOneOf4 struct for ConsistencyErrorOneOf4
type ConsistencyErrorOneOf4 struct {
	Uuidindexcorrupt string `json:"uuidindexcorrupt"`
}

type _ConsistencyErrorOneOf4 ConsistencyErrorOneOf4

// NewConsistencyErrorOneOf4 instantiates a new ConsistencyErrorOneOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsistencyErrorOneOf4(uuidindexcorrupt string) *ConsistencyErrorOneOf4 {
	this := ConsistencyErrorOneOf4{}
	this.Uuidindexcorrupt = uuidindexcorrupt
	return &this
}

// NewConsistencyErrorOneOf4WithDefaults instantiates a new ConsistencyErrorOneOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsistencyErrorOneOf4WithDefaults() *ConsistencyErrorOneOf4 {
	this := ConsistencyErrorOneOf4{}
	return &this
}

// GetUuidindexcorrupt returns the Uuidindexcorrupt field value
func (o *ConsistencyErrorOneOf4) GetUuidindexcorrupt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuidindexcorrupt
}

// GetUuidindexcorruptOk returns a tuple with the Uuidindexcorrupt field value
// and a boolean to check if the value has been set.
func (o *ConsistencyErrorOneOf4) GetUuidindexcorruptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuidindexcorrupt, true
}

// SetUuidindexcorrupt sets field value
func (o *ConsistencyErrorOneOf4) SetUuidindexcorrupt(v string) {
	o.Uuidindexcorrupt = v
}

func (o ConsistencyErrorOneOf4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsistencyErrorOneOf4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuidindexcorrupt"] = o.Uuidindexcorrupt
	return toSerialize, nil
}

func (o *ConsistencyErrorOneOf4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuidindexcorrupt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsistencyErrorOneOf4 := _ConsistencyErrorOneOf4{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsistencyErrorOneOf4)

	if err != nil {
		return err
	}

	*o = ConsistencyErrorOneOf4(varConsistencyErrorOneOf4)

	return err
}

type NullableConsistencyErrorOneOf4 struct {
	value *ConsistencyErrorOneOf4
	isSet bool
}

func (v NullableConsistencyErrorOneOf4) Get() *ConsistencyErrorOneOf4 {
	return v.value
}

func (v *NullableConsistencyErrorOneOf4) Set(val *ConsistencyErrorOneOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableConsistencyErrorOneOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableConsistencyErrorOneOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsistencyErrorOneOf4(val *ConsistencyErrorOneOf4) *NullableConsistencyErrorOneOf4 {
	return &NullableConsistencyErrorOneOf4{value: val, isSet: true}
}

func (v NullableConsistencyErrorOneOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsistencyErrorOneOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


