/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ScimSyncRetentionMode - struct for ScimSyncRetentionMode
type ScimSyncRetentionMode struct {
	ScimSyncRetentionModeOneOf *ScimSyncRetentionModeOneOf
	ScimSyncRetentionModeOneOf1 *ScimSyncRetentionModeOneOf1
	String *string
}

// ScimSyncRetentionModeOneOfAsScimSyncRetentionMode is a convenience function that returns ScimSyncRetentionModeOneOf wrapped in ScimSyncRetentionMode
func ScimSyncRetentionModeOneOfAsScimSyncRetentionMode(v *ScimSyncRetentionModeOneOf) ScimSyncRetentionMode {
	return ScimSyncRetentionMode{
		ScimSyncRetentionModeOneOf: v,
	}
}

// ScimSyncRetentionModeOneOf1AsScimSyncRetentionMode is a convenience function that returns ScimSyncRetentionModeOneOf1 wrapped in ScimSyncRetentionMode
func ScimSyncRetentionModeOneOf1AsScimSyncRetentionMode(v *ScimSyncRetentionModeOneOf1) ScimSyncRetentionMode {
	return ScimSyncRetentionMode{
		ScimSyncRetentionModeOneOf1: v,
	}
}

// stringAsScimSyncRetentionMode is a convenience function that returns string wrapped in ScimSyncRetentionMode
func StringAsScimSyncRetentionMode(v *string) ScimSyncRetentionMode {
	return ScimSyncRetentionMode{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ScimSyncRetentionMode) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ScimSyncRetentionModeOneOf
	err = newStrictDecoder(data).Decode(&dst.ScimSyncRetentionModeOneOf)
	if err == nil {
		jsonScimSyncRetentionModeOneOf, _ := json.Marshal(dst.ScimSyncRetentionModeOneOf)
		if string(jsonScimSyncRetentionModeOneOf) == "{}" { // empty struct
			dst.ScimSyncRetentionModeOneOf = nil
		} else {
			if err = validator.Validate(dst.ScimSyncRetentionModeOneOf); err != nil {
				dst.ScimSyncRetentionModeOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ScimSyncRetentionModeOneOf = nil
	}

	// try to unmarshal data into ScimSyncRetentionModeOneOf1
	err = newStrictDecoder(data).Decode(&dst.ScimSyncRetentionModeOneOf1)
	if err == nil {
		jsonScimSyncRetentionModeOneOf1, _ := json.Marshal(dst.ScimSyncRetentionModeOneOf1)
		if string(jsonScimSyncRetentionModeOneOf1) == "{}" { // empty struct
			dst.ScimSyncRetentionModeOneOf1 = nil
		} else {
			if err = validator.Validate(dst.ScimSyncRetentionModeOneOf1); err != nil {
				dst.ScimSyncRetentionModeOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.ScimSyncRetentionModeOneOf1 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ScimSyncRetentionModeOneOf = nil
		dst.ScimSyncRetentionModeOneOf1 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ScimSyncRetentionMode)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ScimSyncRetentionMode)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ScimSyncRetentionMode) MarshalJSON() ([]byte, error) {
	if src.ScimSyncRetentionModeOneOf != nil {
		return json.Marshal(&src.ScimSyncRetentionModeOneOf)
	}

	if src.ScimSyncRetentionModeOneOf1 != nil {
		return json.Marshal(&src.ScimSyncRetentionModeOneOf1)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ScimSyncRetentionMode) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ScimSyncRetentionModeOneOf != nil {
		return obj.ScimSyncRetentionModeOneOf
	}

	if obj.ScimSyncRetentionModeOneOf1 != nil {
		return obj.ScimSyncRetentionModeOneOf1
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ScimSyncRetentionMode) GetActualInstanceValue() (interface{}) {
	if obj.ScimSyncRetentionModeOneOf != nil {
		return *obj.ScimSyncRetentionModeOneOf
	}

	if obj.ScimSyncRetentionModeOneOf1 != nil {
		return *obj.ScimSyncRetentionModeOneOf1
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableScimSyncRetentionMode struct {
	value *ScimSyncRetentionMode
	isSet bool
}

func (v NullableScimSyncRetentionMode) Get() *ScimSyncRetentionMode {
	return v.value
}

func (v *NullableScimSyncRetentionMode) Set(val *ScimSyncRetentionMode) {
	v.value = val
	v.isSet = true
}

func (v NullableScimSyncRetentionMode) IsSet() bool {
	return v.isSet
}

func (v *NullableScimSyncRetentionMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimSyncRetentionMode(val *ScimSyncRetentionMode) *NullableScimSyncRetentionMode {
	return &NullableScimSyncRetentionMode{value: val, isSet: true}
}

func (v NullableScimSyncRetentionMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimSyncRetentionMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


