/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConsistencyErrorOneOf13 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsistencyErrorOneOf13{}

// ConsistencyErrorOneOf13 struct for ConsistencyErrorOneOf13
type ConsistencyErrorOneOf13 struct {
	Deniedname string `json:"deniedname"`
}

type _ConsistencyErrorOneOf13 ConsistencyErrorOneOf13

// NewConsistencyErrorOneOf13 instantiates a new ConsistencyErrorOneOf13 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsistencyErrorOneOf13(deniedname string) *ConsistencyErrorOneOf13 {
	this := ConsistencyErrorOneOf13{}
	this.Deniedname = deniedname
	return &this
}

// NewConsistencyErrorOneOf13WithDefaults instantiates a new ConsistencyErrorOneOf13 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsistencyErrorOneOf13WithDefaults() *ConsistencyErrorOneOf13 {
	this := ConsistencyErrorOneOf13{}
	return &this
}

// GetDeniedname returns the Deniedname field value
func (o *ConsistencyErrorOneOf13) GetDeniedname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Deniedname
}

// GetDeniednameOk returns a tuple with the Deniedname field value
// and a boolean to check if the value has been set.
func (o *ConsistencyErrorOneOf13) GetDeniednameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deniedname, true
}

// SetDeniedname sets field value
func (o *ConsistencyErrorOneOf13) SetDeniedname(v string) {
	o.Deniedname = v
}

func (o ConsistencyErrorOneOf13) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsistencyErrorOneOf13) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deniedname"] = o.Deniedname
	return toSerialize, nil
}

func (o *ConsistencyErrorOneOf13) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deniedname",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsistencyErrorOneOf13 := _ConsistencyErrorOneOf13{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsistencyErrorOneOf13)

	if err != nil {
		return err
	}

	*o = ConsistencyErrorOneOf13(varConsistencyErrorOneOf13)

	return err
}

type NullableConsistencyErrorOneOf13 struct {
	value *ConsistencyErrorOneOf13
	isSet bool
}

func (v NullableConsistencyErrorOneOf13) Get() *ConsistencyErrorOneOf13 {
	return v.value
}

func (v *NullableConsistencyErrorOneOf13) Set(val *ConsistencyErrorOneOf13) {
	v.value = val
	v.isSet = true
}

func (v NullableConsistencyErrorOneOf13) IsSet() bool {
	return v.isSet
}

func (v *NullableConsistencyErrorOneOf13) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsistencyErrorOneOf13(val *ConsistencyErrorOneOf13) *NullableConsistencyErrorOneOf13 {
	return &NullableConsistencyErrorOneOf13{value: val, isSet: true}
}

func (v NullableConsistencyErrorOneOf13) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsistencyErrorOneOf13) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


