/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ScimSyncRetentionModeOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimSyncRetentionModeOneOf{}

// ScimSyncRetentionModeOneOf All entries that have their uuid present in this set are retained. Anything not present will be deleted.
type ScimSyncRetentionModeOneOf struct {
	// All entries that have their uuid present in this set are retained. Anything not present will be deleted.
	Retain []string `json:"Retain"`
}

type _ScimSyncRetentionModeOneOf ScimSyncRetentionModeOneOf

// NewScimSyncRetentionModeOneOf instantiates a new ScimSyncRetentionModeOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimSyncRetentionModeOneOf(retain []string) *ScimSyncRetentionModeOneOf {
	this := ScimSyncRetentionModeOneOf{}
	this.Retain = retain
	return &this
}

// NewScimSyncRetentionModeOneOfWithDefaults instantiates a new ScimSyncRetentionModeOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimSyncRetentionModeOneOfWithDefaults() *ScimSyncRetentionModeOneOf {
	this := ScimSyncRetentionModeOneOf{}
	return &this
}

// GetRetain returns the Retain field value
func (o *ScimSyncRetentionModeOneOf) GetRetain() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Retain
}

// GetRetainOk returns a tuple with the Retain field value
// and a boolean to check if the value has been set.
func (o *ScimSyncRetentionModeOneOf) GetRetainOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Retain, true
}

// SetRetain sets field value
func (o *ScimSyncRetentionModeOneOf) SetRetain(v []string) {
	o.Retain = v
}

func (o ScimSyncRetentionModeOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimSyncRetentionModeOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Retain"] = o.Retain
	return toSerialize, nil
}

func (o *ScimSyncRetentionModeOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Retain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScimSyncRetentionModeOneOf := _ScimSyncRetentionModeOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScimSyncRetentionModeOneOf)

	if err != nil {
		return err
	}

	*o = ScimSyncRetentionModeOneOf(varScimSyncRetentionModeOneOf)

	return err
}

type NullableScimSyncRetentionModeOneOf struct {
	value *ScimSyncRetentionModeOneOf
	isSet bool
}

func (v NullableScimSyncRetentionModeOneOf) Get() *ScimSyncRetentionModeOneOf {
	return v.value
}

func (v *NullableScimSyncRetentionModeOneOf) Set(val *ScimSyncRetentionModeOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableScimSyncRetentionModeOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableScimSyncRetentionModeOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimSyncRetentionModeOneOf(val *ScimSyncRetentionModeOneOf) *NullableScimSyncRetentionModeOneOf {
	return &NullableScimSyncRetentionModeOneOf{value: val, isSet: true}
}

func (v NullableScimSyncRetentionModeOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimSyncRetentionModeOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


