/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CUStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CUStatus{}

// CUStatus struct for CUStatus
type CUStatus struct {
	Spn string `json:"spn"`
	Displayname string `json:"displayname"`
	ExtCredPortal CUExtPortal `json:"ext_cred_portal"`
	Mfaregstate CURegState `json:"mfaregstate"`
	CanCommit bool `json:"can_commit"`
	Warnings []CURegWarning `json:"warnings"`
	Primary NullableCredentialDetail `json:"primary,omitempty"`
	PrimaryState CUCredState `json:"primary_state"`
	Passkeys []PasskeyDetail `json:"passkeys"`
	PasskeysState CUCredState `json:"passkeys_state"`
	AttestedPasskeys []PasskeyDetail `json:"attested_passkeys"`
	AttestedPasskeysState CUCredState `json:"attested_passkeys_state"`
	AttestedPasskeysAllowedDevices []string `json:"attested_passkeys_allowed_devices"`
	Unixcred NullableCredentialDetail `json:"unixcred,omitempty"`
	UnixcredState CUCredState `json:"unixcred_state"`
	Sshkeys map[string]interface{} `json:"sshkeys"`
	SshkeysState CUCredState `json:"sshkeys_state"`
}

type _CUStatus CUStatus

// NewCUStatus instantiates a new CUStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCUStatus(spn string, displayname string, extCredPortal CUExtPortal, mfaregstate CURegState, canCommit bool, warnings []CURegWarning, primaryState CUCredState, passkeys []PasskeyDetail, passkeysState CUCredState, attestedPasskeys []PasskeyDetail, attestedPasskeysState CUCredState, attestedPasskeysAllowedDevices []string, unixcredState CUCredState, sshkeys map[string]interface{}, sshkeysState CUCredState) *CUStatus {
	this := CUStatus{}
	this.Spn = spn
	this.Displayname = displayname
	this.ExtCredPortal = extCredPortal
	this.Mfaregstate = mfaregstate
	this.CanCommit = canCommit
	this.Warnings = warnings
	this.PrimaryState = primaryState
	this.Passkeys = passkeys
	this.PasskeysState = passkeysState
	this.AttestedPasskeys = attestedPasskeys
	this.AttestedPasskeysState = attestedPasskeysState
	this.AttestedPasskeysAllowedDevices = attestedPasskeysAllowedDevices
	this.UnixcredState = unixcredState
	this.Sshkeys = sshkeys
	this.SshkeysState = sshkeysState
	return &this
}

// NewCUStatusWithDefaults instantiates a new CUStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCUStatusWithDefaults() *CUStatus {
	this := CUStatus{}
	return &this
}

// GetSpn returns the Spn field value
func (o *CUStatus) GetSpn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Spn
}

// GetSpnOk returns a tuple with the Spn field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetSpnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spn, true
}

// SetSpn sets field value
func (o *CUStatus) SetSpn(v string) {
	o.Spn = v
}

// GetDisplayname returns the Displayname field value
func (o *CUStatus) GetDisplayname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Displayname
}

// GetDisplaynameOk returns a tuple with the Displayname field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetDisplaynameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Displayname, true
}

// SetDisplayname sets field value
func (o *CUStatus) SetDisplayname(v string) {
	o.Displayname = v
}

// GetExtCredPortal returns the ExtCredPortal field value
func (o *CUStatus) GetExtCredPortal() CUExtPortal {
	if o == nil {
		var ret CUExtPortal
		return ret
	}

	return o.ExtCredPortal
}

// GetExtCredPortalOk returns a tuple with the ExtCredPortal field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetExtCredPortalOk() (*CUExtPortal, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExtCredPortal, true
}

// SetExtCredPortal sets field value
func (o *CUStatus) SetExtCredPortal(v CUExtPortal) {
	o.ExtCredPortal = v
}

// GetMfaregstate returns the Mfaregstate field value
func (o *CUStatus) GetMfaregstate() CURegState {
	if o == nil {
		var ret CURegState
		return ret
	}

	return o.Mfaregstate
}

// GetMfaregstateOk returns a tuple with the Mfaregstate field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetMfaregstateOk() (*CURegState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mfaregstate, true
}

// SetMfaregstate sets field value
func (o *CUStatus) SetMfaregstate(v CURegState) {
	o.Mfaregstate = v
}

// GetCanCommit returns the CanCommit field value
func (o *CUStatus) GetCanCommit() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CanCommit
}

// GetCanCommitOk returns a tuple with the CanCommit field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetCanCommitOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanCommit, true
}

// SetCanCommit sets field value
func (o *CUStatus) SetCanCommit(v bool) {
	o.CanCommit = v
}

// GetWarnings returns the Warnings field value
func (o *CUStatus) GetWarnings() []CURegWarning {
	if o == nil {
		var ret []CURegWarning
		return ret
	}

	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetWarningsOk() ([]CURegWarning, bool) {
	if o == nil {
		return nil, false
	}
	return o.Warnings, true
}

// SetWarnings sets field value
func (o *CUStatus) SetWarnings(v []CURegWarning) {
	o.Warnings = v
}

// GetPrimary returns the Primary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CUStatus) GetPrimary() CredentialDetail {
	if o == nil || IsNil(o.Primary.Get()) {
		var ret CredentialDetail
		return ret
	}
	return *o.Primary.Get()
}

// GetPrimaryOk returns a tuple with the Primary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CUStatus) GetPrimaryOk() (*CredentialDetail, bool) {
	if o == nil {
		return nil, false
	}
	return o.Primary.Get(), o.Primary.IsSet()
}

// HasPrimary returns a boolean if a field has been set.
func (o *CUStatus) HasPrimary() bool {
	if o != nil && o.Primary.IsSet() {
		return true
	}

	return false
}

// SetPrimary gets a reference to the given NullableCredentialDetail and assigns it to the Primary field.
func (o *CUStatus) SetPrimary(v CredentialDetail) {
	o.Primary.Set(&v)
}
// SetPrimaryNil sets the value for Primary to be an explicit nil
func (o *CUStatus) SetPrimaryNil() {
	o.Primary.Set(nil)
}

// UnsetPrimary ensures that no value is present for Primary, not even an explicit nil
func (o *CUStatus) UnsetPrimary() {
	o.Primary.Unset()
}

// GetPrimaryState returns the PrimaryState field value
func (o *CUStatus) GetPrimaryState() CUCredState {
	if o == nil {
		var ret CUCredState
		return ret
	}

	return o.PrimaryState
}

// GetPrimaryStateOk returns a tuple with the PrimaryState field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetPrimaryStateOk() (*CUCredState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrimaryState, true
}

// SetPrimaryState sets field value
func (o *CUStatus) SetPrimaryState(v CUCredState) {
	o.PrimaryState = v
}

// GetPasskeys returns the Passkeys field value
func (o *CUStatus) GetPasskeys() []PasskeyDetail {
	if o == nil {
		var ret []PasskeyDetail
		return ret
	}

	return o.Passkeys
}

// GetPasskeysOk returns a tuple with the Passkeys field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetPasskeysOk() ([]PasskeyDetail, bool) {
	if o == nil {
		return nil, false
	}
	return o.Passkeys, true
}

// SetPasskeys sets field value
func (o *CUStatus) SetPasskeys(v []PasskeyDetail) {
	o.Passkeys = v
}

// GetPasskeysState returns the PasskeysState field value
func (o *CUStatus) GetPasskeysState() CUCredState {
	if o == nil {
		var ret CUCredState
		return ret
	}

	return o.PasskeysState
}

// GetPasskeysStateOk returns a tuple with the PasskeysState field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetPasskeysStateOk() (*CUCredState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PasskeysState, true
}

// SetPasskeysState sets field value
func (o *CUStatus) SetPasskeysState(v CUCredState) {
	o.PasskeysState = v
}

// GetAttestedPasskeys returns the AttestedPasskeys field value
func (o *CUStatus) GetAttestedPasskeys() []PasskeyDetail {
	if o == nil {
		var ret []PasskeyDetail
		return ret
	}

	return o.AttestedPasskeys
}

// GetAttestedPasskeysOk returns a tuple with the AttestedPasskeys field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetAttestedPasskeysOk() ([]PasskeyDetail, bool) {
	if o == nil {
		return nil, false
	}
	return o.AttestedPasskeys, true
}

// SetAttestedPasskeys sets field value
func (o *CUStatus) SetAttestedPasskeys(v []PasskeyDetail) {
	o.AttestedPasskeys = v
}

// GetAttestedPasskeysState returns the AttestedPasskeysState field value
func (o *CUStatus) GetAttestedPasskeysState() CUCredState {
	if o == nil {
		var ret CUCredState
		return ret
	}

	return o.AttestedPasskeysState
}

// GetAttestedPasskeysStateOk returns a tuple with the AttestedPasskeysState field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetAttestedPasskeysStateOk() (*CUCredState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttestedPasskeysState, true
}

// SetAttestedPasskeysState sets field value
func (o *CUStatus) SetAttestedPasskeysState(v CUCredState) {
	o.AttestedPasskeysState = v
}

// GetAttestedPasskeysAllowedDevices returns the AttestedPasskeysAllowedDevices field value
func (o *CUStatus) GetAttestedPasskeysAllowedDevices() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.AttestedPasskeysAllowedDevices
}

// GetAttestedPasskeysAllowedDevicesOk returns a tuple with the AttestedPasskeysAllowedDevices field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetAttestedPasskeysAllowedDevicesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AttestedPasskeysAllowedDevices, true
}

// SetAttestedPasskeysAllowedDevices sets field value
func (o *CUStatus) SetAttestedPasskeysAllowedDevices(v []string) {
	o.AttestedPasskeysAllowedDevices = v
}

// GetUnixcred returns the Unixcred field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CUStatus) GetUnixcred() CredentialDetail {
	if o == nil || IsNil(o.Unixcred.Get()) {
		var ret CredentialDetail
		return ret
	}
	return *o.Unixcred.Get()
}

// GetUnixcredOk returns a tuple with the Unixcred field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CUStatus) GetUnixcredOk() (*CredentialDetail, bool) {
	if o == nil {
		return nil, false
	}
	return o.Unixcred.Get(), o.Unixcred.IsSet()
}

// HasUnixcred returns a boolean if a field has been set.
func (o *CUStatus) HasUnixcred() bool {
	if o != nil && o.Unixcred.IsSet() {
		return true
	}

	return false
}

// SetUnixcred gets a reference to the given NullableCredentialDetail and assigns it to the Unixcred field.
func (o *CUStatus) SetUnixcred(v CredentialDetail) {
	o.Unixcred.Set(&v)
}
// SetUnixcredNil sets the value for Unixcred to be an explicit nil
func (o *CUStatus) SetUnixcredNil() {
	o.Unixcred.Set(nil)
}

// UnsetUnixcred ensures that no value is present for Unixcred, not even an explicit nil
func (o *CUStatus) UnsetUnixcred() {
	o.Unixcred.Unset()
}

// GetUnixcredState returns the UnixcredState field value
func (o *CUStatus) GetUnixcredState() CUCredState {
	if o == nil {
		var ret CUCredState
		return ret
	}

	return o.UnixcredState
}

// GetUnixcredStateOk returns a tuple with the UnixcredState field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetUnixcredStateOk() (*CUCredState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnixcredState, true
}

// SetUnixcredState sets field value
func (o *CUStatus) SetUnixcredState(v CUCredState) {
	o.UnixcredState = v
}

// GetSshkeys returns the Sshkeys field value
func (o *CUStatus) GetSshkeys() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Sshkeys
}

// GetSshkeysOk returns a tuple with the Sshkeys field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetSshkeysOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Sshkeys, true
}

// SetSshkeys sets field value
func (o *CUStatus) SetSshkeys(v map[string]interface{}) {
	o.Sshkeys = v
}

// GetSshkeysState returns the SshkeysState field value
func (o *CUStatus) GetSshkeysState() CUCredState {
	if o == nil {
		var ret CUCredState
		return ret
	}

	return o.SshkeysState
}

// GetSshkeysStateOk returns a tuple with the SshkeysState field value
// and a boolean to check if the value has been set.
func (o *CUStatus) GetSshkeysStateOk() (*CUCredState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SshkeysState, true
}

// SetSshkeysState sets field value
func (o *CUStatus) SetSshkeysState(v CUCredState) {
	o.SshkeysState = v
}

func (o CUStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CUStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["spn"] = o.Spn
	toSerialize["displayname"] = o.Displayname
	toSerialize["ext_cred_portal"] = o.ExtCredPortal
	toSerialize["mfaregstate"] = o.Mfaregstate
	toSerialize["can_commit"] = o.CanCommit
	toSerialize["warnings"] = o.Warnings
	if o.Primary.IsSet() {
		toSerialize["primary"] = o.Primary.Get()
	}
	toSerialize["primary_state"] = o.PrimaryState
	toSerialize["passkeys"] = o.Passkeys
	toSerialize["passkeys_state"] = o.PasskeysState
	toSerialize["attested_passkeys"] = o.AttestedPasskeys
	toSerialize["attested_passkeys_state"] = o.AttestedPasskeysState
	toSerialize["attested_passkeys_allowed_devices"] = o.AttestedPasskeysAllowedDevices
	if o.Unixcred.IsSet() {
		toSerialize["unixcred"] = o.Unixcred.Get()
	}
	toSerialize["unixcred_state"] = o.UnixcredState
	toSerialize["sshkeys"] = o.Sshkeys
	toSerialize["sshkeys_state"] = o.SshkeysState
	return toSerialize, nil
}

func (o *CUStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"spn",
		"displayname",
		"ext_cred_portal",
		"mfaregstate",
		"can_commit",
		"warnings",
		"primary_state",
		"passkeys",
		"passkeys_state",
		"attested_passkeys",
		"attested_passkeys_state",
		"attested_passkeys_allowed_devices",
		"unixcred_state",
		"sshkeys",
		"sshkeys_state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCUStatus := _CUStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCUStatus)

	if err != nil {
		return err
	}

	*o = CUStatus(varCUStatus)

	return err
}

type NullableCUStatus struct {
	value *CUStatus
	isSet bool
}

func (v NullableCUStatus) Get() *CUStatus {
	return v.value
}

func (v *NullableCUStatus) Set(val *CUStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableCUStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableCUStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCUStatus(val *CUStatus) *NullableCUStatus {
	return &NullableCUStatus{value: val, isSet: true}
}

func (v NullableCUStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCUStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


