/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateRequest{}

// CreateRequest struct for CreateRequest
type CreateRequest struct {
	Entries []Entry `json:"entries"`
}

type _CreateRequest CreateRequest

// NewCreateRequest instantiates a new CreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateRequest(entries []Entry) *CreateRequest {
	this := CreateRequest{}
	this.Entries = entries
	return &this
}

// NewCreateRequestWithDefaults instantiates a new CreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateRequestWithDefaults() *CreateRequest {
	this := CreateRequest{}
	return &this
}

// GetEntries returns the Entries field value
func (o *CreateRequest) GetEntries() []Entry {
	if o == nil {
		var ret []Entry
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *CreateRequest) GetEntriesOk() ([]Entry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *CreateRequest) SetEntries(v []Entry) {
	o.Entries = v
}

func (o CreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

func (o *CreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateRequest := _CreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateRequest)

	if err != nil {
		return err
	}

	*o = CreateRequest(varCreateRequest)

	return err
}

type NullableCreateRequest struct {
	value *CreateRequest
	isSet bool
}

func (v NullableCreateRequest) Get() *CreateRequest {
	return v.value
}

func (v *NullableCreateRequest) Set(val *CreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateRequest(val *CreateRequest) *NullableCreateRequest {
	return &NullableCreateRequest{value: val, isSet: true}
}

func (v NullableCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


