/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
	"fmt"
	"gopkg.in/validator.v2"
)

// BTreeMapValue - struct for BTreeMapValue
type BTreeMapValue struct {
	Bool *bool
	Float64 *float64
	Int64 *int64
	String *string
	TimeTime *time.Time
}

// boolAsBTreeMapValue is a convenience function that returns bool wrapped in BTreeMapValue
func BoolAsBTreeMapValue(v *bool) BTreeMapValue {
	return BTreeMapValue{
		Bool: v,
	}
}

// float64AsBTreeMapValue is a convenience function that returns float64 wrapped in BTreeMapValue
func Float64AsBTreeMapValue(v *float64) BTreeMapValue {
	return BTreeMapValue{
		Float64: v,
	}
}

// int64AsBTreeMapValue is a convenience function that returns int64 wrapped in BTreeMapValue
func Int64AsBTreeMapValue(v *int64) BTreeMapValue {
	return BTreeMapValue{
		Int64: v,
	}
}

// stringAsBTreeMapValue is a convenience function that returns string wrapped in BTreeMapValue
func StringAsBTreeMapValue(v *string) BTreeMapValue {
	return BTreeMapValue{
		String: v,
	}
}

// time.TimeAsBTreeMapValue is a convenience function that returns time.Time wrapped in BTreeMapValue
func TimeTimeAsBTreeMapValue(v *time.Time) BTreeMapValue {
	return BTreeMapValue{
		TimeTime: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *BTreeMapValue) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			if err = validator.Validate(dst.Bool); err != nil {
				dst.Bool = nil
			} else {
				match++
			}
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal data into Float64
	err = newStrictDecoder(data).Decode(&dst.Float64)
	if err == nil {
		jsonFloat64, _ := json.Marshal(dst.Float64)
		if string(jsonFloat64) == "{}" { // empty struct
			dst.Float64 = nil
		} else {
			if err = validator.Validate(dst.Float64); err != nil {
				dst.Float64 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Float64 = nil
	}

	// try to unmarshal data into Int64
	err = newStrictDecoder(data).Decode(&dst.Int64)
	if err == nil {
		jsonInt64, _ := json.Marshal(dst.Int64)
		if string(jsonInt64) == "{}" { // empty struct
			dst.Int64 = nil
		} else {
			if err = validator.Validate(dst.Int64); err != nil {
				dst.Int64 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int64 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	// try to unmarshal data into TimeTime
	err = newStrictDecoder(data).Decode(&dst.TimeTime)
	if err == nil {
		jsonTimeTime, _ := json.Marshal(dst.TimeTime)
		if string(jsonTimeTime) == "{}" { // empty struct
			dst.TimeTime = nil
		} else {
			if err = validator.Validate(dst.TimeTime); err != nil {
				dst.TimeTime = nil
			} else {
				match++
			}
		}
	} else {
		dst.TimeTime = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Bool = nil
		dst.Float64 = nil
		dst.Int64 = nil
		dst.String = nil
		dst.TimeTime = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BTreeMapValue)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(BTreeMapValue)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BTreeMapValue) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.Float64 != nil {
		return json.Marshal(&src.Float64)
	}

	if src.Int64 != nil {
		return json.Marshal(&src.Int64)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	if src.TimeTime != nil {
		return json.Marshal(&src.TimeTime)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BTreeMapValue) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Bool != nil {
		return obj.Bool
	}

	if obj.Float64 != nil {
		return obj.Float64
	}

	if obj.Int64 != nil {
		return obj.Int64
	}

	if obj.String != nil {
		return obj.String
	}

	if obj.TimeTime != nil {
		return obj.TimeTime
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BTreeMapValue) GetActualInstanceValue() (interface{}) {
	if obj.Bool != nil {
		return *obj.Bool
	}

	if obj.Float64 != nil {
		return *obj.Float64
	}

	if obj.Int64 != nil {
		return *obj.Int64
	}

	if obj.String != nil {
		return *obj.String
	}

	if obj.TimeTime != nil {
		return *obj.TimeTime
	}

	// all schemas are nil
	return nil
}

type NullableBTreeMapValue struct {
	value *BTreeMapValue
	isSet bool
}

func (v NullableBTreeMapValue) Get() *BTreeMapValue {
	return v.value
}

func (v *NullableBTreeMapValue) Set(val *BTreeMapValue) {
	v.value = val
	v.isSet = true
}

func (v NullableBTreeMapValue) IsSet() bool {
	return v.isSet
}

func (v *NullableBTreeMapValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBTreeMapValue(val *BTreeMapValue) *NullableBTreeMapValue {
	return &NullableBTreeMapValue{value: val, isSet: true}
}

func (v NullableBTreeMapValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBTreeMapValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


