/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// ApiTokenPurpose the model 'ApiTokenPurpose'
type ApiTokenPurpose string

// List of ApiTokenPurpose
const (
	SAT_READONLY    ApiTokenPurpose = "readonly"
	SAT_READWRITE   ApiTokenPurpose = "readwrite"
	SAT_SYNCHRONISE ApiTokenPurpose = "synchronise"
)

// All allowed values of ApiTokenPurpose enum
var AllowedApiTokenPurposeEnumValues = []ApiTokenPurpose{
	"readonly",
	"readwrite",
	"synchronise",
}

func (v *ApiTokenPurpose) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ApiTokenPurpose(value)
	for _, existing := range AllowedApiTokenPurposeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ApiTokenPurpose", value)
}

// NewApiTokenPurposeFromValue returns a pointer to a valid ApiTokenPurpose
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewApiTokenPurposeFromValue(v string) (*ApiTokenPurpose, error) {
	ev := ApiTokenPurpose(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ApiTokenPurpose: valid values are %v", v, AllowedApiTokenPurposeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ApiTokenPurpose) IsValid() bool {
	for _, existing := range AllowedApiTokenPurposeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ApiTokenPurpose value
func (v ApiTokenPurpose) Ptr() *ApiTokenPurpose {
	return &v
}

type NullableApiTokenPurpose struct {
	value *ApiTokenPurpose
	isSet bool
}

func (v NullableApiTokenPurpose) Get() *ApiTokenPurpose {
	return v.value
}

func (v *NullableApiTokenPurpose) Set(val *ApiTokenPurpose) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTokenPurpose) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTokenPurpose) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTokenPurpose(val *ApiTokenPurpose) *NullableApiTokenPurpose {
	return &NullableApiTokenPurpose{value: val, isSet: true}
}

func (v NullableApiTokenPurpose) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTokenPurpose) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
