/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthStepOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthStepOneOf2{}

// AuthStepOneOf2 Request the named authentication mechanism to proceed
type AuthStepOneOf2 struct {
	// Request the named authentication mechanism to proceed
	Begin AuthMech `json:"begin"`
}

type _AuthStepOneOf2 AuthStepOneOf2

// NewAuthStepOneOf2 instantiates a new AuthStepOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthStepOneOf2(begin AuthMech) *AuthStepOneOf2 {
	this := AuthStepOneOf2{}
	this.Begin = begin
	return &this
}

// NewAuthStepOneOf2WithDefaults instantiates a new AuthStepOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthStepOneOf2WithDefaults() *AuthStepOneOf2 {
	this := AuthStepOneOf2{}
	return &this
}

// GetBegin returns the Begin field value
func (o *AuthStepOneOf2) GetBegin() AuthMech {
	if o == nil {
		var ret AuthMech
		return ret
	}

	return o.Begin
}

// GetBeginOk returns a tuple with the Begin field value
// and a boolean to check if the value has been set.
func (o *AuthStepOneOf2) GetBeginOk() (*AuthMech, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Begin, true
}

// SetBegin sets field value
func (o *AuthStepOneOf2) SetBegin(v AuthMech) {
	o.Begin = v
}

func (o AuthStepOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthStepOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["begin"] = o.Begin
	return toSerialize, nil
}

func (o *AuthStepOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"begin",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthStepOneOf2 := _AuthStepOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthStepOneOf2)

	if err != nil {
		return err
	}

	*o = AuthStepOneOf2(varAuthStepOneOf2)

	return err
}

type NullableAuthStepOneOf2 struct {
	value *AuthStepOneOf2
	isSet bool
}

func (v NullableAuthStepOneOf2) Get() *AuthStepOneOf2 {
	return v.value
}

func (v *NullableAuthStepOneOf2) Set(val *AuthStepOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthStepOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthStepOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthStepOneOf2(val *AuthStepOneOf2) *NullableAuthStepOneOf2 {
	return &NullableAuthStepOneOf2{value: val, isSet: true}
}

func (v NullableAuthStepOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthStepOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


