/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PluginErrorOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PluginErrorOneOf{}

// PluginErrorOneOf struct for PluginErrorOneOf
type PluginErrorOneOf struct {
	Base string `json:"base"`
}

type _PluginErrorOneOf PluginErrorOneOf

// NewPluginErrorOneOf instantiates a new PluginErrorOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginErrorOneOf(base string) *PluginErrorOneOf {
	this := PluginErrorOneOf{}
	this.Base = base
	return &this
}

// NewPluginErrorOneOfWithDefaults instantiates a new PluginErrorOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginErrorOneOfWithDefaults() *PluginErrorOneOf {
	this := PluginErrorOneOf{}
	return &this
}

// GetBase returns the Base field value
func (o *PluginErrorOneOf) GetBase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Base
}

// GetBaseOk returns a tuple with the Base field value
// and a boolean to check if the value has been set.
func (o *PluginErrorOneOf) GetBaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Base, true
}

// SetBase sets field value
func (o *PluginErrorOneOf) SetBase(v string) {
	o.Base = v
}

func (o PluginErrorOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PluginErrorOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["base"] = o.Base
	return toSerialize, nil
}

func (o *PluginErrorOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"base",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPluginErrorOneOf := _PluginErrorOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPluginErrorOneOf)

	if err != nil {
		return err
	}

	*o = PluginErrorOneOf(varPluginErrorOneOf)

	return err
}

type NullablePluginErrorOneOf struct {
	value *PluginErrorOneOf
	isSet bool
}

func (v NullablePluginErrorOneOf) Get() *PluginErrorOneOf {
	return v.value
}

func (v *NullablePluginErrorOneOf) Set(val *PluginErrorOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginErrorOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginErrorOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginErrorOneOf(val *PluginErrorOneOf) *NullablePluginErrorOneOf {
	return &NullablePluginErrorOneOf{value: val, isSet: true}
}

func (v NullablePluginErrorOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginErrorOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


