/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// IdentifyUserResponse - struct for IdentifyUserResponse
type IdentifyUserResponse struct {
	IdentifyUserResponseOneOf *IdentifyUserResponseOneOf
	String *string
}

// IdentifyUserResponseOneOfAsIdentifyUserResponse is a convenience function that returns IdentifyUserResponseOneOf wrapped in IdentifyUserResponse
func IdentifyUserResponseOneOfAsIdentifyUserResponse(v *IdentifyUserResponseOneOf) IdentifyUserResponse {
	return IdentifyUserResponse{
		IdentifyUserResponseOneOf: v,
	}
}

// stringAsIdentifyUserResponse is a convenience function that returns string wrapped in IdentifyUserResponse
func StringAsIdentifyUserResponse(v *string) IdentifyUserResponse {
	return IdentifyUserResponse{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *IdentifyUserResponse) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into IdentifyUserResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.IdentifyUserResponseOneOf)
	if err == nil {
		jsonIdentifyUserResponseOneOf, _ := json.Marshal(dst.IdentifyUserResponseOneOf)
		if string(jsonIdentifyUserResponseOneOf) == "{}" { // empty struct
			dst.IdentifyUserResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.IdentifyUserResponseOneOf); err != nil {
				dst.IdentifyUserResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.IdentifyUserResponseOneOf = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.IdentifyUserResponseOneOf = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(IdentifyUserResponse)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(IdentifyUserResponse)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src IdentifyUserResponse) MarshalJSON() ([]byte, error) {
	if src.IdentifyUserResponseOneOf != nil {
		return json.Marshal(&src.IdentifyUserResponseOneOf)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *IdentifyUserResponse) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.IdentifyUserResponseOneOf != nil {
		return obj.IdentifyUserResponseOneOf
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj IdentifyUserResponse) GetActualInstanceValue() (interface{}) {
	if obj.IdentifyUserResponseOneOf != nil {
		return *obj.IdentifyUserResponseOneOf
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableIdentifyUserResponse struct {
	value *IdentifyUserResponse
	isSet bool
}

func (v NullableIdentifyUserResponse) Get() *IdentifyUserResponse {
	return v.value
}

func (v *NullableIdentifyUserResponse) Set(val *IdentifyUserResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentifyUserResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentifyUserResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentifyUserResponse(val *IdentifyUserResponse) *NullableIdentifyUserResponse {
	return &NullableIdentifyUserResponse{value: val, isSet: true}
}

func (v NullableIdentifyUserResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentifyUserResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


