/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PluginError - struct for PluginError
type PluginError struct {
	PluginErrorOneOf *PluginErrorOneOf
	PluginErrorOneOf1 *PluginErrorOneOf1
	PluginErrorOneOf2 *PluginErrorOneOf2
	String *string
}

// PluginErrorOneOfAsPluginError is a convenience function that returns PluginErrorOneOf wrapped in PluginError
func PluginErrorOneOfAsPluginError(v *PluginErrorOneOf) PluginError {
	return PluginError{
		PluginErrorOneOf: v,
	}
}

// PluginErrorOneOf1AsPluginError is a convenience function that returns PluginErrorOneOf1 wrapped in PluginError
func PluginErrorOneOf1AsPluginError(v *PluginErrorOneOf1) PluginError {
	return PluginError{
		PluginErrorOneOf1: v,
	}
}

// PluginErrorOneOf2AsPluginError is a convenience function that returns PluginErrorOneOf2 wrapped in PluginError
func PluginErrorOneOf2AsPluginError(v *PluginErrorOneOf2) PluginError {
	return PluginError{
		PluginErrorOneOf2: v,
	}
}

// stringAsPluginError is a convenience function that returns string wrapped in PluginError
func StringAsPluginError(v *string) PluginError {
	return PluginError{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PluginError) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PluginErrorOneOf
	err = newStrictDecoder(data).Decode(&dst.PluginErrorOneOf)
	if err == nil {
		jsonPluginErrorOneOf, _ := json.Marshal(dst.PluginErrorOneOf)
		if string(jsonPluginErrorOneOf) == "{}" { // empty struct
			dst.PluginErrorOneOf = nil
		} else {
			if err = validator.Validate(dst.PluginErrorOneOf); err != nil {
				dst.PluginErrorOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.PluginErrorOneOf = nil
	}

	// try to unmarshal data into PluginErrorOneOf1
	err = newStrictDecoder(data).Decode(&dst.PluginErrorOneOf1)
	if err == nil {
		jsonPluginErrorOneOf1, _ := json.Marshal(dst.PluginErrorOneOf1)
		if string(jsonPluginErrorOneOf1) == "{}" { // empty struct
			dst.PluginErrorOneOf1 = nil
		} else {
			if err = validator.Validate(dst.PluginErrorOneOf1); err != nil {
				dst.PluginErrorOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PluginErrorOneOf1 = nil
	}

	// try to unmarshal data into PluginErrorOneOf2
	err = newStrictDecoder(data).Decode(&dst.PluginErrorOneOf2)
	if err == nil {
		jsonPluginErrorOneOf2, _ := json.Marshal(dst.PluginErrorOneOf2)
		if string(jsonPluginErrorOneOf2) == "{}" { // empty struct
			dst.PluginErrorOneOf2 = nil
		} else {
			if err = validator.Validate(dst.PluginErrorOneOf2); err != nil {
				dst.PluginErrorOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PluginErrorOneOf2 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PluginErrorOneOf = nil
		dst.PluginErrorOneOf1 = nil
		dst.PluginErrorOneOf2 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PluginError)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PluginError)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PluginError) MarshalJSON() ([]byte, error) {
	if src.PluginErrorOneOf != nil {
		return json.Marshal(&src.PluginErrorOneOf)
	}

	if src.PluginErrorOneOf1 != nil {
		return json.Marshal(&src.PluginErrorOneOf1)
	}

	if src.PluginErrorOneOf2 != nil {
		return json.Marshal(&src.PluginErrorOneOf2)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PluginError) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PluginErrorOneOf != nil {
		return obj.PluginErrorOneOf
	}

	if obj.PluginErrorOneOf1 != nil {
		return obj.PluginErrorOneOf1
	}

	if obj.PluginErrorOneOf2 != nil {
		return obj.PluginErrorOneOf2
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PluginError) GetActualInstanceValue() (interface{}) {
	if obj.PluginErrorOneOf != nil {
		return *obj.PluginErrorOneOf
	}

	if obj.PluginErrorOneOf1 != nil {
		return *obj.PluginErrorOneOf1
	}

	if obj.PluginErrorOneOf2 != nil {
		return *obj.PluginErrorOneOf2
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePluginError struct {
	value *PluginError
	isSet bool
}

func (v NullablePluginError) Get() *PluginError {
	return v.value
}

func (v *NullablePluginError) Set(val *PluginError) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginError) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginError(val *PluginError) *NullablePluginError {
	return &NullablePluginError{value: val, isSet: true}
}

func (v NullablePluginError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


