/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CredentialDetailTypeOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialDetailTypeOneOf1{}

// CredentialDetailTypeOneOf1 totp, webauthn
type CredentialDetailTypeOneOf1 struct {
	// totp, webauthn
	PasswordMfa []map[string]interface{} `json:"PasswordMfa"`
}

type _CredentialDetailTypeOneOf1 CredentialDetailTypeOneOf1

// NewCredentialDetailTypeOneOf1 instantiates a new CredentialDetailTypeOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialDetailTypeOneOf1(passwordMfa []map[string]interface{}) *CredentialDetailTypeOneOf1 {
	this := CredentialDetailTypeOneOf1{}
	this.PasswordMfa = passwordMfa
	return &this
}

// NewCredentialDetailTypeOneOf1WithDefaults instantiates a new CredentialDetailTypeOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialDetailTypeOneOf1WithDefaults() *CredentialDetailTypeOneOf1 {
	this := CredentialDetailTypeOneOf1{}
	return &this
}

// GetPasswordMfa returns the PasswordMfa field value
func (o *CredentialDetailTypeOneOf1) GetPasswordMfa() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.PasswordMfa
}

// GetPasswordMfaOk returns a tuple with the PasswordMfa field value
// and a boolean to check if the value has been set.
func (o *CredentialDetailTypeOneOf1) GetPasswordMfaOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.PasswordMfa, true
}

// SetPasswordMfa sets field value
func (o *CredentialDetailTypeOneOf1) SetPasswordMfa(v []map[string]interface{}) {
	o.PasswordMfa = v
}

func (o CredentialDetailTypeOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialDetailTypeOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["PasswordMfa"] = o.PasswordMfa
	return toSerialize, nil
}

func (o *CredentialDetailTypeOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"PasswordMfa",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCredentialDetailTypeOneOf1 := _CredentialDetailTypeOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCredentialDetailTypeOneOf1)

	if err != nil {
		return err
	}

	*o = CredentialDetailTypeOneOf1(varCredentialDetailTypeOneOf1)

	return err
}

type NullableCredentialDetailTypeOneOf1 struct {
	value *CredentialDetailTypeOneOf1
	isSet bool
}

func (v NullableCredentialDetailTypeOneOf1) Get() *CredentialDetailTypeOneOf1 {
	return v.value
}

func (v *NullableCredentialDetailTypeOneOf1) Set(val *CredentialDetailTypeOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialDetailTypeOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialDetailTypeOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialDetailTypeOneOf1(val *CredentialDetailTypeOneOf1) *NullableCredentialDetailTypeOneOf1 {
	return &NullableCredentialDetailTypeOneOf1{value: val, isSet: true}
}

func (v NullableCredentialDetailTypeOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialDetailTypeOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


