/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the UatPurposeOneOfReadwrite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UatPurposeOneOfReadwrite{}

// UatPurposeOneOfReadwrite struct for UatPurposeOneOfReadwrite
type UatPurposeOneOfReadwrite struct {
	// If none, there is no expiry, and this is always rw. If there is an expiry, check that the current time < expiry.
	Expiry NullableTime `json:"expiry,omitempty"`
}

// NewUatPurposeOneOfReadwrite instantiates a new UatPurposeOneOfReadwrite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUatPurposeOneOfReadwrite() *UatPurposeOneOfReadwrite {
	this := UatPurposeOneOfReadwrite{}
	return &this
}

// NewUatPurposeOneOfReadwriteWithDefaults instantiates a new UatPurposeOneOfReadwrite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUatPurposeOneOfReadwriteWithDefaults() *UatPurposeOneOfReadwrite {
	this := UatPurposeOneOfReadwrite{}
	return &this
}

// GetExpiry returns the Expiry field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UatPurposeOneOfReadwrite) GetExpiry() time.Time {
	if o == nil || IsNil(o.Expiry.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Expiry.Get()
}

// GetExpiryOk returns a tuple with the Expiry field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UatPurposeOneOfReadwrite) GetExpiryOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Expiry.Get(), o.Expiry.IsSet()
}

// HasExpiry returns a boolean if a field has been set.
func (o *UatPurposeOneOfReadwrite) HasExpiry() bool {
	if o != nil && o.Expiry.IsSet() {
		return true
	}

	return false
}

// SetExpiry gets a reference to the given NullableTime and assigns it to the Expiry field.
func (o *UatPurposeOneOfReadwrite) SetExpiry(v time.Time) {
	o.Expiry.Set(&v)
}
// SetExpiryNil sets the value for Expiry to be an explicit nil
func (o *UatPurposeOneOfReadwrite) SetExpiryNil() {
	o.Expiry.Set(nil)
}

// UnsetExpiry ensures that no value is present for Expiry, not even an explicit nil
func (o *UatPurposeOneOfReadwrite) UnsetExpiry() {
	o.Expiry.Unset()
}

func (o UatPurposeOneOfReadwrite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UatPurposeOneOfReadwrite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Expiry.IsSet() {
		toSerialize["expiry"] = o.Expiry.Get()
	}
	return toSerialize, nil
}

type NullableUatPurposeOneOfReadwrite struct {
	value *UatPurposeOneOfReadwrite
	isSet bool
}

func (v NullableUatPurposeOneOfReadwrite) Get() *UatPurposeOneOfReadwrite {
	return v.value
}

func (v *NullableUatPurposeOneOfReadwrite) Set(val *UatPurposeOneOfReadwrite) {
	v.value = val
	v.isSet = true
}

func (v NullableUatPurposeOneOfReadwrite) IsSet() bool {
	return v.isSet
}

func (v *NullableUatPurposeOneOfReadwrite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUatPurposeOneOfReadwrite(val *UatPurposeOneOfReadwrite) *NullableUatPurposeOneOfReadwrite {
	return &NullableUatPurposeOneOfReadwrite{value: val, isSet: true}
}

func (v NullableUatPurposeOneOfReadwrite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUatPurposeOneOfReadwrite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


