/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CredentialDetailType - struct for CredentialDetailType
type CredentialDetailType struct {
	CredentialDetailTypeOneOf *CredentialDetailTypeOneOf
	CredentialDetailTypeOneOf1 *CredentialDetailTypeOneOf1
	String *string
}

// CredentialDetailTypeOneOfAsCredentialDetailType is a convenience function that returns CredentialDetailTypeOneOf wrapped in CredentialDetailType
func CredentialDetailTypeOneOfAsCredentialDetailType(v *CredentialDetailTypeOneOf) CredentialDetailType {
	return CredentialDetailType{
		CredentialDetailTypeOneOf: v,
	}
}

// CredentialDetailTypeOneOf1AsCredentialDetailType is a convenience function that returns CredentialDetailTypeOneOf1 wrapped in CredentialDetailType
func CredentialDetailTypeOneOf1AsCredentialDetailType(v *CredentialDetailTypeOneOf1) CredentialDetailType {
	return CredentialDetailType{
		CredentialDetailTypeOneOf1: v,
	}
}

// stringAsCredentialDetailType is a convenience function that returns string wrapped in CredentialDetailType
func StringAsCredentialDetailType(v *string) CredentialDetailType {
	return CredentialDetailType{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CredentialDetailType) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CredentialDetailTypeOneOf
	err = newStrictDecoder(data).Decode(&dst.CredentialDetailTypeOneOf)
	if err == nil {
		jsonCredentialDetailTypeOneOf, _ := json.Marshal(dst.CredentialDetailTypeOneOf)
		if string(jsonCredentialDetailTypeOneOf) == "{}" { // empty struct
			dst.CredentialDetailTypeOneOf = nil
		} else {
			if err = validator.Validate(dst.CredentialDetailTypeOneOf); err != nil {
				dst.CredentialDetailTypeOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.CredentialDetailTypeOneOf = nil
	}

	// try to unmarshal data into CredentialDetailTypeOneOf1
	err = newStrictDecoder(data).Decode(&dst.CredentialDetailTypeOneOf1)
	if err == nil {
		jsonCredentialDetailTypeOneOf1, _ := json.Marshal(dst.CredentialDetailTypeOneOf1)
		if string(jsonCredentialDetailTypeOneOf1) == "{}" { // empty struct
			dst.CredentialDetailTypeOneOf1 = nil
		} else {
			if err = validator.Validate(dst.CredentialDetailTypeOneOf1); err != nil {
				dst.CredentialDetailTypeOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CredentialDetailTypeOneOf1 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CredentialDetailTypeOneOf = nil
		dst.CredentialDetailTypeOneOf1 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CredentialDetailType)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CredentialDetailType)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CredentialDetailType) MarshalJSON() ([]byte, error) {
	if src.CredentialDetailTypeOneOf != nil {
		return json.Marshal(&src.CredentialDetailTypeOneOf)
	}

	if src.CredentialDetailTypeOneOf1 != nil {
		return json.Marshal(&src.CredentialDetailTypeOneOf1)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CredentialDetailType) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CredentialDetailTypeOneOf != nil {
		return obj.CredentialDetailTypeOneOf
	}

	if obj.CredentialDetailTypeOneOf1 != nil {
		return obj.CredentialDetailTypeOneOf1
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CredentialDetailType) GetActualInstanceValue() (interface{}) {
	if obj.CredentialDetailTypeOneOf != nil {
		return *obj.CredentialDetailTypeOneOf
	}

	if obj.CredentialDetailTypeOneOf1 != nil {
		return *obj.CredentialDetailTypeOneOf1
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableCredentialDetailType struct {
	value *CredentialDetailType
	isSet bool
}

func (v NullableCredentialDetailType) Get() *CredentialDetailType {
	return v.value
}

func (v *NullableCredentialDetailType) Set(val *CredentialDetailType) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialDetailType) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialDetailType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialDetailType(val *CredentialDetailType) *NullableCredentialDetailType {
	return &NullableCredentialDetailType{value: val, isSet: true}
}

func (v NullableCredentialDetailType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialDetailType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


