/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the ScimEntryGetQuery type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimEntryGetQuery{}

// ScimEntryGetQuery SCIM Query Parameters used during the get of a single entry
type ScimEntryGetQuery struct {
	Attributes []Attribute `json:"attributes,omitempty"`
	ExtAccessCheck *bool `json:"extAccessCheck,omitempty"`
	SortBy NullableAttribute `json:"sortBy,omitempty"`
	SortOrder NullableScimSortOrder `json:"sortOrder,omitempty"`
	StartIndex *int64 `json:"startIndex,omitempty"`
	Count *int64 `json:"count,omitempty"`
	Filter interface{} `json:"filter,omitempty"`
}

// NewScimEntryGetQuery instantiates a new ScimEntryGetQuery object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimEntryGetQuery() *ScimEntryGetQuery {
	this := ScimEntryGetQuery{}
	return &this
}

// NewScimEntryGetQueryWithDefaults instantiates a new ScimEntryGetQuery object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimEntryGetQueryWithDefaults() *ScimEntryGetQuery {
	this := ScimEntryGetQuery{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScimEntryGetQuery) GetAttributes() []Attribute {
	if o == nil {
		var ret []Attribute
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScimEntryGetQuery) GetAttributesOk() ([]Attribute, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ScimEntryGetQuery) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []Attribute and assigns it to the Attributes field.
func (o *ScimEntryGetQuery) SetAttributes(v []Attribute) {
	o.Attributes = v
}

// GetExtAccessCheck returns the ExtAccessCheck field value if set, zero value otherwise.
func (o *ScimEntryGetQuery) GetExtAccessCheck() bool {
	if o == nil || IsNil(o.ExtAccessCheck) {
		var ret bool
		return ret
	}
	return *o.ExtAccessCheck
}

// GetExtAccessCheckOk returns a tuple with the ExtAccessCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimEntryGetQuery) GetExtAccessCheckOk() (*bool, bool) {
	if o == nil || IsNil(o.ExtAccessCheck) {
		return nil, false
	}
	return o.ExtAccessCheck, true
}

// HasExtAccessCheck returns a boolean if a field has been set.
func (o *ScimEntryGetQuery) HasExtAccessCheck() bool {
	if o != nil && !IsNil(o.ExtAccessCheck) {
		return true
	}

	return false
}

// SetExtAccessCheck gets a reference to the given bool and assigns it to the ExtAccessCheck field.
func (o *ScimEntryGetQuery) SetExtAccessCheck(v bool) {
	o.ExtAccessCheck = &v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScimEntryGetQuery) GetSortBy() Attribute {
	if o == nil || IsNil(o.SortBy.Get()) {
		var ret Attribute
		return ret
	}
	return *o.SortBy.Get()
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScimEntryGetQuery) GetSortByOk() (*Attribute, bool) {
	if o == nil {
		return nil, false
	}
	return o.SortBy.Get(), o.SortBy.IsSet()
}

// HasSortBy returns a boolean if a field has been set.
func (o *ScimEntryGetQuery) HasSortBy() bool {
	if o != nil && o.SortBy.IsSet() {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given NullableAttribute and assigns it to the SortBy field.
func (o *ScimEntryGetQuery) SetSortBy(v Attribute) {
	o.SortBy.Set(&v)
}
// SetSortByNil sets the value for SortBy to be an explicit nil
func (o *ScimEntryGetQuery) SetSortByNil() {
	o.SortBy.Set(nil)
}

// UnsetSortBy ensures that no value is present for SortBy, not even an explicit nil
func (o *ScimEntryGetQuery) UnsetSortBy() {
	o.SortBy.Unset()
}

// GetSortOrder returns the SortOrder field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScimEntryGetQuery) GetSortOrder() ScimSortOrder {
	if o == nil || IsNil(o.SortOrder.Get()) {
		var ret ScimSortOrder
		return ret
	}
	return *o.SortOrder.Get()
}

// GetSortOrderOk returns a tuple with the SortOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScimEntryGetQuery) GetSortOrderOk() (*ScimSortOrder, bool) {
	if o == nil {
		return nil, false
	}
	return o.SortOrder.Get(), o.SortOrder.IsSet()
}

// HasSortOrder returns a boolean if a field has been set.
func (o *ScimEntryGetQuery) HasSortOrder() bool {
	if o != nil && o.SortOrder.IsSet() {
		return true
	}

	return false
}

// SetSortOrder gets a reference to the given NullableScimSortOrder and assigns it to the SortOrder field.
func (o *ScimEntryGetQuery) SetSortOrder(v ScimSortOrder) {
	o.SortOrder.Set(&v)
}
// SetSortOrderNil sets the value for SortOrder to be an explicit nil
func (o *ScimEntryGetQuery) SetSortOrderNil() {
	o.SortOrder.Set(nil)
}

// UnsetSortOrder ensures that no value is present for SortOrder, not even an explicit nil
func (o *ScimEntryGetQuery) UnsetSortOrder() {
	o.SortOrder.Unset()
}

// GetStartIndex returns the StartIndex field value if set, zero value otherwise.
func (o *ScimEntryGetQuery) GetStartIndex() int64 {
	if o == nil || IsNil(o.StartIndex) {
		var ret int64
		return ret
	}
	return *o.StartIndex
}

// GetStartIndexOk returns a tuple with the StartIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimEntryGetQuery) GetStartIndexOk() (*int64, bool) {
	if o == nil || IsNil(o.StartIndex) {
		return nil, false
	}
	return o.StartIndex, true
}

// HasStartIndex returns a boolean if a field has been set.
func (o *ScimEntryGetQuery) HasStartIndex() bool {
	if o != nil && !IsNil(o.StartIndex) {
		return true
	}

	return false
}

// SetStartIndex gets a reference to the given int64 and assigns it to the StartIndex field.
func (o *ScimEntryGetQuery) SetStartIndex(v int64) {
	o.StartIndex = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ScimEntryGetQuery) GetCount() int64 {
	if o == nil || IsNil(o.Count) {
		var ret int64
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScimEntryGetQuery) GetCountOk() (*int64, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ScimEntryGetQuery) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int64 and assigns it to the Count field.
func (o *ScimEntryGetQuery) SetCount(v int64) {
	o.Count = &v
}

// GetFilter returns the Filter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScimEntryGetQuery) GetFilter() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScimEntryGetQuery) GetFilterOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return &o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *ScimEntryGetQuery) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given interface{} and assigns it to the Filter field.
func (o *ScimEntryGetQuery) SetFilter(v interface{}) {
	o.Filter = v
}

func (o ScimEntryGetQuery) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimEntryGetQuery) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.ExtAccessCheck) {
		toSerialize["extAccessCheck"] = o.ExtAccessCheck
	}
	if o.SortBy.IsSet() {
		toSerialize["sortBy"] = o.SortBy.Get()
	}
	if o.SortOrder.IsSet() {
		toSerialize["sortOrder"] = o.SortOrder.Get()
	}
	if !IsNil(o.StartIndex) {
		toSerialize["startIndex"] = o.StartIndex
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if o.Filter != nil {
		toSerialize["filter"] = o.Filter
	}
	return toSerialize, nil
}

type NullableScimEntryGetQuery struct {
	value *ScimEntryGetQuery
	isSet bool
}

func (v NullableScimEntryGetQuery) Get() *ScimEntryGetQuery {
	return v.value
}

func (v *NullableScimEntryGetQuery) Set(val *ScimEntryGetQuery) {
	v.value = val
	v.isSet = true
}

func (v NullableScimEntryGetQuery) IsSet() bool {
	return v.isSet
}

func (v *NullableScimEntryGetQuery) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimEntryGetQuery(val *ScimEntryGetQuery) *NullableScimEntryGetQuery {
	return &NullableScimEntryGetQuery{value: val, isSet: true}
}

func (v NullableScimEntryGetQuery) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimEntryGetQuery) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


