/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// AuthCredential - The credential challenge provided by a user.
type AuthCredential struct {
	AuthAllowedOneOf *AuthAllowedOneOf
	AuthCredentialOneOf *AuthCredentialOneOf
	AuthCredentialOneOf1 *AuthCredentialOneOf1
	AuthCredentialOneOf2 *AuthCredentialOneOf2
	AuthCredentialOneOf3 *AuthCredentialOneOf3
	String *string
}

// AuthAllowedOneOfAsAuthCredential is a convenience function that returns AuthAllowedOneOf wrapped in AuthCredential
func AuthAllowedOneOfAsAuthCredential(v *AuthAllowedOneOf) AuthCredential {
	return AuthCredential{
		AuthAllowedOneOf: v,
	}
}

// AuthCredentialOneOfAsAuthCredential is a convenience function that returns AuthCredentialOneOf wrapped in AuthCredential
func AuthCredentialOneOfAsAuthCredential(v *AuthCredentialOneOf) AuthCredential {
	return AuthCredential{
		AuthCredentialOneOf: v,
	}
}

// AuthCredentialOneOf1AsAuthCredential is a convenience function that returns AuthCredentialOneOf1 wrapped in AuthCredential
func AuthCredentialOneOf1AsAuthCredential(v *AuthCredentialOneOf1) AuthCredential {
	return AuthCredential{
		AuthCredentialOneOf1: v,
	}
}

// AuthCredentialOneOf2AsAuthCredential is a convenience function that returns AuthCredentialOneOf2 wrapped in AuthCredential
func AuthCredentialOneOf2AsAuthCredential(v *AuthCredentialOneOf2) AuthCredential {
	return AuthCredential{
		AuthCredentialOneOf2: v,
	}
}

// AuthCredentialOneOf3AsAuthCredential is a convenience function that returns AuthCredentialOneOf3 wrapped in AuthCredential
func AuthCredentialOneOf3AsAuthCredential(v *AuthCredentialOneOf3) AuthCredential {
	return AuthCredential{
		AuthCredentialOneOf3: v,
	}
}

// stringAsAuthCredential is a convenience function that returns string wrapped in AuthCredential
func StringAsAuthCredential(v *string) AuthCredential {
	return AuthCredential{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *AuthCredential) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into AuthAllowedOneOf
	err = newStrictDecoder(data).Decode(&dst.AuthAllowedOneOf)
	if err == nil {
		jsonAuthAllowedOneOf, _ := json.Marshal(dst.AuthAllowedOneOf)
		if string(jsonAuthAllowedOneOf) == "{}" { // empty struct
			dst.AuthAllowedOneOf = nil
		} else {
			if err = validator.Validate(dst.AuthAllowedOneOf); err != nil {
				dst.AuthAllowedOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuthAllowedOneOf = nil
	}

	// try to unmarshal data into AuthCredentialOneOf
	err = newStrictDecoder(data).Decode(&dst.AuthCredentialOneOf)
	if err == nil {
		jsonAuthCredentialOneOf, _ := json.Marshal(dst.AuthCredentialOneOf)
		if string(jsonAuthCredentialOneOf) == "{}" { // empty struct
			dst.AuthCredentialOneOf = nil
		} else {
			if err = validator.Validate(dst.AuthCredentialOneOf); err != nil {
				dst.AuthCredentialOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuthCredentialOneOf = nil
	}

	// try to unmarshal data into AuthCredentialOneOf1
	err = newStrictDecoder(data).Decode(&dst.AuthCredentialOneOf1)
	if err == nil {
		jsonAuthCredentialOneOf1, _ := json.Marshal(dst.AuthCredentialOneOf1)
		if string(jsonAuthCredentialOneOf1) == "{}" { // empty struct
			dst.AuthCredentialOneOf1 = nil
		} else {
			if err = validator.Validate(dst.AuthCredentialOneOf1); err != nil {
				dst.AuthCredentialOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuthCredentialOneOf1 = nil
	}

	// try to unmarshal data into AuthCredentialOneOf2
	err = newStrictDecoder(data).Decode(&dst.AuthCredentialOneOf2)
	if err == nil {
		jsonAuthCredentialOneOf2, _ := json.Marshal(dst.AuthCredentialOneOf2)
		if string(jsonAuthCredentialOneOf2) == "{}" { // empty struct
			dst.AuthCredentialOneOf2 = nil
		} else {
			if err = validator.Validate(dst.AuthCredentialOneOf2); err != nil {
				dst.AuthCredentialOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuthCredentialOneOf2 = nil
	}

	// try to unmarshal data into AuthCredentialOneOf3
	err = newStrictDecoder(data).Decode(&dst.AuthCredentialOneOf3)
	if err == nil {
		jsonAuthCredentialOneOf3, _ := json.Marshal(dst.AuthCredentialOneOf3)
		if string(jsonAuthCredentialOneOf3) == "{}" { // empty struct
			dst.AuthCredentialOneOf3 = nil
		} else {
			if err = validator.Validate(dst.AuthCredentialOneOf3); err != nil {
				dst.AuthCredentialOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.AuthCredentialOneOf3 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.AuthAllowedOneOf = nil
		dst.AuthCredentialOneOf = nil
		dst.AuthCredentialOneOf1 = nil
		dst.AuthCredentialOneOf2 = nil
		dst.AuthCredentialOneOf3 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(AuthCredential)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(AuthCredential)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src AuthCredential) MarshalJSON() ([]byte, error) {
	if src.AuthAllowedOneOf != nil {
		return json.Marshal(&src.AuthAllowedOneOf)
	}

	if src.AuthCredentialOneOf != nil {
		return json.Marshal(&src.AuthCredentialOneOf)
	}

	if src.AuthCredentialOneOf1 != nil {
		return json.Marshal(&src.AuthCredentialOneOf1)
	}

	if src.AuthCredentialOneOf2 != nil {
		return json.Marshal(&src.AuthCredentialOneOf2)
	}

	if src.AuthCredentialOneOf3 != nil {
		return json.Marshal(&src.AuthCredentialOneOf3)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *AuthCredential) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.AuthAllowedOneOf != nil {
		return obj.AuthAllowedOneOf
	}

	if obj.AuthCredentialOneOf != nil {
		return obj.AuthCredentialOneOf
	}

	if obj.AuthCredentialOneOf1 != nil {
		return obj.AuthCredentialOneOf1
	}

	if obj.AuthCredentialOneOf2 != nil {
		return obj.AuthCredentialOneOf2
	}

	if obj.AuthCredentialOneOf3 != nil {
		return obj.AuthCredentialOneOf3
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj AuthCredential) GetActualInstanceValue() (interface{}) {
	if obj.AuthAllowedOneOf != nil {
		return *obj.AuthAllowedOneOf
	}

	if obj.AuthCredentialOneOf != nil {
		return *obj.AuthCredentialOneOf
	}

	if obj.AuthCredentialOneOf1 != nil {
		return *obj.AuthCredentialOneOf1
	}

	if obj.AuthCredentialOneOf2 != nil {
		return *obj.AuthCredentialOneOf2
	}

	if obj.AuthCredentialOneOf3 != nil {
		return *obj.AuthCredentialOneOf3
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableAuthCredential struct {
	value *AuthCredential
	isSet bool
}

func (v NullableAuthCredential) Get() *AuthCredential {
	return v.value
}

func (v *NullableAuthCredential) Set(val *AuthCredential) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthCredential) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthCredential) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthCredential(val *AuthCredential) *NullableAuthCredential {
	return &NullableAuthCredential{value: val, isSet: true}
}

func (v NullableAuthCredential) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthCredential) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


