/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SchemaErrorOneOf5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SchemaErrorOneOf5{}

// SchemaErrorOneOf5 struct for SchemaErrorOneOf5
type SchemaErrorOneOf5 struct {
	Excludesnotsatisfied []string `json:"excludesnotsatisfied"`
}

type _SchemaErrorOneOf5 SchemaErrorOneOf5

// NewSchemaErrorOneOf5 instantiates a new SchemaErrorOneOf5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaErrorOneOf5(excludesnotsatisfied []string) *SchemaErrorOneOf5 {
	this := SchemaErrorOneOf5{}
	this.Excludesnotsatisfied = excludesnotsatisfied
	return &this
}

// NewSchemaErrorOneOf5WithDefaults instantiates a new SchemaErrorOneOf5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaErrorOneOf5WithDefaults() *SchemaErrorOneOf5 {
	this := SchemaErrorOneOf5{}
	return &this
}

// GetExcludesnotsatisfied returns the Excludesnotsatisfied field value
func (o *SchemaErrorOneOf5) GetExcludesnotsatisfied() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Excludesnotsatisfied
}

// GetExcludesnotsatisfiedOk returns a tuple with the Excludesnotsatisfied field value
// and a boolean to check if the value has been set.
func (o *SchemaErrorOneOf5) GetExcludesnotsatisfiedOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Excludesnotsatisfied, true
}

// SetExcludesnotsatisfied sets field value
func (o *SchemaErrorOneOf5) SetExcludesnotsatisfied(v []string) {
	o.Excludesnotsatisfied = v
}

func (o SchemaErrorOneOf5) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SchemaErrorOneOf5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["excludesnotsatisfied"] = o.Excludesnotsatisfied
	return toSerialize, nil
}

func (o *SchemaErrorOneOf5) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"excludesnotsatisfied",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSchemaErrorOneOf5 := _SchemaErrorOneOf5{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSchemaErrorOneOf5)

	if err != nil {
		return err
	}

	*o = SchemaErrorOneOf5(varSchemaErrorOneOf5)

	return err
}

type NullableSchemaErrorOneOf5 struct {
	value *SchemaErrorOneOf5
	isSet bool
}

func (v NullableSchemaErrorOneOf5) Get() *SchemaErrorOneOf5 {
	return v.value
}

func (v *NullableSchemaErrorOneOf5) Set(val *SchemaErrorOneOf5) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaErrorOneOf5) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaErrorOneOf5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaErrorOneOf5(val *SchemaErrorOneOf5) *NullableSchemaErrorOneOf5 {
	return &NullableSchemaErrorOneOf5{value: val, isSet: true}
}

func (v NullableSchemaErrorOneOf5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaErrorOneOf5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


