/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the ScimEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimEntry{}

// ScimEntry struct for ScimEntry
type ScimEntry struct {
	Schemas []string `json:"schemas"`
	Id string `json:"id"`
	ExternalId NullableString `json:"externalId,omitempty"`
	Meta NullableScimMeta `json:"meta,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ScimEntry ScimEntry

// NewScimEntry instantiates a new ScimEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimEntry(schemas []string, id string) *ScimEntry {
	this := ScimEntry{}
	this.Schemas = schemas
	this.Id = id
	return &this
}

// NewScimEntryWithDefaults instantiates a new ScimEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimEntryWithDefaults() *ScimEntry {
	this := ScimEntry{}
	return &this
}

// GetSchemas returns the Schemas field value
func (o *ScimEntry) GetSchemas() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Schemas
}

// GetSchemasOk returns a tuple with the Schemas field value
// and a boolean to check if the value has been set.
func (o *ScimEntry) GetSchemasOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Schemas, true
}

// SetSchemas sets field value
func (o *ScimEntry) SetSchemas(v []string) {
	o.Schemas = v
}

// GetId returns the Id field value
func (o *ScimEntry) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ScimEntry) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ScimEntry) SetId(v string) {
	o.Id = v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScimEntry) GetExternalId() string {
	if o == nil || IsNil(o.ExternalId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScimEntry) GetExternalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *ScimEntry) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *ScimEntry) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}
// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *ScimEntry) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *ScimEntry) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetMeta returns the Meta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScimEntry) GetMeta() ScimMeta {
	if o == nil || IsNil(o.Meta.Get()) {
		var ret ScimMeta
		return ret
	}
	return *o.Meta.Get()
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScimEntry) GetMetaOk() (*ScimMeta, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta.Get(), o.Meta.IsSet()
}

// HasMeta returns a boolean if a field has been set.
func (o *ScimEntry) HasMeta() bool {
	if o != nil && o.Meta.IsSet() {
		return true
	}

	return false
}

// SetMeta gets a reference to the given NullableScimMeta and assigns it to the Meta field.
func (o *ScimEntry) SetMeta(v ScimMeta) {
	o.Meta.Set(&v)
}
// SetMetaNil sets the value for Meta to be an explicit nil
func (o *ScimEntry) SetMetaNil() {
	o.Meta.Set(nil)
}

// UnsetMeta ensures that no value is present for Meta, not even an explicit nil
func (o *ScimEntry) UnsetMeta() {
	o.Meta.Unset()
}

func (o ScimEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schemas"] = o.Schemas
	toSerialize["id"] = o.Id
	if o.ExternalId.IsSet() {
		toSerialize["externalId"] = o.ExternalId.Get()
	}
	if o.Meta.IsSet() {
		toSerialize["meta"] = o.Meta.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ScimEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schemas",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScimEntry := _ScimEntry{}

	err = json.Unmarshal(data, &varScimEntry)

	if err != nil {
		return err
	}

	*o = ScimEntry(varScimEntry)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "schemas")
		delete(additionalProperties, "id")
		delete(additionalProperties, "externalId")
		delete(additionalProperties, "meta")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableScimEntry struct {
	value *ScimEntry
	isSet bool
}

func (v NullableScimEntry) Get() *ScimEntry {
	return v.value
}

func (v *NullableScimEntry) Set(val *ScimEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableScimEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableScimEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimEntry(val *ScimEntry) *NullableScimEntry {
	return &NullableScimEntry{value: val, isSet: true}
}

func (v NullableScimEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


