/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// UatPurposeStatus The current purpose of a User Auth Token. It may be read-only, read-write or privilege capable (able to step up to read-write after re-authentication).
type UatPurposeStatus string

// List of UatPurposeStatus
const (
	UAT_READONLY         UatPurposeStatus = "readonly"
	UAT_READWRITE        UatPurposeStatus = "readwrite"
	UAT_PRIVILEGECAPABLE UatPurposeStatus = "privilegecapable"
)

// All allowed values of UatPurposeStatus enum
var AllowedUatPurposeStatusEnumValues = []UatPurposeStatus{
	"readonly",
	"readwrite",
	"privilegecapable",
}

func (v *UatPurposeStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UatPurposeStatus(value)
	for _, existing := range AllowedUatPurposeStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UatPurposeStatus", value)
}

// NewUatPurposeStatusFromValue returns a pointer to a valid UatPurposeStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUatPurposeStatusFromValue(v string) (*UatPurposeStatus, error) {
	ev := UatPurposeStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UatPurposeStatus: valid values are %v", v, AllowedUatPurposeStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UatPurposeStatus) IsValid() bool {
	for _, existing := range AllowedUatPurposeStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UatPurposeStatus value
func (v UatPurposeStatus) Ptr() *UatPurposeStatus {
	return &v
}

type NullableUatPurposeStatus struct {
	value *UatPurposeStatus
	isSet bool
}

func (v NullableUatPurposeStatus) Get() *UatPurposeStatus {
	return v.value
}

func (v *NullableUatPurposeStatus) Set(val *UatPurposeStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableUatPurposeStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableUatPurposeStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUatPurposeStatus(val *UatPurposeStatus) *NullableUatPurposeStatus {
	return &NullableUatPurposeStatus{value: val, isSet: true}
}

func (v NullableUatPurposeStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUatPurposeStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
