/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// AuthMech The mechanisms that may proceed in this authentication
type AuthMech string

// List of AuthMech
const (
	ANONYMOUS AuthMech = "anonymous"
	PASSWORD AuthMech = "password"
	PASSWORDBACKUPCODE AuthMech = "passwordbackupcode"
	PASSWORDMFA AuthMech = "passwordmfa"
	PASSWORDSECURITYKEY AuthMech = "passwordsecuritykey"
	PASSKEY AuthMech = "passkey"
	OAUTH2TRUST AuthMech = "oauth2trust"
)

// All allowed values of AuthMech enum
var AllowedAuthMechEnumValues = []AuthMech{
	"anonymous",
	"password",
	"passwordbackupcode",
	"passwordmfa",
	"passwordsecuritykey",
	"passkey",
	"oauth2trust",
}

func (v *AuthMech) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AuthMech(value)
	for _, existing := range AllowedAuthMechEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AuthMech", value)
}

// NewAuthMechFromValue returns a pointer to a valid AuthMech
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAuthMechFromValue(v string) (*AuthMech, error) {
	ev := AuthMech(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AuthMech: valid values are %v", v, AllowedAuthMechEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AuthMech) IsValid() bool {
	for _, existing := range AllowedAuthMechEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AuthMech value
func (v AuthMech) Ptr() *AuthMech {
	return &v
}

type NullableAuthMech struct {
	value *AuthMech
	isSet bool
}

func (v NullableAuthMech) Get() *AuthMech {
	return v.value
}

func (v *NullableAuthMech) Set(val *AuthMech) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthMech) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthMech) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthMech(val *AuthMech) *NullableAuthMech {
	return &NullableAuthMech{value: val, isSet: true}
}

func (v NullableAuthMech) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthMech) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

