/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SingleStringRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SingleStringRequest{}

// SingleStringRequest struct for SingleStringRequest
type SingleStringRequest struct {
	Value string `json:"value"`
}

type _SingleStringRequest SingleStringRequest

// NewSingleStringRequest instantiates a new SingleStringRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSingleStringRequest(value string) *SingleStringRequest {
	this := SingleStringRequest{}
	this.Value = value
	return &this
}

// NewSingleStringRequestWithDefaults instantiates a new SingleStringRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSingleStringRequestWithDefaults() *SingleStringRequest {
	this := SingleStringRequest{}
	return &this
}

// GetValue returns the Value field value
func (o *SingleStringRequest) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *SingleStringRequest) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *SingleStringRequest) SetValue(v string) {
	o.Value = v
}

func (o SingleStringRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SingleStringRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *SingleStringRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSingleStringRequest := _SingleStringRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSingleStringRequest)

	if err != nil {
		return err
	}

	*o = SingleStringRequest(varSingleStringRequest)

	return err
}

type NullableSingleStringRequest struct {
	value *SingleStringRequest
	isSet bool
}

func (v NullableSingleStringRequest) Get() *SingleStringRequest {
	return v.value
}

func (v *NullableSingleStringRequest) Set(val *SingleStringRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSingleStringRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSingleStringRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSingleStringRequest(val *SingleStringRequest) *NullableSingleStringRequest {
	return &NullableSingleStringRequest{value: val, isSet: true}
}

func (v NullableSingleStringRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSingleStringRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


