/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ScimSyncState - struct for ScimSyncState
type ScimSyncState struct {
	ScimSyncStateOneOf *ScimSyncStateOneOf
	String *string
}

// ScimSyncStateOneOfAsScimSyncState is a convenience function that returns ScimSyncStateOneOf wrapped in ScimSyncState
func ScimSyncStateOneOfAsScimSyncState(v *ScimSyncStateOneOf) ScimSyncState {
	return ScimSyncState{
		ScimSyncStateOneOf: v,
	}
}

// stringAsScimSyncState is a convenience function that returns string wrapped in ScimSyncState
func StringAsScimSyncState(v *string) ScimSyncState {
	return ScimSyncState{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ScimSyncState) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ScimSyncStateOneOf
	err = newStrictDecoder(data).Decode(&dst.ScimSyncStateOneOf)
	if err == nil {
		jsonScimSyncStateOneOf, _ := json.Marshal(dst.ScimSyncStateOneOf)
		if string(jsonScimSyncStateOneOf) == "{}" { // empty struct
			dst.ScimSyncStateOneOf = nil
		} else {
			if err = validator.Validate(dst.ScimSyncStateOneOf); err != nil {
				dst.ScimSyncStateOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.ScimSyncStateOneOf = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ScimSyncStateOneOf = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ScimSyncState)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ScimSyncState)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ScimSyncState) MarshalJSON() ([]byte, error) {
	if src.ScimSyncStateOneOf != nil {
		return json.Marshal(&src.ScimSyncStateOneOf)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ScimSyncState) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ScimSyncStateOneOf != nil {
		return obj.ScimSyncStateOneOf
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ScimSyncState) GetActualInstanceValue() (interface{}) {
	if obj.ScimSyncStateOneOf != nil {
		return *obj.ScimSyncStateOneOf
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableScimSyncState struct {
	value *ScimSyncState
	isSet bool
}

func (v NullableScimSyncState) Get() *ScimSyncState {
	return v.value
}

func (v *NullableScimSyncState) Set(val *ScimSyncState) {
	v.value = val
	v.isSet = true
}

func (v NullableScimSyncState) IsSet() bool {
	return v.isSet
}

func (v *NullableScimSyncState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimSyncState(val *ScimSyncState) *NullableScimSyncState {
	return &NullableScimSyncState{value: val, isSet: true}
}

func (v NullableScimSyncState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimSyncState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


