/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AttributeOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AttributeOneOf{}

// AttributeOneOf struct for AttributeOneOf
type AttributeOneOf struct {
	Custom string `json:"custom"`
}

type _AttributeOneOf AttributeOneOf

// NewAttributeOneOf instantiates a new AttributeOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttributeOneOf(custom string) *AttributeOneOf {
	this := AttributeOneOf{}
	this.Custom = custom
	return &this
}

// NewAttributeOneOfWithDefaults instantiates a new AttributeOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttributeOneOfWithDefaults() *AttributeOneOf {
	this := AttributeOneOf{}
	return &this
}

// GetCustom returns the Custom field value
func (o *AttributeOneOf) GetCustom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Custom
}

// GetCustomOk returns a tuple with the Custom field value
// and a boolean to check if the value has been set.
func (o *AttributeOneOf) GetCustomOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Custom, true
}

// SetCustom sets field value
func (o *AttributeOneOf) SetCustom(v string) {
	o.Custom = v
}

func (o AttributeOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AttributeOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["custom"] = o.Custom
	return toSerialize, nil
}

func (o *AttributeOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"custom",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAttributeOneOf := _AttributeOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAttributeOneOf)

	if err != nil {
		return err
	}

	*o = AttributeOneOf(varAttributeOneOf)

	return err
}

type NullableAttributeOneOf struct {
	value *AttributeOneOf
	isSet bool
}

func (v NullableAttributeOneOf) Get() *AttributeOneOf {
	return v.value
}

func (v *NullableAttributeOneOf) Set(val *AttributeOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableAttributeOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableAttributeOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttributeOneOf(val *AttributeOneOf) *NullableAttributeOneOf {
	return &NullableAttributeOneOf{value: val, isSet: true}
}

func (v NullableAttributeOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttributeOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


