/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// UiHint the model 'UiHint'
type UiHint string

// List of UiHint
const (
	EXPERIMENTALFEATURES UiHint = "experimentalfeatures"
	POSIXACCOUNT UiHint = "posixaccount"
	CREDENTIALUPDATE UiHint = "credentialupdate"
	SYNCHRONISEDACCOUNT UiHint = "synchronisedaccount"
)

// All allowed values of UiHint enum
var AllowedUiHintEnumValues = []UiHint{
	"experimentalfeatures",
	"posixaccount",
	"credentialupdate",
	"synchronisedaccount",
}

func (v *UiHint) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := UiHint(value)
	for _, existing := range AllowedUiHintEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid UiHint", value)
}

// NewUiHintFromValue returns a pointer to a valid UiHint
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewUiHintFromValue(v string) (*UiHint, error) {
	ev := UiHint(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for UiHint: valid values are %v", v, AllowedUiHintEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v UiHint) IsValid() bool {
	for _, existing := range AllowedUiHintEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to UiHint value
func (v UiHint) Ptr() *UiHint {
	return &v
}

type NullableUiHint struct {
	value *UiHint
	isSet bool
}

func (v NullableUiHint) Get() *UiHint {
	return v.value
}

func (v *NullableUiHint) Set(val *UiHint) {
	v.value = val
	v.isSet = true
}

func (v NullableUiHint) IsSet() bool {
	return v.isSet
}

func (v *NullableUiHint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUiHint(val *UiHint) *NullableUiHint {
	return &NullableUiHint{value: val, isSet: true}
}

func (v NullableUiHint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUiHint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

