/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BackupCodesView type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupCodesView{}

// BackupCodesView struct for BackupCodesView
type BackupCodesView struct {
	BackupCodes []string `json:"backup_codes"`
}

type _BackupCodesView BackupCodesView

// NewBackupCodesView instantiates a new BackupCodesView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupCodesView(backupCodes []string) *BackupCodesView {
	this := BackupCodesView{}
	this.BackupCodes = backupCodes
	return &this
}

// NewBackupCodesViewWithDefaults instantiates a new BackupCodesView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupCodesViewWithDefaults() *BackupCodesView {
	this := BackupCodesView{}
	return &this
}

// GetBackupCodes returns the BackupCodes field value
func (o *BackupCodesView) GetBackupCodes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BackupCodes
}

// GetBackupCodesOk returns a tuple with the BackupCodes field value
// and a boolean to check if the value has been set.
func (o *BackupCodesView) GetBackupCodesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BackupCodes, true
}

// SetBackupCodes sets field value
func (o *BackupCodesView) SetBackupCodes(v []string) {
	o.BackupCodes = v
}

func (o BackupCodesView) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupCodesView) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["backup_codes"] = o.BackupCodes
	return toSerialize, nil
}

func (o *BackupCodesView) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backup_codes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBackupCodesView := _BackupCodesView{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBackupCodesView)

	if err != nil {
		return err
	}

	*o = BackupCodesView(varBackupCodesView)

	return err
}

type NullableBackupCodesView struct {
	value *BackupCodesView
	isSet bool
}

func (v NullableBackupCodesView) Get() *BackupCodesView {
	return v.value
}

func (v *NullableBackupCodesView) Set(val *BackupCodesView) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupCodesView) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupCodesView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupCodesView(val *BackupCodesView) *NullableBackupCodesView {
	return &NullableBackupCodesView{value: val, isSet: true}
}

func (v NullableBackupCodesView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupCodesView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


