/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CUExtPortalOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CUExtPortalOneOf{}

// CUExtPortalOneOf struct for CUExtPortalOneOf
type CUExtPortalOneOf struct {
	Some string `json:"Some"`
}

type _CUExtPortalOneOf CUExtPortalOneOf

// NewCUExtPortalOneOf instantiates a new CUExtPortalOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCUExtPortalOneOf(some string) *CUExtPortalOneOf {
	this := CUExtPortalOneOf{}
	this.Some = some
	return &this
}

// NewCUExtPortalOneOfWithDefaults instantiates a new CUExtPortalOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCUExtPortalOneOfWithDefaults() *CUExtPortalOneOf {
	this := CUExtPortalOneOf{}
	return &this
}

// GetSome returns the Some field value
func (o *CUExtPortalOneOf) GetSome() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Some
}

// GetSomeOk returns a tuple with the Some field value
// and a boolean to check if the value has been set.
func (o *CUExtPortalOneOf) GetSomeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Some, true
}

// SetSome sets field value
func (o *CUExtPortalOneOf) SetSome(v string) {
	o.Some = v
}

func (o CUExtPortalOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CUExtPortalOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Some"] = o.Some
	return toSerialize, nil
}

func (o *CUExtPortalOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Some",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCUExtPortalOneOf := _CUExtPortalOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCUExtPortalOneOf)

	if err != nil {
		return err
	}

	*o = CUExtPortalOneOf(varCUExtPortalOneOf)

	return err
}

type NullableCUExtPortalOneOf struct {
	value *CUExtPortalOneOf
	isSet bool
}

func (v NullableCUExtPortalOneOf) Get() *CUExtPortalOneOf {
	return v.value
}

func (v *NullableCUExtPortalOneOf) Set(val *CUExtPortalOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCUExtPortalOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCUExtPortalOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCUExtPortalOneOf(val *CUExtPortalOneOf) *NullableCUExtPortalOneOf {
	return &NullableCUExtPortalOneOf{value: val, isSet: true}
}

func (v NullableCUExtPortalOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCUExtPortalOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


