/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CURegStateOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CURegStateOneOf1{}

// CURegStateOneOf1 struct for CURegStateOneOf1
type CURegStateOneOf1 struct {
	TotpNameTryAgain string `json:"TotpNameTryAgain"`
}

type _CURegStateOneOf1 CURegStateOneOf1

// NewCURegStateOneOf1 instantiates a new CURegStateOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCURegStateOneOf1(totpNameTryAgain string) *CURegStateOneOf1 {
	this := CURegStateOneOf1{}
	this.TotpNameTryAgain = totpNameTryAgain
	return &this
}

// NewCURegStateOneOf1WithDefaults instantiates a new CURegStateOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCURegStateOneOf1WithDefaults() *CURegStateOneOf1 {
	this := CURegStateOneOf1{}
	return &this
}

// GetTotpNameTryAgain returns the TotpNameTryAgain field value
func (o *CURegStateOneOf1) GetTotpNameTryAgain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TotpNameTryAgain
}

// GetTotpNameTryAgainOk returns a tuple with the TotpNameTryAgain field value
// and a boolean to check if the value has been set.
func (o *CURegStateOneOf1) GetTotpNameTryAgainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotpNameTryAgain, true
}

// SetTotpNameTryAgain sets field value
func (o *CURegStateOneOf1) SetTotpNameTryAgain(v string) {
	o.TotpNameTryAgain = v
}

func (o CURegStateOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CURegStateOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["TotpNameTryAgain"] = o.TotpNameTryAgain
	return toSerialize, nil
}

func (o *CURegStateOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"TotpNameTryAgain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCURegStateOneOf1 := _CURegStateOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCURegStateOneOf1)

	if err != nil {
		return err
	}

	*o = CURegStateOneOf1(varCURegStateOneOf1)

	return err
}

type NullableCURegStateOneOf1 struct {
	value *CURegStateOneOf1
	isSet bool
}

func (v NullableCURegStateOneOf1) Get() *CURegStateOneOf1 {
	return v.value
}

func (v *NullableCURegStateOneOf1) Set(val *CURegStateOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableCURegStateOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableCURegStateOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCURegStateOneOf1(val *CURegStateOneOf1) *NullableCURegStateOneOf1 {
	return &NullableCURegStateOneOf1{value: val, isSet: true}
}

func (v NullableCURegStateOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCURegStateOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


