/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// UatStatusState - The expiry of the User Auth Token.
type UatStatusState struct {
	UatStatusStateOneOf *UatStatusStateOneOf
	String *string
}

// UatStatusStateOneOfAsUatStatusState is a convenience function that returns UatStatusStateOneOf wrapped in UatStatusState
func UatStatusStateOneOfAsUatStatusState(v *UatStatusStateOneOf) UatStatusState {
	return UatStatusState{
		UatStatusStateOneOf: v,
	}
}

// stringAsUatStatusState is a convenience function that returns string wrapped in UatStatusState
func StringAsUatStatusState(v *string) UatStatusState {
	return UatStatusState{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *UatStatusState) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into UatStatusStateOneOf
	err = newStrictDecoder(data).Decode(&dst.UatStatusStateOneOf)
	if err == nil {
		jsonUatStatusStateOneOf, _ := json.Marshal(dst.UatStatusStateOneOf)
		if string(jsonUatStatusStateOneOf) == "{}" { // empty struct
			dst.UatStatusStateOneOf = nil
		} else {
			if err = validator.Validate(dst.UatStatusStateOneOf); err != nil {
				dst.UatStatusStateOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.UatStatusStateOneOf = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.UatStatusStateOneOf = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(UatStatusState)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(UatStatusState)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UatStatusState) MarshalJSON() ([]byte, error) {
	if src.UatStatusStateOneOf != nil {
		return json.Marshal(&src.UatStatusStateOneOf)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *UatStatusState) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.UatStatusStateOneOf != nil {
		return obj.UatStatusStateOneOf
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj UatStatusState) GetActualInstanceValue() (interface{}) {
	if obj.UatStatusStateOneOf != nil {
		return *obj.UatStatusStateOneOf
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableUatStatusState struct {
	value *UatStatusState
	isSet bool
}

func (v NullableUatStatusState) Get() *UatStatusState {
	return v.value
}

func (v *NullableUatStatusState) Set(val *UatStatusState) {
	v.value = val
	v.isSet = true
}

func (v NullableUatStatusState) IsSet() bool {
	return v.isSet
}

func (v *NullableUatStatusState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUatStatusState(val *UatStatusState) *NullableUatStatusState {
	return &NullableUatStatusState{value: val, isSet: true}
}

func (v NullableUatStatusState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUatStatusState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


