/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConsistencyErrorOneOf9 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsistencyErrorOneOf9{}

// ConsistencyErrorOneOf9 struct for ConsistencyErrorOneOf9
type ConsistencyErrorOneOf9 struct {
	Invalidspn int64 `json:"invalidspn"`
}

type _ConsistencyErrorOneOf9 ConsistencyErrorOneOf9

// NewConsistencyErrorOneOf9 instantiates a new ConsistencyErrorOneOf9 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsistencyErrorOneOf9(invalidspn int64) *ConsistencyErrorOneOf9 {
	this := ConsistencyErrorOneOf9{}
	this.Invalidspn = invalidspn
	return &this
}

// NewConsistencyErrorOneOf9WithDefaults instantiates a new ConsistencyErrorOneOf9 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsistencyErrorOneOf9WithDefaults() *ConsistencyErrorOneOf9 {
	this := ConsistencyErrorOneOf9{}
	return &this
}

// GetInvalidspn returns the Invalidspn field value
func (o *ConsistencyErrorOneOf9) GetInvalidspn() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Invalidspn
}

// GetInvalidspnOk returns a tuple with the Invalidspn field value
// and a boolean to check if the value has been set.
func (o *ConsistencyErrorOneOf9) GetInvalidspnOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Invalidspn, true
}

// SetInvalidspn sets field value
func (o *ConsistencyErrorOneOf9) SetInvalidspn(v int64) {
	o.Invalidspn = v
}

func (o ConsistencyErrorOneOf9) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsistencyErrorOneOf9) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invalidspn"] = o.Invalidspn
	return toSerialize, nil
}

func (o *ConsistencyErrorOneOf9) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invalidspn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsistencyErrorOneOf9 := _ConsistencyErrorOneOf9{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsistencyErrorOneOf9)

	if err != nil {
		return err
	}

	*o = ConsistencyErrorOneOf9(varConsistencyErrorOneOf9)

	return err
}

type NullableConsistencyErrorOneOf9 struct {
	value *ConsistencyErrorOneOf9
	isSet bool
}

func (v NullableConsistencyErrorOneOf9) Get() *ConsistencyErrorOneOf9 {
	return v.value
}

func (v *NullableConsistencyErrorOneOf9) Set(val *ConsistencyErrorOneOf9) {
	v.value = val
	v.isSet = true
}

func (v NullableConsistencyErrorOneOf9) IsSet() bool {
	return v.isSet
}

func (v *NullableConsistencyErrorOneOf9) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsistencyErrorOneOf9(val *ConsistencyErrorOneOf9) *NullableConsistencyErrorOneOf9 {
	return &NullableConsistencyErrorOneOf9{value: val, isSet: true}
}

func (v NullableConsistencyErrorOneOf9) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsistencyErrorOneOf9) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


