/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthStateOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthStateOneOf1{}

// AuthStateOneOf1 Continue to auth, allowed mechanisms/challenges listed.
type AuthStateOneOf1 struct {
	// Continue to auth, allowed mechanisms/challenges listed.
	Continue []AuthAllowed `json:"continue"`
}

type _AuthStateOneOf1 AuthStateOneOf1

// NewAuthStateOneOf1 instantiates a new AuthStateOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthStateOneOf1(continue_ []AuthAllowed) *AuthStateOneOf1 {
	this := AuthStateOneOf1{}
	this.Continue = continue_
	return &this
}

// NewAuthStateOneOf1WithDefaults instantiates a new AuthStateOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthStateOneOf1WithDefaults() *AuthStateOneOf1 {
	this := AuthStateOneOf1{}
	return &this
}

// GetContinue returns the Continue field value
func (o *AuthStateOneOf1) GetContinue() []AuthAllowed {
	if o == nil {
		var ret []AuthAllowed
		return ret
	}

	return o.Continue
}

// GetContinueOk returns a tuple with the Continue field value
// and a boolean to check if the value has been set.
func (o *AuthStateOneOf1) GetContinueOk() ([]AuthAllowed, bool) {
	if o == nil {
		return nil, false
	}
	return o.Continue, true
}

// SetContinue sets field value
func (o *AuthStateOneOf1) SetContinue(v []AuthAllowed) {
	o.Continue = v
}

func (o AuthStateOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthStateOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["continue"] = o.Continue
	return toSerialize, nil
}

func (o *AuthStateOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"continue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthStateOneOf1 := _AuthStateOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthStateOneOf1)

	if err != nil {
		return err
	}

	*o = AuthStateOneOf1(varAuthStateOneOf1)

	return err
}

type NullableAuthStateOneOf1 struct {
	value *AuthStateOneOf1
	isSet bool
}

func (v NullableAuthStateOneOf1) Get() *AuthStateOneOf1 {
	return v.value
}

func (v *NullableAuthStateOneOf1) Set(val *AuthStateOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthStateOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthStateOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthStateOneOf1(val *AuthStateOneOf1) *NullableAuthStateOneOf1 {
	return &NullableAuthStateOneOf1{value: val, isSet: true}
}

func (v NullableAuthStateOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthStateOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


