/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConsistencyErrorOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsistencyErrorOneOf2{}

// ConsistencyErrorOneOf2 struct for ConsistencyErrorOneOf2
type ConsistencyErrorOneOf2 struct {
	Schemauuidnotunique string `json:"schemauuidnotunique"`
}

type _ConsistencyErrorOneOf2 ConsistencyErrorOneOf2

// NewConsistencyErrorOneOf2 instantiates a new ConsistencyErrorOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsistencyErrorOneOf2(schemauuidnotunique string) *ConsistencyErrorOneOf2 {
	this := ConsistencyErrorOneOf2{}
	this.Schemauuidnotunique = schemauuidnotunique
	return &this
}

// NewConsistencyErrorOneOf2WithDefaults instantiates a new ConsistencyErrorOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsistencyErrorOneOf2WithDefaults() *ConsistencyErrorOneOf2 {
	this := ConsistencyErrorOneOf2{}
	return &this
}

// GetSchemauuidnotunique returns the Schemauuidnotunique field value
func (o *ConsistencyErrorOneOf2) GetSchemauuidnotunique() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schemauuidnotunique
}

// GetSchemauuidnotuniqueOk returns a tuple with the Schemauuidnotunique field value
// and a boolean to check if the value has been set.
func (o *ConsistencyErrorOneOf2) GetSchemauuidnotuniqueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schemauuidnotunique, true
}

// SetSchemauuidnotunique sets field value
func (o *ConsistencyErrorOneOf2) SetSchemauuidnotunique(v string) {
	o.Schemauuidnotunique = v
}

func (o ConsistencyErrorOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsistencyErrorOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["schemauuidnotunique"] = o.Schemauuidnotunique
	return toSerialize, nil
}

func (o *ConsistencyErrorOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"schemauuidnotunique",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsistencyErrorOneOf2 := _ConsistencyErrorOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsistencyErrorOneOf2)

	if err != nil {
		return err
	}

	*o = ConsistencyErrorOneOf2(varConsistencyErrorOneOf2)

	return err
}

type NullableConsistencyErrorOneOf2 struct {
	value *ConsistencyErrorOneOf2
	isSet bool
}

func (v NullableConsistencyErrorOneOf2) Get() *ConsistencyErrorOneOf2 {
	return v.value
}

func (v *NullableConsistencyErrorOneOf2) Set(val *ConsistencyErrorOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableConsistencyErrorOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableConsistencyErrorOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsistencyErrorOneOf2(val *ConsistencyErrorOneOf2) *NullableConsistencyErrorOneOf2 {
	return &NullableConsistencyErrorOneOf2{value: val, isSet: true}
}

func (v NullableConsistencyErrorOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsistencyErrorOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


