/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CUSessionToken type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CUSessionToken{}

// CUSessionToken struct for CUSessionToken
type CUSessionToken struct {
	Token string `json:"token"`
}

type _CUSessionToken CUSessionToken

// NewCUSessionToken instantiates a new CUSessionToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCUSessionToken(token string) *CUSessionToken {
	this := CUSessionToken{}
	this.Token = token
	return &this
}

// NewCUSessionTokenWithDefaults instantiates a new CUSessionToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCUSessionTokenWithDefaults() *CUSessionToken {
	this := CUSessionToken{}
	return &this
}

// GetToken returns the Token field value
func (o *CUSessionToken) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *CUSessionToken) GetTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *CUSessionToken) SetToken(v string) {
	o.Token = v
}

func (o CUSessionToken) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CUSessionToken) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *CUSessionToken) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCUSessionToken := _CUSessionToken{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCUSessionToken)

	if err != nil {
		return err
	}

	*o = CUSessionToken(varCUSessionToken)

	return err
}

type NullableCUSessionToken struct {
	value *CUSessionToken
	isSet bool
}

func (v NullableCUSessionToken) Get() *CUSessionToken {
	return v.value
}

func (v *NullableCUSessionToken) Set(val *CUSessionToken) {
	v.value = val
	v.isSet = true
}

func (v NullableCUSessionToken) IsSet() bool {
	return v.isSet
}

func (v *NullableCUSessionToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCUSessionToken(val *CUSessionToken) *NullableCUSessionToken {
	return &NullableCUSessionToken{value: val, isSet: true}
}

func (v NullableCUSessionToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCUSessionToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


