/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FilterOneOf3 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilterOneOf3{}

// FilterOneOf3 struct for FilterOneOf3
type FilterOneOf3 struct {
	Or []Filter `json:"or"`
}

type _FilterOneOf3 FilterOneOf3

// NewFilterOneOf3 instantiates a new FilterOneOf3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterOneOf3(or []Filter) *FilterOneOf3 {
	this := FilterOneOf3{}
	this.Or = or
	return &this
}

// NewFilterOneOf3WithDefaults instantiates a new FilterOneOf3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterOneOf3WithDefaults() *FilterOneOf3 {
	this := FilterOneOf3{}
	return &this
}

// GetOr returns the Or field value
func (o *FilterOneOf3) GetOr() []Filter {
	if o == nil {
		var ret []Filter
		return ret
	}

	return o.Or
}

// GetOrOk returns a tuple with the Or field value
// and a boolean to check if the value has been set.
func (o *FilterOneOf3) GetOrOk() ([]Filter, bool) {
	if o == nil {
		return nil, false
	}
	return o.Or, true
}

// SetOr sets field value
func (o *FilterOneOf3) SetOr(v []Filter) {
	o.Or = v
}

func (o FilterOneOf3) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilterOneOf3) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["or"] = o.Or
	return toSerialize, nil
}

func (o *FilterOneOf3) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"or",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFilterOneOf3 := _FilterOneOf3{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFilterOneOf3)

	if err != nil {
		return err
	}

	*o = FilterOneOf3(varFilterOneOf3)

	return err
}

type NullableFilterOneOf3 struct {
	value *FilterOneOf3
	isSet bool
}

func (v NullableFilterOneOf3) Get() *FilterOneOf3 {
	return v.value
}

func (v *NullableFilterOneOf3) Set(val *FilterOneOf3) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterOneOf3) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterOneOf3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterOneOf3(val *FilterOneOf3) *NullableFilterOneOf3 {
	return &NullableFilterOneOf3{value: val, isSet: true}
}

func (v NullableFilterOneOf3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterOneOf3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


