/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebErrorOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebErrorOneOf2{}

// WebErrorOneOf2 struct for WebErrorOneOf2
type WebErrorOneOf2 struct {
	OAuth2 map[string]interface{} `json:"OAuth2"`
}

type _WebErrorOneOf2 WebErrorOneOf2

// NewWebErrorOneOf2 instantiates a new WebErrorOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebErrorOneOf2(oAuth2 map[string]interface{}) *WebErrorOneOf2 {
	this := WebErrorOneOf2{}
	this.OAuth2 = oAuth2
	return &this
}

// NewWebErrorOneOf2WithDefaults instantiates a new WebErrorOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebErrorOneOf2WithDefaults() *WebErrorOneOf2 {
	this := WebErrorOneOf2{}
	return &this
}

// GetOAuth2 returns the OAuth2 field value
func (o *WebErrorOneOf2) GetOAuth2() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.OAuth2
}

// GetOAuth2Ok returns a tuple with the OAuth2 field value
// and a boolean to check if the value has been set.
func (o *WebErrorOneOf2) GetOAuth2Ok() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.OAuth2, true
}

// SetOAuth2 sets field value
func (o *WebErrorOneOf2) SetOAuth2(v map[string]interface{}) {
	o.OAuth2 = v
}

func (o WebErrorOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebErrorOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["OAuth2"] = o.OAuth2
	return toSerialize, nil
}

func (o *WebErrorOneOf2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"OAuth2",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebErrorOneOf2 := _WebErrorOneOf2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebErrorOneOf2)

	if err != nil {
		return err
	}

	*o = WebErrorOneOf2(varWebErrorOneOf2)

	return err
}

type NullableWebErrorOneOf2 struct {
	value *WebErrorOneOf2
	isSet bool
}

func (v NullableWebErrorOneOf2) Get() *WebErrorOneOf2 {
	return v.value
}

func (v *NullableWebErrorOneOf2) Set(val *WebErrorOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableWebErrorOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableWebErrorOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebErrorOneOf2(val *WebErrorOneOf2) *NullableWebErrorOneOf2 {
	return &NullableWebErrorOneOf2{value: val, isSet: true}
}

func (v NullableWebErrorOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebErrorOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


