/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperationErrorOneOf11 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationErrorOneOf11{}

// OperationErrorOneOf11 struct for OperationErrorOneOf11
type OperationErrorOneOf11 struct {
	Missingattribute Attribute `json:"missingattribute"`
}

type _OperationErrorOneOf11 OperationErrorOneOf11

// NewOperationErrorOneOf11 instantiates a new OperationErrorOneOf11 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationErrorOneOf11(missingattribute Attribute) *OperationErrorOneOf11 {
	this := OperationErrorOneOf11{}
	this.Missingattribute = missingattribute
	return &this
}

// NewOperationErrorOneOf11WithDefaults instantiates a new OperationErrorOneOf11 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationErrorOneOf11WithDefaults() *OperationErrorOneOf11 {
	this := OperationErrorOneOf11{}
	return &this
}

// GetMissingattribute returns the Missingattribute field value
func (o *OperationErrorOneOf11) GetMissingattribute() Attribute {
	if o == nil {
		var ret Attribute
		return ret
	}

	return o.Missingattribute
}

// GetMissingattributeOk returns a tuple with the Missingattribute field value
// and a boolean to check if the value has been set.
func (o *OperationErrorOneOf11) GetMissingattributeOk() (*Attribute, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Missingattribute, true
}

// SetMissingattribute sets field value
func (o *OperationErrorOneOf11) SetMissingattribute(v Attribute) {
	o.Missingattribute = v
}

func (o OperationErrorOneOf11) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationErrorOneOf11) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["missingattribute"] = o.Missingattribute
	return toSerialize, nil
}

func (o *OperationErrorOneOf11) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"missingattribute",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperationErrorOneOf11 := _OperationErrorOneOf11{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperationErrorOneOf11)

	if err != nil {
		return err
	}

	*o = OperationErrorOneOf11(varOperationErrorOneOf11)

	return err
}

type NullableOperationErrorOneOf11 struct {
	value *OperationErrorOneOf11
	isSet bool
}

func (v NullableOperationErrorOneOf11) Get() *OperationErrorOneOf11 {
	return v.value
}

func (v *NullableOperationErrorOneOf11) Set(val *OperationErrorOneOf11) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationErrorOneOf11) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationErrorOneOf11) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationErrorOneOf11(val *OperationErrorOneOf11) *NullableOperationErrorOneOf11 {
	return &NullableOperationErrorOneOf11{value: val, isSet: true}
}

func (v NullableOperationErrorOneOf11) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationErrorOneOf11) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


