/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProtoEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProtoEntry{}

// ProtoEntry struct for ProtoEntry
type ProtoEntry struct {
	Attrs map[string][]string `json:"attrs"`
}

type _ProtoEntry ProtoEntry

// NewProtoEntry instantiates a new ProtoEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtoEntry(attrs map[string][]string) *ProtoEntry {
	this := ProtoEntry{}
	this.Attrs = attrs
	return &this
}

// NewProtoEntryWithDefaults instantiates a new ProtoEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtoEntryWithDefaults() *ProtoEntry {
	this := ProtoEntry{}
	return &this
}

// GetAttrs returns the Attrs field value
func (o *ProtoEntry) GetAttrs() map[string][]string {
	if o == nil {
		var ret map[string][]string
		return ret
	}

	return o.Attrs
}

// GetAttrsOk returns a tuple with the Attrs field value
// and a boolean to check if the value has been set.
func (o *ProtoEntry) GetAttrsOk() (map[string][]string, bool) {
	if o == nil {
		return map[string][]string{}, false
	}
	return o.Attrs, true
}

// SetAttrs sets field value
func (o *ProtoEntry) SetAttrs(v map[string][]string) {
	o.Attrs = v
}

func (o ProtoEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProtoEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attrs"] = o.Attrs
	return toSerialize, nil
}

func (o *ProtoEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attrs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProtoEntry := _ProtoEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProtoEntry)

	if err != nil {
		return err
	}

	*o = ProtoEntry(varProtoEntry)

	return err
}

type NullableProtoEntry struct {
	value *ProtoEntry
	isSet bool
}

func (v NullableProtoEntry) Get() *ProtoEntry {
	return v.value
}

func (v *NullableProtoEntry) Set(val *ProtoEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableProtoEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableProtoEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtoEntry(val *ProtoEntry) *NullableProtoEntry {
	return &NullableProtoEntry{value: val, isSet: true}
}

func (v NullableProtoEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtoEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


