/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ScimApplicationPassword type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScimApplicationPassword{}

// ScimApplicationPassword struct for ScimApplicationPassword
type ScimApplicationPassword struct {
	Uuid string `json:"uuid"`
	Label string `json:"label"`
	Secret string `json:"secret"`
}

type _ScimApplicationPassword ScimApplicationPassword

// NewScimApplicationPassword instantiates a new ScimApplicationPassword object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScimApplicationPassword(uuid string, label string, secret string) *ScimApplicationPassword {
	this := ScimApplicationPassword{}
	this.Uuid = uuid
	this.Label = label
	this.Secret = secret
	return &this
}

// NewScimApplicationPasswordWithDefaults instantiates a new ScimApplicationPassword object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScimApplicationPasswordWithDefaults() *ScimApplicationPassword {
	this := ScimApplicationPassword{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *ScimApplicationPassword) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *ScimApplicationPassword) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *ScimApplicationPassword) SetUuid(v string) {
	o.Uuid = v
}

// GetLabel returns the Label field value
func (o *ScimApplicationPassword) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ScimApplicationPassword) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ScimApplicationPassword) SetLabel(v string) {
	o.Label = v
}

// GetSecret returns the Secret field value
func (o *ScimApplicationPassword) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *ScimApplicationPassword) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *ScimApplicationPassword) SetSecret(v string) {
	o.Secret = v
}

func (o ScimApplicationPassword) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScimApplicationPassword) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["label"] = o.Label
	toSerialize["secret"] = o.Secret
	return toSerialize, nil
}

func (o *ScimApplicationPassword) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"label",
		"secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScimApplicationPassword := _ScimApplicationPassword{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScimApplicationPassword)

	if err != nil {
		return err
	}

	*o = ScimApplicationPassword(varScimApplicationPassword)

	return err
}

type NullableScimApplicationPassword struct {
	value *ScimApplicationPassword
	isSet bool
}

func (v NullableScimApplicationPassword) Get() *ScimApplicationPassword {
	return v.value
}

func (v *NullableScimApplicationPassword) Set(val *ScimApplicationPassword) {
	v.value = val
	v.isSet = true
}

func (v NullableScimApplicationPassword) IsSet() bool {
	return v.isSet
}

func (v *NullableScimApplicationPassword) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScimApplicationPassword(val *ScimApplicationPassword) *NullableScimApplicationPassword {
	return &NullableScimApplicationPassword{value: val, isSet: true}
}

func (v NullableScimApplicationPassword) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScimApplicationPassword) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


