/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConsistencyErrorOneOf14 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsistencyErrorOneOf14{}

// ConsistencyErrorOneOf14 struct for ConsistencyErrorOneOf14
type ConsistencyErrorOneOf14 struct {
	Keyprovideruuidmissing ConsistencyErrorOneOf14Keyprovideruuidmissing `json:"keyprovideruuidmissing"`
}

type _ConsistencyErrorOneOf14 ConsistencyErrorOneOf14

// NewConsistencyErrorOneOf14 instantiates a new ConsistencyErrorOneOf14 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsistencyErrorOneOf14(keyprovideruuidmissing ConsistencyErrorOneOf14Keyprovideruuidmissing) *ConsistencyErrorOneOf14 {
	this := ConsistencyErrorOneOf14{}
	this.Keyprovideruuidmissing = keyprovideruuidmissing
	return &this
}

// NewConsistencyErrorOneOf14WithDefaults instantiates a new ConsistencyErrorOneOf14 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsistencyErrorOneOf14WithDefaults() *ConsistencyErrorOneOf14 {
	this := ConsistencyErrorOneOf14{}
	return &this
}

// GetKeyprovideruuidmissing returns the Keyprovideruuidmissing field value
func (o *ConsistencyErrorOneOf14) GetKeyprovideruuidmissing() ConsistencyErrorOneOf14Keyprovideruuidmissing {
	if o == nil {
		var ret ConsistencyErrorOneOf14Keyprovideruuidmissing
		return ret
	}

	return o.Keyprovideruuidmissing
}

// GetKeyprovideruuidmissingOk returns a tuple with the Keyprovideruuidmissing field value
// and a boolean to check if the value has been set.
func (o *ConsistencyErrorOneOf14) GetKeyprovideruuidmissingOk() (*ConsistencyErrorOneOf14Keyprovideruuidmissing, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Keyprovideruuidmissing, true
}

// SetKeyprovideruuidmissing sets field value
func (o *ConsistencyErrorOneOf14) SetKeyprovideruuidmissing(v ConsistencyErrorOneOf14Keyprovideruuidmissing) {
	o.Keyprovideruuidmissing = v
}

func (o ConsistencyErrorOneOf14) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsistencyErrorOneOf14) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["keyprovideruuidmissing"] = o.Keyprovideruuidmissing
	return toSerialize, nil
}

func (o *ConsistencyErrorOneOf14) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"keyprovideruuidmissing",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsistencyErrorOneOf14 := _ConsistencyErrorOneOf14{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsistencyErrorOneOf14)

	if err != nil {
		return err
	}

	*o = ConsistencyErrorOneOf14(varConsistencyErrorOneOf14)

	return err
}

type NullableConsistencyErrorOneOf14 struct {
	value *ConsistencyErrorOneOf14
	isSet bool
}

func (v NullableConsistencyErrorOneOf14) Get() *ConsistencyErrorOneOf14 {
	return v.value
}

func (v *NullableConsistencyErrorOneOf14) Set(val *ConsistencyErrorOneOf14) {
	v.value = val
	v.isSet = true
}

func (v NullableConsistencyErrorOneOf14) IsSet() bool {
	return v.isSet
}

func (v *NullableConsistencyErrorOneOf14) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsistencyErrorOneOf14(val *ConsistencyErrorOneOf14) *NullableConsistencyErrorOneOf14 {
	return &NullableConsistencyErrorOneOf14{value: val, isSet: true}
}

func (v NullableConsistencyErrorOneOf14) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsistencyErrorOneOf14) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


