/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperationErrorOneOf13 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationErrorOneOf13{}

// OperationErrorOneOf13 struct for OperationErrorOneOf13
type OperationErrorOneOf13 struct {
	Invalidauthstate string `json:"invalidauthstate"`
}

type _OperationErrorOneOf13 OperationErrorOneOf13

// NewOperationErrorOneOf13 instantiates a new OperationErrorOneOf13 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationErrorOneOf13(invalidauthstate string) *OperationErrorOneOf13 {
	this := OperationErrorOneOf13{}
	this.Invalidauthstate = invalidauthstate
	return &this
}

// NewOperationErrorOneOf13WithDefaults instantiates a new OperationErrorOneOf13 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationErrorOneOf13WithDefaults() *OperationErrorOneOf13 {
	this := OperationErrorOneOf13{}
	return &this
}

// GetInvalidauthstate returns the Invalidauthstate field value
func (o *OperationErrorOneOf13) GetInvalidauthstate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Invalidauthstate
}

// GetInvalidauthstateOk returns a tuple with the Invalidauthstate field value
// and a boolean to check if the value has been set.
func (o *OperationErrorOneOf13) GetInvalidauthstateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Invalidauthstate, true
}

// SetInvalidauthstate sets field value
func (o *OperationErrorOneOf13) SetInvalidauthstate(v string) {
	o.Invalidauthstate = v
}

func (o OperationErrorOneOf13) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationErrorOneOf13) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["invalidauthstate"] = o.Invalidauthstate
	return toSerialize, nil
}

func (o *OperationErrorOneOf13) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"invalidauthstate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperationErrorOneOf13 := _OperationErrorOneOf13{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperationErrorOneOf13)

	if err != nil {
		return err
	}

	*o = OperationErrorOneOf13(varOperationErrorOneOf13)

	return err
}

type NullableOperationErrorOneOf13 struct {
	value *OperationErrorOneOf13
	isSet bool
}

func (v NullableOperationErrorOneOf13) Get() *OperationErrorOneOf13 {
	return v.value
}

func (v *NullableOperationErrorOneOf13) Set(val *OperationErrorOneOf13) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationErrorOneOf13) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationErrorOneOf13) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationErrorOneOf13(val *OperationErrorOneOf13) *NullableOperationErrorOneOf13 {
	return &NullableOperationErrorOneOf13{value: val, isSet: true}
}

func (v NullableOperationErrorOneOf13) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationErrorOneOf13) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


