/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CURegState - struct for CURegState
type CURegState struct {
	CURegStateOneOf *CURegStateOneOf
	CURegStateOneOf1 *CURegStateOneOf1
	CURegStateOneOf2 *CURegStateOneOf2
	CURegStateOneOf3 *CURegStateOneOf3
	CURegStateOneOf4 *CURegStateOneOf4
	String *string
}

// CURegStateOneOfAsCURegState is a convenience function that returns CURegStateOneOf wrapped in CURegState
func CURegStateOneOfAsCURegState(v *CURegStateOneOf) CURegState {
	return CURegState{
		CURegStateOneOf: v,
	}
}

// CURegStateOneOf1AsCURegState is a convenience function that returns CURegStateOneOf1 wrapped in CURegState
func CURegStateOneOf1AsCURegState(v *CURegStateOneOf1) CURegState {
	return CURegState{
		CURegStateOneOf1: v,
	}
}

// CURegStateOneOf2AsCURegState is a convenience function that returns CURegStateOneOf2 wrapped in CURegState
func CURegStateOneOf2AsCURegState(v *CURegStateOneOf2) CURegState {
	return CURegState{
		CURegStateOneOf2: v,
	}
}

// CURegStateOneOf3AsCURegState is a convenience function that returns CURegStateOneOf3 wrapped in CURegState
func CURegStateOneOf3AsCURegState(v *CURegStateOneOf3) CURegState {
	return CURegState{
		CURegStateOneOf3: v,
	}
}

// CURegStateOneOf4AsCURegState is a convenience function that returns CURegStateOneOf4 wrapped in CURegState
func CURegStateOneOf4AsCURegState(v *CURegStateOneOf4) CURegState {
	return CURegState{
		CURegStateOneOf4: v,
	}
}

// stringAsCURegState is a convenience function that returns string wrapped in CURegState
func StringAsCURegState(v *string) CURegState {
	return CURegState{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CURegState) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CURegStateOneOf
	err = newStrictDecoder(data).Decode(&dst.CURegStateOneOf)
	if err == nil {
		jsonCURegStateOneOf, _ := json.Marshal(dst.CURegStateOneOf)
		if string(jsonCURegStateOneOf) == "{}" { // empty struct
			dst.CURegStateOneOf = nil
		} else {
			if err = validator.Validate(dst.CURegStateOneOf); err != nil {
				dst.CURegStateOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.CURegStateOneOf = nil
	}

	// try to unmarshal data into CURegStateOneOf1
	err = newStrictDecoder(data).Decode(&dst.CURegStateOneOf1)
	if err == nil {
		jsonCURegStateOneOf1, _ := json.Marshal(dst.CURegStateOneOf1)
		if string(jsonCURegStateOneOf1) == "{}" { // empty struct
			dst.CURegStateOneOf1 = nil
		} else {
			if err = validator.Validate(dst.CURegStateOneOf1); err != nil {
				dst.CURegStateOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CURegStateOneOf1 = nil
	}

	// try to unmarshal data into CURegStateOneOf2
	err = newStrictDecoder(data).Decode(&dst.CURegStateOneOf2)
	if err == nil {
		jsonCURegStateOneOf2, _ := json.Marshal(dst.CURegStateOneOf2)
		if string(jsonCURegStateOneOf2) == "{}" { // empty struct
			dst.CURegStateOneOf2 = nil
		} else {
			if err = validator.Validate(dst.CURegStateOneOf2); err != nil {
				dst.CURegStateOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CURegStateOneOf2 = nil
	}

	// try to unmarshal data into CURegStateOneOf3
	err = newStrictDecoder(data).Decode(&dst.CURegStateOneOf3)
	if err == nil {
		jsonCURegStateOneOf3, _ := json.Marshal(dst.CURegStateOneOf3)
		if string(jsonCURegStateOneOf3) == "{}" { // empty struct
			dst.CURegStateOneOf3 = nil
		} else {
			if err = validator.Validate(dst.CURegStateOneOf3); err != nil {
				dst.CURegStateOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CURegStateOneOf3 = nil
	}

	// try to unmarshal data into CURegStateOneOf4
	err = newStrictDecoder(data).Decode(&dst.CURegStateOneOf4)
	if err == nil {
		jsonCURegStateOneOf4, _ := json.Marshal(dst.CURegStateOneOf4)
		if string(jsonCURegStateOneOf4) == "{}" { // empty struct
			dst.CURegStateOneOf4 = nil
		} else {
			if err = validator.Validate(dst.CURegStateOneOf4); err != nil {
				dst.CURegStateOneOf4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CURegStateOneOf4 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CURegStateOneOf = nil
		dst.CURegStateOneOf1 = nil
		dst.CURegStateOneOf2 = nil
		dst.CURegStateOneOf3 = nil
		dst.CURegStateOneOf4 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CURegState)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CURegState)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CURegState) MarshalJSON() ([]byte, error) {
	if src.CURegStateOneOf != nil {
		return json.Marshal(&src.CURegStateOneOf)
	}

	if src.CURegStateOneOf1 != nil {
		return json.Marshal(&src.CURegStateOneOf1)
	}

	if src.CURegStateOneOf2 != nil {
		return json.Marshal(&src.CURegStateOneOf2)
	}

	if src.CURegStateOneOf3 != nil {
		return json.Marshal(&src.CURegStateOneOf3)
	}

	if src.CURegStateOneOf4 != nil {
		return json.Marshal(&src.CURegStateOneOf4)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CURegState) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CURegStateOneOf != nil {
		return obj.CURegStateOneOf
	}

	if obj.CURegStateOneOf1 != nil {
		return obj.CURegStateOneOf1
	}

	if obj.CURegStateOneOf2 != nil {
		return obj.CURegStateOneOf2
	}

	if obj.CURegStateOneOf3 != nil {
		return obj.CURegStateOneOf3
	}

	if obj.CURegStateOneOf4 != nil {
		return obj.CURegStateOneOf4
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CURegState) GetActualInstanceValue() (interface{}) {
	if obj.CURegStateOneOf != nil {
		return *obj.CURegStateOneOf
	}

	if obj.CURegStateOneOf1 != nil {
		return *obj.CURegStateOneOf1
	}

	if obj.CURegStateOneOf2 != nil {
		return *obj.CURegStateOneOf2
	}

	if obj.CURegStateOneOf3 != nil {
		return *obj.CURegStateOneOf3
	}

	if obj.CURegStateOneOf4 != nil {
		return *obj.CURegStateOneOf4
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableCURegState struct {
	value *CURegState
	isSet bool
}

func (v NullableCURegState) Get() *CURegState {
	return v.value
}

func (v *NullableCURegState) Set(val *CURegState) {
	v.value = val
	v.isSet = true
}

func (v NullableCURegState) IsSet() bool {
	return v.isSet
}

func (v *NullableCURegState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCURegState(val *CURegState) *NullableCURegState {
	return &NullableCURegState{value: val, isSet: true}
}

func (v NullableCURegState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCURegState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


