/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModifyList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModifyList{}

// ModifyList struct for ModifyList
type ModifyList struct {
	Mods []Modify `json:"mods"`
}

type _ModifyList ModifyList

// NewModifyList instantiates a new ModifyList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyList(mods []Modify) *ModifyList {
	this := ModifyList{}
	this.Mods = mods
	return &this
}

// NewModifyListWithDefaults instantiates a new ModifyList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyListWithDefaults() *ModifyList {
	this := ModifyList{}
	return &this
}

// GetMods returns the Mods field value
func (o *ModifyList) GetMods() []Modify {
	if o == nil {
		var ret []Modify
		return ret
	}

	return o.Mods
}

// GetModsOk returns a tuple with the Mods field value
// and a boolean to check if the value has been set.
func (o *ModifyList) GetModsOk() ([]Modify, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mods, true
}

// SetMods sets field value
func (o *ModifyList) SetMods(v []Modify) {
	o.Mods = v
}

func (o ModifyList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mods"] = o.Mods
	return toSerialize, nil
}

func (o *ModifyList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mods",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModifyList := _ModifyList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModifyList)

	if err != nil {
		return err
	}

	*o = ModifyList(varModifyList)

	return err
}

type NullableModifyList struct {
	value *ModifyList
	isSet bool
}

func (v NullableModifyList) Get() *ModifyList {
	return v.value
}

func (v *NullableModifyList) Set(val *ModifyList) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyList) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyList(val *ModifyList) *NullableModifyList {
	return &NullableModifyList{value: val, isSet: true}
}

func (v NullableModifyList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


