/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// OperationError - struct for OperationError
type OperationError struct {
	OperationErrorOneOf *OperationErrorOneOf
	OperationErrorOneOf1 *OperationErrorOneOf1
	OperationErrorOneOf10 *OperationErrorOneOf10
	OperationErrorOneOf11 *OperationErrorOneOf11
	OperationErrorOneOf12 *OperationErrorOneOf12
	OperationErrorOneOf13 *OperationErrorOneOf13
	OperationErrorOneOf14 *OperationErrorOneOf14
	OperationErrorOneOf15 *OperationErrorOneOf15
	OperationErrorOneOf2 *OperationErrorOneOf2
	OperationErrorOneOf3 *OperationErrorOneOf3
	OperationErrorOneOf4 *OperationErrorOneOf4
	OperationErrorOneOf5 *OperationErrorOneOf5
	OperationErrorOneOf6 *OperationErrorOneOf6
	OperationErrorOneOf7 *OperationErrorOneOf7
	OperationErrorOneOf8 *OperationErrorOneOf8
	OperationErrorOneOf9 *OperationErrorOneOf9
	String *string
}

// OperationErrorOneOfAsOperationError is a convenience function that returns OperationErrorOneOf wrapped in OperationError
func OperationErrorOneOfAsOperationError(v *OperationErrorOneOf) OperationError {
	return OperationError{
		OperationErrorOneOf: v,
	}
}

// OperationErrorOneOf1AsOperationError is a convenience function that returns OperationErrorOneOf1 wrapped in OperationError
func OperationErrorOneOf1AsOperationError(v *OperationErrorOneOf1) OperationError {
	return OperationError{
		OperationErrorOneOf1: v,
	}
}

// OperationErrorOneOf10AsOperationError is a convenience function that returns OperationErrorOneOf10 wrapped in OperationError
func OperationErrorOneOf10AsOperationError(v *OperationErrorOneOf10) OperationError {
	return OperationError{
		OperationErrorOneOf10: v,
	}
}

// OperationErrorOneOf11AsOperationError is a convenience function that returns OperationErrorOneOf11 wrapped in OperationError
func OperationErrorOneOf11AsOperationError(v *OperationErrorOneOf11) OperationError {
	return OperationError{
		OperationErrorOneOf11: v,
	}
}

// OperationErrorOneOf12AsOperationError is a convenience function that returns OperationErrorOneOf12 wrapped in OperationError
func OperationErrorOneOf12AsOperationError(v *OperationErrorOneOf12) OperationError {
	return OperationError{
		OperationErrorOneOf12: v,
	}
}

// OperationErrorOneOf13AsOperationError is a convenience function that returns OperationErrorOneOf13 wrapped in OperationError
func OperationErrorOneOf13AsOperationError(v *OperationErrorOneOf13) OperationError {
	return OperationError{
		OperationErrorOneOf13: v,
	}
}

// OperationErrorOneOf14AsOperationError is a convenience function that returns OperationErrorOneOf14 wrapped in OperationError
func OperationErrorOneOf14AsOperationError(v *OperationErrorOneOf14) OperationError {
	return OperationError{
		OperationErrorOneOf14: v,
	}
}

// OperationErrorOneOf15AsOperationError is a convenience function that returns OperationErrorOneOf15 wrapped in OperationError
func OperationErrorOneOf15AsOperationError(v *OperationErrorOneOf15) OperationError {
	return OperationError{
		OperationErrorOneOf15: v,
	}
}

// OperationErrorOneOf2AsOperationError is a convenience function that returns OperationErrorOneOf2 wrapped in OperationError
func OperationErrorOneOf2AsOperationError(v *OperationErrorOneOf2) OperationError {
	return OperationError{
		OperationErrorOneOf2: v,
	}
}

// OperationErrorOneOf3AsOperationError is a convenience function that returns OperationErrorOneOf3 wrapped in OperationError
func OperationErrorOneOf3AsOperationError(v *OperationErrorOneOf3) OperationError {
	return OperationError{
		OperationErrorOneOf3: v,
	}
}

// OperationErrorOneOf4AsOperationError is a convenience function that returns OperationErrorOneOf4 wrapped in OperationError
func OperationErrorOneOf4AsOperationError(v *OperationErrorOneOf4) OperationError {
	return OperationError{
		OperationErrorOneOf4: v,
	}
}

// OperationErrorOneOf5AsOperationError is a convenience function that returns OperationErrorOneOf5 wrapped in OperationError
func OperationErrorOneOf5AsOperationError(v *OperationErrorOneOf5) OperationError {
	return OperationError{
		OperationErrorOneOf5: v,
	}
}

// OperationErrorOneOf6AsOperationError is a convenience function that returns OperationErrorOneOf6 wrapped in OperationError
func OperationErrorOneOf6AsOperationError(v *OperationErrorOneOf6) OperationError {
	return OperationError{
		OperationErrorOneOf6: v,
	}
}

// OperationErrorOneOf7AsOperationError is a convenience function that returns OperationErrorOneOf7 wrapped in OperationError
func OperationErrorOneOf7AsOperationError(v *OperationErrorOneOf7) OperationError {
	return OperationError{
		OperationErrorOneOf7: v,
	}
}

// OperationErrorOneOf8AsOperationError is a convenience function that returns OperationErrorOneOf8 wrapped in OperationError
func OperationErrorOneOf8AsOperationError(v *OperationErrorOneOf8) OperationError {
	return OperationError{
		OperationErrorOneOf8: v,
	}
}

// OperationErrorOneOf9AsOperationError is a convenience function that returns OperationErrorOneOf9 wrapped in OperationError
func OperationErrorOneOf9AsOperationError(v *OperationErrorOneOf9) OperationError {
	return OperationError{
		OperationErrorOneOf9: v,
	}
}

// stringAsOperationError is a convenience function that returns string wrapped in OperationError
func StringAsOperationError(v *string) OperationError {
	return OperationError{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *OperationError) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into OperationErrorOneOf
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf)
	if err == nil {
		jsonOperationErrorOneOf, _ := json.Marshal(dst.OperationErrorOneOf)
		if string(jsonOperationErrorOneOf) == "{}" { // empty struct
			dst.OperationErrorOneOf = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf); err != nil {
				dst.OperationErrorOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf = nil
	}

	// try to unmarshal data into OperationErrorOneOf1
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf1)
	if err == nil {
		jsonOperationErrorOneOf1, _ := json.Marshal(dst.OperationErrorOneOf1)
		if string(jsonOperationErrorOneOf1) == "{}" { // empty struct
			dst.OperationErrorOneOf1 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf1); err != nil {
				dst.OperationErrorOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf1 = nil
	}

	// try to unmarshal data into OperationErrorOneOf10
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf10)
	if err == nil {
		jsonOperationErrorOneOf10, _ := json.Marshal(dst.OperationErrorOneOf10)
		if string(jsonOperationErrorOneOf10) == "{}" { // empty struct
			dst.OperationErrorOneOf10 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf10); err != nil {
				dst.OperationErrorOneOf10 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf10 = nil
	}

	// try to unmarshal data into OperationErrorOneOf11
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf11)
	if err == nil {
		jsonOperationErrorOneOf11, _ := json.Marshal(dst.OperationErrorOneOf11)
		if string(jsonOperationErrorOneOf11) == "{}" { // empty struct
			dst.OperationErrorOneOf11 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf11); err != nil {
				dst.OperationErrorOneOf11 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf11 = nil
	}

	// try to unmarshal data into OperationErrorOneOf12
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf12)
	if err == nil {
		jsonOperationErrorOneOf12, _ := json.Marshal(dst.OperationErrorOneOf12)
		if string(jsonOperationErrorOneOf12) == "{}" { // empty struct
			dst.OperationErrorOneOf12 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf12); err != nil {
				dst.OperationErrorOneOf12 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf12 = nil
	}

	// try to unmarshal data into OperationErrorOneOf13
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf13)
	if err == nil {
		jsonOperationErrorOneOf13, _ := json.Marshal(dst.OperationErrorOneOf13)
		if string(jsonOperationErrorOneOf13) == "{}" { // empty struct
			dst.OperationErrorOneOf13 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf13); err != nil {
				dst.OperationErrorOneOf13 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf13 = nil
	}

	// try to unmarshal data into OperationErrorOneOf14
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf14)
	if err == nil {
		jsonOperationErrorOneOf14, _ := json.Marshal(dst.OperationErrorOneOf14)
		if string(jsonOperationErrorOneOf14) == "{}" { // empty struct
			dst.OperationErrorOneOf14 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf14); err != nil {
				dst.OperationErrorOneOf14 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf14 = nil
	}

	// try to unmarshal data into OperationErrorOneOf15
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf15)
	if err == nil {
		jsonOperationErrorOneOf15, _ := json.Marshal(dst.OperationErrorOneOf15)
		if string(jsonOperationErrorOneOf15) == "{}" { // empty struct
			dst.OperationErrorOneOf15 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf15); err != nil {
				dst.OperationErrorOneOf15 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf15 = nil
	}

	// try to unmarshal data into OperationErrorOneOf2
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf2)
	if err == nil {
		jsonOperationErrorOneOf2, _ := json.Marshal(dst.OperationErrorOneOf2)
		if string(jsonOperationErrorOneOf2) == "{}" { // empty struct
			dst.OperationErrorOneOf2 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf2); err != nil {
				dst.OperationErrorOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf2 = nil
	}

	// try to unmarshal data into OperationErrorOneOf3
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf3)
	if err == nil {
		jsonOperationErrorOneOf3, _ := json.Marshal(dst.OperationErrorOneOf3)
		if string(jsonOperationErrorOneOf3) == "{}" { // empty struct
			dst.OperationErrorOneOf3 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf3); err != nil {
				dst.OperationErrorOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf3 = nil
	}

	// try to unmarshal data into OperationErrorOneOf4
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf4)
	if err == nil {
		jsonOperationErrorOneOf4, _ := json.Marshal(dst.OperationErrorOneOf4)
		if string(jsonOperationErrorOneOf4) == "{}" { // empty struct
			dst.OperationErrorOneOf4 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf4); err != nil {
				dst.OperationErrorOneOf4 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf4 = nil
	}

	// try to unmarshal data into OperationErrorOneOf5
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf5)
	if err == nil {
		jsonOperationErrorOneOf5, _ := json.Marshal(dst.OperationErrorOneOf5)
		if string(jsonOperationErrorOneOf5) == "{}" { // empty struct
			dst.OperationErrorOneOf5 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf5); err != nil {
				dst.OperationErrorOneOf5 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf5 = nil
	}

	// try to unmarshal data into OperationErrorOneOf6
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf6)
	if err == nil {
		jsonOperationErrorOneOf6, _ := json.Marshal(dst.OperationErrorOneOf6)
		if string(jsonOperationErrorOneOf6) == "{}" { // empty struct
			dst.OperationErrorOneOf6 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf6); err != nil {
				dst.OperationErrorOneOf6 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf6 = nil
	}

	// try to unmarshal data into OperationErrorOneOf7
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf7)
	if err == nil {
		jsonOperationErrorOneOf7, _ := json.Marshal(dst.OperationErrorOneOf7)
		if string(jsonOperationErrorOneOf7) == "{}" { // empty struct
			dst.OperationErrorOneOf7 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf7); err != nil {
				dst.OperationErrorOneOf7 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf7 = nil
	}

	// try to unmarshal data into OperationErrorOneOf8
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf8)
	if err == nil {
		jsonOperationErrorOneOf8, _ := json.Marshal(dst.OperationErrorOneOf8)
		if string(jsonOperationErrorOneOf8) == "{}" { // empty struct
			dst.OperationErrorOneOf8 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf8); err != nil {
				dst.OperationErrorOneOf8 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf8 = nil
	}

	// try to unmarshal data into OperationErrorOneOf9
	err = newStrictDecoder(data).Decode(&dst.OperationErrorOneOf9)
	if err == nil {
		jsonOperationErrorOneOf9, _ := json.Marshal(dst.OperationErrorOneOf9)
		if string(jsonOperationErrorOneOf9) == "{}" { // empty struct
			dst.OperationErrorOneOf9 = nil
		} else {
			if err = validator.Validate(dst.OperationErrorOneOf9); err != nil {
				dst.OperationErrorOneOf9 = nil
			} else {
				match++
			}
		}
	} else {
		dst.OperationErrorOneOf9 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.OperationErrorOneOf = nil
		dst.OperationErrorOneOf1 = nil
		dst.OperationErrorOneOf10 = nil
		dst.OperationErrorOneOf11 = nil
		dst.OperationErrorOneOf12 = nil
		dst.OperationErrorOneOf13 = nil
		dst.OperationErrorOneOf14 = nil
		dst.OperationErrorOneOf15 = nil
		dst.OperationErrorOneOf2 = nil
		dst.OperationErrorOneOf3 = nil
		dst.OperationErrorOneOf4 = nil
		dst.OperationErrorOneOf5 = nil
		dst.OperationErrorOneOf6 = nil
		dst.OperationErrorOneOf7 = nil
		dst.OperationErrorOneOf8 = nil
		dst.OperationErrorOneOf9 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(OperationError)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(OperationError)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src OperationError) MarshalJSON() ([]byte, error) {
	if src.OperationErrorOneOf != nil {
		return json.Marshal(&src.OperationErrorOneOf)
	}

	if src.OperationErrorOneOf1 != nil {
		return json.Marshal(&src.OperationErrorOneOf1)
	}

	if src.OperationErrorOneOf10 != nil {
		return json.Marshal(&src.OperationErrorOneOf10)
	}

	if src.OperationErrorOneOf11 != nil {
		return json.Marshal(&src.OperationErrorOneOf11)
	}

	if src.OperationErrorOneOf12 != nil {
		return json.Marshal(&src.OperationErrorOneOf12)
	}

	if src.OperationErrorOneOf13 != nil {
		return json.Marshal(&src.OperationErrorOneOf13)
	}

	if src.OperationErrorOneOf14 != nil {
		return json.Marshal(&src.OperationErrorOneOf14)
	}

	if src.OperationErrorOneOf15 != nil {
		return json.Marshal(&src.OperationErrorOneOf15)
	}

	if src.OperationErrorOneOf2 != nil {
		return json.Marshal(&src.OperationErrorOneOf2)
	}

	if src.OperationErrorOneOf3 != nil {
		return json.Marshal(&src.OperationErrorOneOf3)
	}

	if src.OperationErrorOneOf4 != nil {
		return json.Marshal(&src.OperationErrorOneOf4)
	}

	if src.OperationErrorOneOf5 != nil {
		return json.Marshal(&src.OperationErrorOneOf5)
	}

	if src.OperationErrorOneOf6 != nil {
		return json.Marshal(&src.OperationErrorOneOf6)
	}

	if src.OperationErrorOneOf7 != nil {
		return json.Marshal(&src.OperationErrorOneOf7)
	}

	if src.OperationErrorOneOf8 != nil {
		return json.Marshal(&src.OperationErrorOneOf8)
	}

	if src.OperationErrorOneOf9 != nil {
		return json.Marshal(&src.OperationErrorOneOf9)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *OperationError) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.OperationErrorOneOf != nil {
		return obj.OperationErrorOneOf
	}

	if obj.OperationErrorOneOf1 != nil {
		return obj.OperationErrorOneOf1
	}

	if obj.OperationErrorOneOf10 != nil {
		return obj.OperationErrorOneOf10
	}

	if obj.OperationErrorOneOf11 != nil {
		return obj.OperationErrorOneOf11
	}

	if obj.OperationErrorOneOf12 != nil {
		return obj.OperationErrorOneOf12
	}

	if obj.OperationErrorOneOf13 != nil {
		return obj.OperationErrorOneOf13
	}

	if obj.OperationErrorOneOf14 != nil {
		return obj.OperationErrorOneOf14
	}

	if obj.OperationErrorOneOf15 != nil {
		return obj.OperationErrorOneOf15
	}

	if obj.OperationErrorOneOf2 != nil {
		return obj.OperationErrorOneOf2
	}

	if obj.OperationErrorOneOf3 != nil {
		return obj.OperationErrorOneOf3
	}

	if obj.OperationErrorOneOf4 != nil {
		return obj.OperationErrorOneOf4
	}

	if obj.OperationErrorOneOf5 != nil {
		return obj.OperationErrorOneOf5
	}

	if obj.OperationErrorOneOf6 != nil {
		return obj.OperationErrorOneOf6
	}

	if obj.OperationErrorOneOf7 != nil {
		return obj.OperationErrorOneOf7
	}

	if obj.OperationErrorOneOf8 != nil {
		return obj.OperationErrorOneOf8
	}

	if obj.OperationErrorOneOf9 != nil {
		return obj.OperationErrorOneOf9
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj OperationError) GetActualInstanceValue() (interface{}) {
	if obj.OperationErrorOneOf != nil {
		return *obj.OperationErrorOneOf
	}

	if obj.OperationErrorOneOf1 != nil {
		return *obj.OperationErrorOneOf1
	}

	if obj.OperationErrorOneOf10 != nil {
		return *obj.OperationErrorOneOf10
	}

	if obj.OperationErrorOneOf11 != nil {
		return *obj.OperationErrorOneOf11
	}

	if obj.OperationErrorOneOf12 != nil {
		return *obj.OperationErrorOneOf12
	}

	if obj.OperationErrorOneOf13 != nil {
		return *obj.OperationErrorOneOf13
	}

	if obj.OperationErrorOneOf14 != nil {
		return *obj.OperationErrorOneOf14
	}

	if obj.OperationErrorOneOf15 != nil {
		return *obj.OperationErrorOneOf15
	}

	if obj.OperationErrorOneOf2 != nil {
		return *obj.OperationErrorOneOf2
	}

	if obj.OperationErrorOneOf3 != nil {
		return *obj.OperationErrorOneOf3
	}

	if obj.OperationErrorOneOf4 != nil {
		return *obj.OperationErrorOneOf4
	}

	if obj.OperationErrorOneOf5 != nil {
		return *obj.OperationErrorOneOf5
	}

	if obj.OperationErrorOneOf6 != nil {
		return *obj.OperationErrorOneOf6
	}

	if obj.OperationErrorOneOf7 != nil {
		return *obj.OperationErrorOneOf7
	}

	if obj.OperationErrorOneOf8 != nil {
		return *obj.OperationErrorOneOf8
	}

	if obj.OperationErrorOneOf9 != nil {
		return *obj.OperationErrorOneOf9
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableOperationError struct {
	value *OperationError
	isSet bool
}

func (v NullableOperationError) Get() *OperationError {
	return v.value
}

func (v *NullableOperationError) Set(val *OperationError) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationError) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationError(val *OperationError) *NullableOperationError {
	return &NullableOperationError{value: val, isSet: true}
}

func (v NullableOperationError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


