/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OperationErrorOneOf4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperationErrorOneOf4{}

// OperationErrorOneOf4 struct for OperationErrorOneOf4
type OperationErrorOneOf4 struct {
	Plugin PluginError `json:"plugin"`
}

type _OperationErrorOneOf4 OperationErrorOneOf4

// NewOperationErrorOneOf4 instantiates a new OperationErrorOneOf4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationErrorOneOf4(plugin PluginError) *OperationErrorOneOf4 {
	this := OperationErrorOneOf4{}
	this.Plugin = plugin
	return &this
}

// NewOperationErrorOneOf4WithDefaults instantiates a new OperationErrorOneOf4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationErrorOneOf4WithDefaults() *OperationErrorOneOf4 {
	this := OperationErrorOneOf4{}
	return &this
}

// GetPlugin returns the Plugin field value
func (o *OperationErrorOneOf4) GetPlugin() PluginError {
	if o == nil {
		var ret PluginError
		return ret
	}

	return o.Plugin
}

// GetPluginOk returns a tuple with the Plugin field value
// and a boolean to check if the value has been set.
func (o *OperationErrorOneOf4) GetPluginOk() (*PluginError, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plugin, true
}

// SetPlugin sets field value
func (o *OperationErrorOneOf4) SetPlugin(v PluginError) {
	o.Plugin = v
}

func (o OperationErrorOneOf4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperationErrorOneOf4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plugin"] = o.Plugin
	return toSerialize, nil
}

func (o *OperationErrorOneOf4) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plugin",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOperationErrorOneOf4 := _OperationErrorOneOf4{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOperationErrorOneOf4)

	if err != nil {
		return err
	}

	*o = OperationErrorOneOf4(varOperationErrorOneOf4)

	return err
}

type NullableOperationErrorOneOf4 struct {
	value *OperationErrorOneOf4
	isSet bool
}

func (v NullableOperationErrorOneOf4) Get() *OperationErrorOneOf4 {
	return v.value
}

func (v *NullableOperationErrorOneOf4) Set(val *OperationErrorOneOf4) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationErrorOneOf4) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationErrorOneOf4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationErrorOneOf4(val *OperationErrorOneOf4) *NullableOperationErrorOneOf4 {
	return &NullableOperationErrorOneOf4{value: val, isSet: true}
}

func (v NullableOperationErrorOneOf4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationErrorOneOf4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


