/*
Kanidm

API for interacting with the Kanidm system. This is a work in progress.

API version: 1.10.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UatPurposeOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UatPurposeOneOf{}

// UatPurposeOneOf struct for UatPurposeOneOf
type UatPurposeOneOf struct {
	Readwrite UatPurposeOneOfReadwrite `json:"readwrite"`
}

type _UatPurposeOneOf UatPurposeOneOf

// NewUatPurposeOneOf instantiates a new UatPurposeOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUatPurposeOneOf(readwrite UatPurposeOneOfReadwrite) *UatPurposeOneOf {
	this := UatPurposeOneOf{}
	this.Readwrite = readwrite
	return &this
}

// NewUatPurposeOneOfWithDefaults instantiates a new UatPurposeOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUatPurposeOneOfWithDefaults() *UatPurposeOneOf {
	this := UatPurposeOneOf{}
	return &this
}

// GetReadwrite returns the Readwrite field value
func (o *UatPurposeOneOf) GetReadwrite() UatPurposeOneOfReadwrite {
	if o == nil {
		var ret UatPurposeOneOfReadwrite
		return ret
	}

	return o.Readwrite
}

// GetReadwriteOk returns a tuple with the Readwrite field value
// and a boolean to check if the value has been set.
func (o *UatPurposeOneOf) GetReadwriteOk() (*UatPurposeOneOfReadwrite, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Readwrite, true
}

// SetReadwrite sets field value
func (o *UatPurposeOneOf) SetReadwrite(v UatPurposeOneOfReadwrite) {
	o.Readwrite = v
}

func (o UatPurposeOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UatPurposeOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["readwrite"] = o.Readwrite
	return toSerialize, nil
}

func (o *UatPurposeOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"readwrite",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUatPurposeOneOf := _UatPurposeOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUatPurposeOneOf)

	if err != nil {
		return err
	}

	*o = UatPurposeOneOf(varUatPurposeOneOf)

	return err
}

type NullableUatPurposeOneOf struct {
	value *UatPurposeOneOf
	isSet bool
}

func (v NullableUatPurposeOneOf) Get() *UatPurposeOneOf {
	return v.value
}

func (v *NullableUatPurposeOneOf) Set(val *UatPurposeOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableUatPurposeOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableUatPurposeOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUatPurposeOneOf(val *UatPurposeOneOf) *NullableUatPurposeOneOf {
	return &NullableUatPurposeOneOf{value: val, isSet: true}
}

func (v NullableUatPurposeOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUatPurposeOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


