/*
Kanidm

Testing PersonSshPubkeysAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/slop-incubator/go-kanidm/internal/api"
)

func Test_api_PersonSshPubkeysAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PersonSshPubkeysAPIService PersonIdSshPubkeysGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.PersonSshPubkeysAPI.PersonIdSshPubkeysGet(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PersonSshPubkeysAPIService PersonIdSshPubkeysPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.PersonSshPubkeysAPI.PersonIdSshPubkeysPost(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PersonSshPubkeysAPIService PersonIdSshPubkeysTagDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tag string
		var id string

		httpRes, err := apiClient.PersonSshPubkeysAPI.PersonIdSshPubkeysTagDelete(context.Background(), tag, id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PersonSshPubkeysAPIService PersonIdSshPubkeysTagGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var tag string

		resp, httpRes, err := apiClient.PersonSshPubkeysAPI.PersonIdSshPubkeysTagGet(context.Background(), id, tag).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
