/*
Kanidm

Testing GroupAttrAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/slop-incubator/go-kanidm/internal/api"
)

func Test_api_GroupAttrAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GroupAttrAPIService GroupIdAttrDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var attr string

		httpRes, err := apiClient.GroupAttrAPI.GroupIdAttrDelete(context.Background(), id, attr).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GroupAttrAPIService GroupIdAttrGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var attr string

		resp, httpRes, err := apiClient.GroupAttrAPI.GroupIdAttrGet(context.Background(), id, attr).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GroupAttrAPIService GroupIdAttrPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var attr string

		httpRes, err := apiClient.GroupAttrAPI.GroupIdAttrPost(context.Background(), id, attr).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GroupAttrAPIService GroupIdAttrPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var attr string

		httpRes, err := apiClient.GroupAttrAPI.GroupIdAttrPut(context.Background(), id, attr).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
