/*
Kanidm

Testing PersonAttrAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/slop-incubator/go-kanidm/internal/api"
)

func Test_api_PersonAttrAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PersonAttrAPIService PersonIdDeleteAttr", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var attr string

		httpRes, err := apiClient.PersonAttrAPI.PersonIdDeleteAttr(context.Background(), id, attr).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PersonAttrAPIService PersonIdGetAttr", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var attr string

		resp, httpRes, err := apiClient.PersonAttrAPI.PersonIdGetAttr(context.Background(), id, attr).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PersonAttrAPIService PersonIdPostAttr", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var attr string

		httpRes, err := apiClient.PersonAttrAPI.PersonIdPostAttr(context.Background(), id, attr).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PersonAttrAPIService PersonIdPutAttr", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string
		var attr string

		httpRes, err := apiClient.PersonAttrAPI.PersonIdPutAttr(context.Background(), id, attr).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
